### ISSUE TITLE
אי אפשר לחזור אחורה בניווט בספרים - זה חוזר למסך הראשי

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#1]
כשאני מנסה לחזור אחורה תוך כדי ניווט בספרים, התוכנה חוזרת למסך הראשי, במקום שלב אחד אחורה בניווט.
מצורף סרטון.
ישר כוח!

https://github.com/Sivan22/otzaria/assets/76535872/f781a6f3-04a6-40ba-8b47-41ee00c9196b

**Comment by Sivan22** [comment]
thank you for your feedback. that will be fixed in the next (pre) release.
