### ISSUE TITLE
רשימת שיפורים מוצעים

### ISSUE THREAD

**Issue by shimonshe** [Sivan22/otzaria#10]
לכבוד @sivan22 אני @ששמעון מפורום מתמחים,
שמחנו מאוד לראות את התוכנה החדשה, היא ממש מעולה למרות שהיא עדיין באמצע הפיתוח. אני נעזר בה הרבה, וכבר העברתי לחברים ומאוד מאוד נהנים. ממש תודה רבה, תבורך מפי עליון.
הייתי רוצה להציע כמה שיפורים ותיקונים לתוכנה, [מן הסתם על חלק מהם אתה כבר עובד], מה ששמתי לב במהלך עבודתי.

א - כיוון הבחירה [עם מקש שיפט] מימין לשמאל ומלמעלה למטה, כרגע כשבוחרים עם החיצים זה עובד הכל הפוך.
ב - אפשרות לנעוץ את רשימת הניווט בגלילת הספר [כרגע הוא נסגר אוטומטית כשמתחילים לגלול].
ג - שיפור מהירות החיפוש בכל מאגר [אולי ע"י אינדקס], כדאי להוסיף אפשרות יצירת אינדקס נפרד לספרים הנוספים ע"י המשתמש.
ד - אפשרות ניווט ובחירה עם סמן בתוכן הספר.
ה - לסמן ב'ניווט' את השערים או הפרקים באופן שונה מהפרקים או ההלכות [כלומר שיהיה אפשר למצוא בקלות דף מסויים בתוך פרק מסויים], אולי עדיף תפריט נפתח ומתכווץ, כמו בדפדוף.
ו - סדר הספרים בדפדוף עדיף שיהיה כרונולוגי או נושאי, ולא לפי א"ב כמו עכשיו, מיקל למצוא.
ז - אפשרות שמירת החלונות הפתוחים לפעם הבאה.
ח - אפשרות שהקישורים והפרשנות ייפתחו בחלון נפרד או כרטיסיה נפרדת, או באזור אחר לצד הטקסט הראשי. כדאי גם להוסיף אפשרות כיווץ והרחבת החלונות השונים ע"י גרירת הסמן.

**Comment by Sivan22** [comment]
תודה על ההערות.
א. זה באג בספריית flutter ולא בקוד שלי. בינתיים לא מצאתי פתרון.
ב, ג, ו, ז - בתכנון.
ה - כבר קיים בגירסה 0.1.3+1
ח - בלחיצה כפולה על קטע פרשנות הוא ייפתח בחלון חדש. בלחיצה בודדת הוא יתכווץ. קישורים נפתחים תמיד בחלון חדש.
לגבי הסמן, זה כרגע לא בתכנון, בין השאר משום שהתוכנה תומכת במסכי מגע ובאנדרואיד.

**Comment by Danthig** [comment]
שיפורים שאני חושב שיהיה כדאי, זה בלחיצה ימנית על הטקסט, יופיע האפשרות לבחור: 
פרשנים 
קישורים
העתקה עם עיצוב
העתקת כותרת (שכרגע לא קיים כלל במאגר).

**Comment by Sivan22** [comment]
שיפור "ב" נוסף בגרסה 0.1.4

**Comment by Y-PLONI** [comment]
תודה רבה!!!
האם יש עניין לכתוב באנגלית?

**Comment by Sivan22** [comment]
In the software development industry, English is commonly used as the primary language. 
עם זאת, קהל היעד של המשתמשים הוא דוברי עברית, ולכן אשתדל להוסיף הסברים גם בעברית.

**Comment by SBW88** [comment]
בחיפוש בPDF שנוספו למאגר, הוא אכן מחפש ומוצא את העמוד אך לא את המיקום המדויק של של מילות החיפוש.
