### ISSUE TITLE
בתצוגת הניווט

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#100]
כאשר יש כותרת 1 ומיד אחריה [כמה] כותרות 3 ורק אחרי כמה כותרות 3 יש כותרת 2, מופיעים תחילה כותרות 2, ואחריהם כותרת 3. 
דוגמא:
[שאגת אריה.txt](https://github.com/Sivan22/otzaria/files/15312433/default.txt)

**Comment by Sivan22** [comment]
זהו מצב שאמור להיות בלתי אפשרי, כי כותרת 3 היא תמיד תחת כותרת 2. אם אין מה לכתוב בכותרת 2, אז פשוט יוצרים כותרת 2 ריקה. כך יש בספרים רבים שיש הקדמה וגוף הספר, גוף הספר זו כותרת ריקה.

**Comment by Danthig** [comment]
> זהו מצב שאמור להיות בלתי אפשרי, כי כותרת 3 היא תמיד תחת כותרת 2. אם אין מה לכתוב בכותרת 2, אז פשוט יוצרים כותרת 2 ריקה. כך יש בספרים רבים שיש הקדמה וגוף הספר, גוף הספר זו כותרת ריקה.

אני מבין שזה גם הפתרון למצב שבו יש כותרת 2, ומיד אחריה כמה פסקאות ללא כותרת 3, ורק אחר כך יש כותרת 3, כדי שיהיה ניתן בלחיצה להגיע לפיסקאות שמיד אחרי כותרת 2. 

השאלה היא האם לא ניתן שבלחיצה על כותרת 2, הספר יגלל לכותרת 2, ולא רק בלחיצה על כותרת 3 המסמך יגלל אליו.

**Comment by Sivan22** [comment]
זה באמת נקודה שכדאי לתקן, בדומה למה שיש בכותרות בוורד, שגם הרמות העליונות
לחיצות.

בתאריך יום ד׳, 15 במאי 2024, 1:17, מאת Danthig ***@***.***>:

**Comment by Sivan22** [comment]
תוקן בסייעתא דשמיא.
