### ISSUE TITLE
באג; חוזר לתחילת הספר בפתיחת החלון מחדש

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#101]
כאשר פותחים כרטיסיה עם פרשנים, ומדפדפים אל תוך הספר, בסגירת החלון הוא חוזר לתחילת הספר

**Comment by Sivan22** [comment]
https://github.com/Sivan22/otzaria/issues/76

**Comment by Refael11** [comment]
יתכן שמדובר באותו באג שבתבטא בשני תופעות, אבל מדובר בשני בעיות שונות
ב#76 אני מדבר על כך שכאשר אתה בוחר פרשן הוא מחזיר אותך לתחילת הספר
עכשיו אני מדבר על כך שכל כרטיסיה שמצגים בה פרשנים, בסגירת התוכנה ופתיחתה מחדש הכרטיסיה חוזרת לתחילת הספר
לתשומת לב @Sivan22
