### ISSUE TITLE
אין כותרות בספר מחנה אפרים

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#102]
הכותרות בספר מחנה אפרים לא מוגדרות כך שאין שום אפשרות לנווט

**Comment by YOSEFTT** [comment]
כי זה ממאגר ספרי דיקטה.
כרגע אין להם עדיין כותרות בכלל,
יש ספרים שאפילו המקטעים לא מסודרים מספיק.

עובדים ע"ז כרגע לסדר את זה, אם תרצה להצטרף, תוכל לשלוח לי מייל HUXHTCT@ ג'ימייל.
