### ISSUE TITLE
הצעות נוספות לייעול, בתודה

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#103]
שוב, **בתודה רבה על ההשקעה האדירה**. להלן כמה רעיונות נוספים לשיפור וייעול המערכת, אם טוב בעיניכם:

א. **התקנת תנועת החיצים מימין לשמאל** [אצלי במחשב לחיצה על חץ ימני במקלדת מוליך לשמאל, וכן להיפך].

ב. אפשרות גלילה במסך הספר מעלה ומטה, ולא רק ע"י החיצים אלא גם  ב-PGDN PGUP.

ג. **אפשרות מציאת מקום בתוך ספר** [ניווט] בכתיבת מקורות מלאים, כגון "שבת צד, א" [ומה טוב אם תפתח רשימה של כל הספרים שיש בהם דף כזה, כולל מפרשים וכד'].

ד. **זיהוי שמות הספרים** [והמקורות] בכתי' מלא וחסר [כגון תהלים תהילים, כעת יש כאלה ויש כאלה...., וכן 'קדושין' ו'קידושין'], ור"ת עם ובלי גרשיים [מו"ק ג, א; מוק ג א].

ה. **ייחוס הקשרים והמפרשים** לפיסקה שעומדים בה [נראה שהתחילו לעבוד על זה, לפי מספרי שורות? אולי כדאי לפי 'דיבור המתחיל'?]

ו. **הערות על המחברים** [למשל - מה הוא ספר 'פניני הלכה'? מי המחבר? מהיכן הוא? (אני יודע, אבל לא כולם...) זה עוד קודם הדיון אם ראוי להעיר שיש לו גישה יייחודית בהלכה ורבים החולקים עליו בתוקף גם מכלל רבני הציונות הדתית (אבל זה כאמור נושא הראוי להיות נדון בפני עצמו)].

יישר חילכם לאורייתא וחפץ ה' בידכם יצליח !

**Comment by Sivan22** [comment]
א. לא מצאתי לזה עדיין פתרון (הבעיה לא בקוד שלי אלא בספריות שלא תלויות בי.)
ב. רעיון נחמד.
ג-ד. בתכנון לגרסה 0.2
ה. המפרשים הם על כל הקטעים הגלויים, הקישורים הם כרגע לקטע העליון ביותר שאינו קטוע בתחילתו. 
ו. בגרסה הבאה שבדרך, יופיע שם המחבר, שנת הוצאה ותיאור קצר לכל ספר. ייתכן וייתווסף בהמשך גם תיאור ארוך וכן ביוגרפיה של המחבר.

**Comment by Bshlomecha** [comment]
תודה. בהצלחה.

‫בתאריך יום ד׳, 15 במאי 2024 ב-13:28 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬
