### ISSUE TITLE
בבחירת פרשנים על הספר, הספר נגלל וקופץ להתחלה

### ISSUE THREAD

**Issue by HeroldGr** [Sivan22/otzaria#104]
לדוגמא אני אפתח גמרא מסכת חולין ובפרשנות אסמן V על רש"י, הספר יגלל לתחילת המסכת. מצורף וידאו. גירסה 0.1.6
תודה רבה

https://github.com/Sivan22/otzaria/assets/103885041/53e9d3d9-5be1-4c29-b7fd-c092a4a33963

**Comment by Danthig** [comment]
https://github.com/Sivan22/otzaria/issues/76
תוקן בגרסה 0.1.7
