### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by avrahamahlomo** [Sivan22/otzaria#106]
במצב כהה בתכנה יש כמה באגים
א. בספריה הרקעים (המרובעים) לא מספיק מודגשים
ב. בחלון עיון נפתח התפריט של ניווט/פרשנות בצבע לבן וכתב חלש ולא ברור
וכן כששורת המשימות על מצב כהה הסמל לא מספיק ברור

**Comment by Sivan22** [comment]
בינתיים טיפלתי בב וג.
