### ISSUE TITLE
קיבוץ כרטיסיות/סשנים נפרדים

### ISSUE THREAD

**Issue by zevisvei** [Sivan22/otzaria#107]
לדעתי יהיה מאוד נח אם ניתן יהיה לפתוח את התוכנה בסשנים נפרדים(היה מישהו במתמחים שעשה משהו כזה לבר אילן, לא מוצא כרגע) או לחילופין לקבץ כרטיסיות(כעין מה שקיים בכרום - "הוסף כרטיסייה לקבוצה")
וכך ניתן יהיה להשתמש בתוכנה בנוחות גם בכמה נושאים בו זמנית

**Comment by Danthig** [comment]
כבר נפתח על זה נושא

**Comment by Y-PLONI** [comment]
איפה?

**Comment by Sivan22** [comment]
הקונספט שחשבתי עליו הוא "שולחן עבודה", ניתן יהיה לשמור את כל הסביבה בשלמותה במועדפים, כמו סימניות והיסטוריה, כך יהיו סביבות עבודה שלמות שמורות וניתן יהיה להחליף סביבת עבודה. [בכל סגירה של כלל הכרטיסיות ביחד, תתווסף אוטומטית הסביבה הנסגרת לסביבות העבודה.] סביבת עבודה תכלול את כל הכרטיסיות הפתוחות, כולל המפרשים.  
גם היום ניתן לפתוח את התוכנה פעמיים, אך הגדרות מסויימות יהיו שותפות בשני המופעים.
אולי זה כבר ימומש לגרסה 0.1.8

**Comment by Danthig** [comment]
יפה מאוד!!!
זה קיים בפרוייקט השו"ת כבר כמה גרסאות אחורה, אבל לכאורה זה יצרוך זכרון RAM.

**Comment by Sivan22** [comment]
זה בתכנון, ואין סיבה שאם זה כתוב נכון זה יצרוך הרבה זכרון. (זה לא הרבה
מידע, שמות הספרים הפתוחים, המיקום, ושמות הפרשנים הפתוחים)

בתאריך יום ג׳, 6 באוג׳ 2024, 06:40, מאת Danthig ***@***.***>:

**Comment by zevisvei** [comment]
@Sivan22 

לדעתי כדאי לשים לב שתהיה אופציה לקרוא שם לסשן וכן לנעוץ סשנים.

**Comment by Sivan22** [comment]
תהיה אפשרות לקרוא שמות.
מה הפירוש לנעוץ?
כרגע הקונספט הוא רשימה כמו של הסימניות.

בתאריך יום ד׳, 7 באוג׳ 2024, 00:26, מאת zevisvei ***@***.***

**Comment by zevisvei** [comment]
כוונתי לנעוץ - שתהיה אפשרות לבחור מה יופיע בתחילת הרשימה, נניח שבסד"א אני לומד מזוזה, בסדר ב' שחיטה וביום שישי אני לומד פר' שבוע - שתהיה אפשרות שסדר א' וסדר ב' יופיעו בתחילת הרשימה.
