### ISSUE TITLE
pdf | מקש ימני - פתח בתכנה

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#108]
## אני מציע
שכאשר פותחים ספר בתצוגת פי די אף, תהיה אפשרות (מקש ימני) לפתוח את הספר בתוכנה.

### בסיס הרעיון
המעלה בזה, שיהיה נח לכתוב הערות על הספר pdf

### לחילופין
ניתן להוסיף תכונה בתוכנה, "כתוב הערות" שיצופו על גבי הספרים. (אולי כמו בבר אילן, שההערות מאוכסנות במאגר עצמו).

😀תודה_על_התכנה

**Comment by Refael11** [comment]
נשמע קצת יומרני מבחינת הפיתוח, ולדעתי יכול גם להכביד על חלק מהמשתמשים.
אולי אני טועה.. 🤷‍♂️

**Comment by Y-PLONI** [comment]
נראה שהוא התכוון לאפשרות השנייה, לא רואה סיבה סבירה לעשות את, @Sivan22 לסגור?

**Comment by chezfo** [comment]
רצת רחוק!
כמה מסובך לעשות פתח את הספר בתוכנת ברירת מחדל, על ידי הקשה על מקש ימני?
אם לא מקש ימני, ניתן  לעשות לחצן ייעודי לזה.

**Comment by Sivan22** [comment]
נוסף לחצן "שיתוף" שפותח את הקובץ בתוכנת ברירת המחדל (בגרסת המפתחים האחרונה): 
![image](https://github.com/Sivan22/otzaria/assets/89018301/0814bd83-2bef-4680-a43c-d60b392610b9)
