### ISSUE TITLE
חסרון בספרים שהיו קיימים

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#109]
יישר כח על העבודה הנפלאה - זה ממש בשורה אדירה לעולם התורה
כל פעם אנחנו נהנים מחדש לגלות עוד שיפורים והוספות - תודה רבה

 1. במהדורות קודמות היה קיים כף החיים גם על חלק אורח חיים וובגירסה החדשה שיצאה היום נחסר ספר זה.
 2. ספרי החזון איש חסרים החלקים על חושן משפט, קדשים, טהרות.
 3. כיון שהתוכנה קוראת קבצי טקסט/וורד וקבצי pdf  היה רצוי שתהיה אפשרות בתוכנה עצמה לפתוח קבצים שאינם מהמאגר וכך לא יהיו חייבים להוסיפם למאגר כדי לפותחם.
כמו כן רציתי לצרף קובץ של ספר מוסר "מזור ותרופה" לבני הנעורים שיצא לפני 115 שנה

יישר כח
 
[מזור ותרופה ללא אידיש1.docx](https://github.com/Sivan22/otzaria/files/15379254/1.docx)

**Comment by Danthig** [comment]
> 2\. ספרי החזון איש חסרים החלקים על חושן משפט, קדשים, טהרות.

יש לך אותם? אם כך תוכל לזכות את הרבים!!!
כמו כן גם בשאר ספרי רבותינו.

**Comment by Danthig** [comment]
> 1. במהדורות קודמות היה קיים כף החיים גם על חלק אורח חיים וובגירסה החדשה שיצאה היום נחסר ספר זה.

מענין שהקובץ JSON קיים על אורח חיים @Sivan22 ?

**Comment by YOSEFTT** [comment]
ייש"כ על הספר @cc054848484 נשמח בעוד!!!

**Comment by Y-PLONI** [comment]
למעשה, למישהו יש את החזו"א?

**Comment by Danthig** [comment]
> למעשה, למישהו יש את החזו"א?

https://beta.hebrewbooks.org/home#gsc.tab=0
