### ISSUE TITLE
שם הספר מופיע בצד ימין בכיתוב מלמעלה למטה, על גבי התפריט

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#11]
![image](https://github.com/Sivan22/otzaria/assets/76535872/1c2c00f7-d25b-4b9f-9cbc-8d484551fc74)
גרסא 0.1.3+1
אגב, אולי כדאי להוסיף בהגדרות כיתוב איזה גרסא זה?
תודה רבה!

**Comment by Sivan22** [comment]
הבאג נפתר, יתוקן בגרסאות הבאות בעזרת ה'.
