### ISSUE TITLE
איתור ספר | הצג תיקיות מתאימות

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#113]
## ההצעה
כאשר מציג את הספרים באיתור לפי שם, יציג גם תיקייה עם שם מתאים.

### המטרה
לפעמים יש לאדם תיקייה עם נושא לדוג': שירת הים בתוכו ישנם המון מאמרים. תן לו את האפשרות לכתוב "שירת הים והתיקייה תוצג.

### תוספת
ניתן להבדיל באופן ויזואלי בין תיקייה מכילה לקובץ

#### בהדגמה ניתן לראות, כי לא מופיעה התיקייה הראשית "תנך"
![אנימציה](https://github.com/Sivan22/otzaria/assets/85172877/d8b2dadc-6bc0-40f7-8d1b-52096cd314db)

**Comment by Sivan22** [comment]
תוקן החל מגירסת המפתחים 0.1.8-dev.0

**Comment by chezfo** [comment]
התבטל, בעקבות גירסת המפתחים deb4
