### ISSUE TITLE
סגירה הניווט בעת לחיצה על תוכן הספר

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#114]
המצב בגירסא החדשה, שאם תפחת את ה"ניווט" הוא יושב על גבי הספר.
כמו כן הוא לא ייסגר עד לחיצה חוזרת על הלחצן, (או בגלילת הספר.)

מה שמקובל בתוכנות, שכאשר הניווט מסתיר את הספר, מספיק נגיעה בספר וה"ניווט" נסגר. (בניגוד למקרים אחרים שהניווט מזיז את הספר, ואז, צריך לסגור אותו ידנית.)

**Comment by Sivan22** [comment]
המצב חזר לקדמותו שהניווט "דוחף" את הספר.

**Comment by chezfo** [comment]
אמנם זה יותר טוב ממה שיש עכשיו. אבל היה שווה, להשאיר כמו עכשיו, ולהוסיף רק שבלחיצה על הטקסט הוא חוזר. (לא רק גלילה)
