### ISSUE TITLE
בעיה בספר משנה ברורה עם ביאור הלכה

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#115]
יש בעיה בספר משנה ברורה כשמסמנים לו בפרשנות שיציג את ספר ביאור הלכה הוא לא מציג כלום
כמו כן בתוכנה החדשה שמתחילים לכתוב משנה ברורה הוא נתקע לכמה שניות עד שהוא כותב את המילה בשלימות
תודה רבה

**Comment by Danthig** [comment]
> יש בעיה בעניין משנה ברורה כשמסמנים לו בפרשנות שיציג את ספר ביאור הלכה הוא לא מציג כלום כמו כן בתוכנה שמתחילים לכתוב משנה ברורה הוא נתקע לכמה שניות עד שהוא כותב את המילה בשלימות תודה רבה

א' ביאור הלכה הוא פירוש על השלחן ערוך, ולא על המשנ"ב. 
ב' האיתור בגרסה החדשה יותר איטי, ומשתמש ביותר משאבים. @Sivan22 שים לב שספרים בתחילת הא' ב' התוצאות מופיעות הרבה יותר מהר מאשר בסוף האלף בית!

**Comment by Bshlomecha** [comment]
> כמו כן בתוכנה החדשה שמתחילים לכתוב משנה ברורה הוא נתקע לכמה שניות עד שהוא כותב את המילה בשלימות

לכאורה הסיבה לכך כיוון שמתחיש לאתר ספר 'משנה' ואולי גם 'משנה תורה' (?), ורק אח"כ חוזר לזהות אותו כ'משנה ברורה'.
[]
כאמור, אינני מתכנת, אבל אולי אציע רעיון לעקוף בעיה זו: לקבוע שכאשר נרשם 'משנה' הוא ממתין עם האיתור הפרטי עד שתופענה אותיות נוספות 'בר' ל'ברורה' ותו' ל'תורה, וכיו"ב. [לא הצעתי באות אחד, כי עדיין תהיינה תוצאות רבות כמו 'משנה ברכות' ביצה בבא קמא וכו']
