### ISSUE TITLE
לחלק את הפרשנים לקטגוריות

### ISSUE THREAD

**Issue by dani860** [Sivan22/otzaria#117]
ההצעה שלי היא לחלק את הפרשני לפי קטגוריות - ראשונים, אחרוני, אחרוני בני זמנינו, ביאורים.
הסיבה היא שהיו כשאני רוצה ללמוד קטע בגמ' ולראות רק את הראשונים אני צריך לסמן מלא V
ואם יהיה קטגוריות אני יוכל לסמן על כל הראשונים, או על כל האחרונים ביחד
וכן שעכשיו הוא מביא עם הפרשנים גם ביאור שטינזלץ למשל, וזה משהוא שמפריע בסדר הלימוד הקלאסי.
וכן לסדר את הפרשנים לפי סדר לימוד
רשי
תוס
ריטבא
רשבא
וכו
תודה רבה
אליפות של תוכנה!!!!!!!!!!!!!!!!!1

**Comment by Bshlomecha** [comment]
ובדומה לזה הייתי מציע גם במפרשים על שו"ע וכד': מפרשים על הדף, מפרשים נוספים.

**Comment by YOSEFTT** [comment]
[פתרון זמני], ניתן למחוק את ביאור שטיינזלץ, וכן כל מה שמפריע לך

**Comment by Danthig** [comment]
לא מומלץ למחוק ספרים רק בגלל שהם מפריעים בכך שהם נמצאים בקטגוריית מפרשים!
באמת @Sivan22 אני חושב שההצעה של @dani860 - חלוקה לראשונים אחרונים ואחרוני זמנינו בבחירת פרשנות היא נכונה ומאוד מועילה.
