### ISSUE TITLE
העלאה לחנות google play

### ISSUE THREAD

**Issue by zeeira** [Sivan22/otzaria#119]
תודה רבה על היוזמה הנפלאה, תודה ליוזם, תודה לכל השותפים.
מאז שנחסם ספריא בנטפרי לא מצאתי נחמה

לצערי העצום אני לא יכול עדיין להנות מהפרוייקט, ואפי’ לא זכיתי להציץ במה מדובר
כי ב”ה יש לי ווייפרי על הטאבלט
וכדי שיוכלו להעלות את זה לחנות של ווייפרי מבחינה טכנית אי אפשר אם זה לא נמצא בגוגל פליי

אין לי שום הבנה בתחום, ואין לי מושג איך עושים את זה ומה נדרש לזה
אנא קחו לתשומת לבכם
ואם אפשר תעשו את זה

ואכפול תודה

נ. ב. נטפרי גם רוצים לקבל מידע אודות הסינון שעשיתם מספריא, אבל זה ענין נפרד

**Comment by Sivan22** [comment]
אם נטפרי יאשרו את התוכנה יש להם אפשרות לאשר התקנה למשתמש מסויים, לפי מספר
מנוי, גם ללא העלאה לגוגל פליי. כרגע התוכנה לא תוכל לעלות לגוגל פליי לצערי.

בתאריך יום ד׳, 22 במאי 2024, 20:47, מאת zeeira ***@***.***>:
