### ISSUE TITLE
כמה הערות בעיצוב התוכנה ותפקודה

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#121]
א. **הכותרת בסימני השו"ע** ממוספרת בטעות בתור סעיף (א).
צריך להפריד את הכותרת להיות עליונה ולסמן את הכתוב בגוף הספר באות (א)

ב. האם אפשר ש**תוצאות החיפוש** יהיו מסודרות לפי חטיבות הספרים, או הנושאים, או חלוקה כרונולוגית?

[אם ניחא ליה - אכתוב עוד הערות עם המשך ההרגל והשימוש].

**Comment by YOSEFTT** [comment]
בקשר לאות ג', החיפוש כולו אמור להשתנות בגירסא 2.0, ועד אז סיוון לא מתכנן לגעת בזה.

**Comment by YOSEFTT** [comment]
דרך אגב, ניחא לי' מאוד בהערות, הרי בשביל מה הוא עשה את התוכנה? בשביל שתהי' תוכנה מוצלחת והמשתמשים בה יאהבו אותה ויהי' להם נח איתה, עם הממשק והעיצוב והמהירות, וכל מה שיש לתוכנה להציע.

ועוד דבר דרך אגב, אם יש לך ספרים נוספים להשיג לנו, נשמח מאוד מאוד, וזכות הרבים תהי' תלוי' בך לדורי דורות.

**Comment by Sivan22** [comment]
תיקנתי גם את א, ויופץ בגרסאות הבאות בעזרת ה'.
