### ISSUE TITLE
ספר עשרה פרקים לרמח"ל

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#122]
אני חוזר על הערה והצעה ישנה, איני יודע מה עלה בגורלה.

**ספר עשרה פרקים** של רבנו הרמח"ל זללה"ה [הנקרא גם **'כללות האילן הקדוש'**] הובא ממאגר שנטל ממאגר שנטל כו' [וכבר היה ב'תורת אמת', ואולי עוד קודם לו] והוא נוסח משובש של מעתיק שלא למד את הדברים אלא כתב אותם בלשונו.

ברשותנו נוסח מתוקן ומוגה, וגם מהודר בפיסקאות וכותרות, בניקוד מלא. 
קיבלנו את רשותו של המהדיר ר' שמואל ווייס שליט"א מהעיר העתיקה, להעלותו לתועלת הציבור העוסק בתוה"ק. 
לע"ד היה ראוי להחליף את הקובץ הישן. עכ"פ ודאי להביא את החדש, כמו שעשו ב'אוצר הספרים היהודי השיתופי'  https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%A2%D7%A9%D7%A8%D7%94_%D7%A4%D7%A8%D7%A7%D7%99%D7%9D.

הנני מעתיק מה שנשלח בעבר במייל, ויישר כח לה"ה Y-PLONY  notifications@github.com שעזר בזה, וכתב:

תייגתי את הקובץ המתוקן שהרב [@Bshlomecha](https://github.com/Bshlomecha) הביא, לאוצריא, [@Sivan22](https://github.com/Sivan22) חשוב שתחליפו במאגר.
[עשרה פרקים לרמחל מוגה.TXT](https://github.com/Sivan22/otzaria/files/14906044/default.TXT)
(מעניין שגיטהב אינם תומכים בקובץ ללא סיומת).

—

**Comment by Danthig** [comment]
אין טעם לפתוח על זה שוב פעם נושא, זה כבר מוזכר כאן https://github.com/Sivan22/otzaria/issues/32.

@Sivan22 זה באמת חשוב!!!

**Comment by Bshlomecha** [comment]
תודָה.

מודֶה.

‫בתאריך יום ה׳, 23 במאי 2024 ב-17:30 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Bshlomecha** [comment]
בס"ד

ר' סיוון נ"י השלו' והברכה,
ברשותי נגן אולטרה פלוס, מנותק מקישור לרשת, למעשה הוא חסום בפני התקנת
אפליקציות חיצוניות [ולצערי אין אפשרות אפילו למחוק משחקים מובנים].
[בנסיון להתקנת אפליקצי' כל שהיא מתקבלת הודעת שגיאה 'לצרכי אבטחה אין אפשרות
להתקין אפליקציות ממקור בלתי ידוע'].
האם באיזו שהיא דרך יש אפשרות שהאפליקציה שלך תהיה מורכבת עם אישור המאפשר
להתקינה? [ראיתי שאתה מתעסק גם בנושאים לאישורי אבטחה כאלה וע"כ מצאתי מקום
לשאול]

בברכה"ת.

אלו הפרטים שכתבתי בהתכתבות ישנה:
ברשותי נגן אולטרה פלוס כשר. לא הגירסא עם המסך הגדול [שבאמת נראה כמו
כסילופון], אלא  גירסא קומפקטית, בסגנון כזה
נגן MP3 אולטרה אס GAMESTAR ULTRA S + מצלמה . - GAMESTAR
(merkaz-electronica-sheonim.co.il)
<https://www.merkaz-electronica-sheonim.co.il/items/5631022-%D7%A0%D7%92%D7%9F-MP3-%D7%90%D7%95%D7%9C%D7%98%D7%A8%D7%94-%D7%90%D7%A1-GAMESTAR-ULTRA-S-%D7%9E%D7%A6%D7%9C%D7%9E%D7%94->
לפי מה שבררתי [אצל העוסקים בתחום] - את אולטרה סטאר פלוס בדקו טובי הטכנאים,
ואמרו לי שלא הצליחו לחברו לרשת.
וטוב שכך.
בכל אופן ישנה אפשרות לפתיחת קבצי הקודים שלו CSV files  [אני איני מתכנת
ואינני יודע איך לעבוד אתם].

אני רוצה למחוק את המשחקים [אע"פ שהם כשרים..], ובעיקר אני מעוניין להתקין
אפליקציות רבות שימושיות [תורניות ומעשיות].
מלבד זאת הוורד מציג לי את כל העברית הפוכה.

**Comment by Danthig** [comment]
המקום לבקשות כעין זה, הוא [למשל כאן](https://mitmachim.top/category/66/%D7%9B%D7%9C%D7%9C%D7%99-%D7%A2%D7%96%D7%A8%D7%94-%D7%94%D7%93%D7%93%D7%99%D7%AA).
אין לבעיה עם הנגן שום קשר לאפליקציה...

**Comment by Sivan22** [comment]
קיבלתי את הנוסח המעודכן של הספר "עשרה פרקים", תודה רבה.

**Comment by Bshlomecha** [comment]
יישר כח על העדכון.
חילך לאורייתא ולהעשרת אוצריא דילה באוצרות הקודש למלאם פנינים ומטמונים
ולהאיר פנים בלבבות נכונים.

‫בתאריך יום ג׳, 28 במאי 2024 ב-6:39 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Bshlomecha** [comment]
תודה. זו לו היתה חלילה וחס ביקורת על האפליקציה.
זו היתה [אולי בעזות פנים] בקשה פרטית, כיוון שבאופן כללי לא רוצים לסייע
בפריצת ההגנות של המכשיר הזה [ובצדק רב!],
רק שסברתי [לתומי] שאתה - בתור מפתח האפליקציה, שגם מבין בתעודות אבטחה - אולי
תוכל להחריג את האפילקציה ולהגדירה כך שהמכשיר יזהה אותה כטובה וראויה ובלתי
מסוכנת...
כאמור, זו משאלת לב שלי, וכנראה סביר יותר שהיא חלום באספמיא...

סליחה על ההטרדה, ותודה על כל ההשקעה להגדיל תורה


‫בתאריך יום ב׳, 27 במאי 2024 ב-13:36 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬
