### ISSUE TITLE
תפריט הניווט בספר מכסה את הטקסט  של הספר עצמו

### ISSUE THREAD

**Issue by HeroldGr** [Sivan22/otzaria#123]
בגירסה 0.1.6, בפתיחת תפריט הצד של הניווט פרשנות וכו' הטקסט של הספר עצמו היה זז הצידה וכך היה אפשר לראות את כל הטקסט בשעה שתפריט הצד פתוח. כעת בגירסה החדשה תפריט הצד מכסה את הטקסט.

**Comment by Sivan22** [comment]
יתוקן בגרסאות הבאות אי"ה.

‫בתאריך יום ו׳, 24 במאי 2024 ב-17:53 מאת ‪HeroldGr‬‏ <‪
***@***.***‬‏>:‬

**Comment by AshiVered** [comment]
אולי שפשוט יוצג באופן קבוע בצד המסך, ולא יסתיר (ואם מציגים פרשנים בצד, אז הוא יסגר)?

**Comment by Y-PLONI** [comment]
כפול?
https://github.com/Sivan22/otzaria/issues/124
