### ISSUE TITLE
תפריט הצד של הניווט והפרשנות וכו' בספר לא נסגר בהקשה על על הטקסט אלא רק ע"י גלילה

### ISSUE THREAD

**Issue by HeroldGr** [Sivan22/otzaria#124]
בהקשה על הטקסט של הספר עצמו תפריט הצד לא נסגר אלא רק עם הגלילה (כמדומני שבגירסה הקודמת 0.1.6 עבד תקין)
https://github.com/Sivan22/otzaria/assets/103885041/33a8a243-b17c-4380-875d-b3ca9ed4c20d

**Comment by Y-PLONI** [comment]
כפול?
https://github.com/Sivan22/otzaria/issues/123
