### ISSUE TITLE
ג'יבריש בהעתקת טקסט מקבצי PDF

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#125]
## תיאור הבאג
כשאני מעתיק טקסט נבחר מקובץ pdf, אני מקבל ג'יבריש
![image](https://github.com/Sivan22/otzaria/assets/76535872/0c37c2c3-6d9b-4115-a9c0-c20e8200fa72)
והתוצאה...
![image](https://github.com/Sivan22/otzaria/assets/76535872/737e01aa-4737-46e0-b5d5-17443bf170ec)

### מערכת
 - OS: [Windows 10 22H2 English]
 - Otzaria 0.1.7
- Office 2013 Standard

**Comment by Sivan22** [comment]
הבעיה היא בקובץ הPDF, לא בתוכנה.
