### ISSUE TITLE
חוסר בדיבורים המתחילים בריטב"א קידושין

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#127]
כמו שאפשר לראות בתמונה,
בריטב"א חסרים הדיבורים המתחילים הממסופרים כ ג ו ד
(מיד אחרי ב מגיע ה)
![image](https://github.com/Sivan22/otzaria/assets/76535872/42a98e54-c042-4002-bb34-c6d4496ce6f4)
הדיבורים האלו מופיעים בספריא
![image](https://github.com/Sivan22/otzaria/assets/76535872/1fe58d1e-6d53-4579-9473-b4afcdfc4620)
זה לא פעם ראשונה - נתקלתי בעוד מקום, לא זוכר איפה, בדילוג על דיבורים מתחילים (לפי המספור ראיתי שיש דילוג).
אבל חשבתי שזה שגיאה במספור או משהו כזה, כי לא הייתי צריך אחד מהדיבורים החסרים.
פה במקרה הייתי צריך אחד מהם וידעתי שיש אותו, כי באוצר החוכמה יש אותו.
אז בדקתי.
איכשהו בהמרה מספריא לאוצריא זה נשמט...
תודה ויש"כ.

**Comment by AshiVered** [comment]
> זה לא פעם ראשונה - נתקלתי בעוד מקום, לא זוכר איפה, בדילוג על דיבורים מתחילים (לפי המספור ראיתי שיש דילוג).

רשב"א שם בדיבור המתחיל שממסופר כ ב'.
לא קיים באוצריא, קיים בספריא.
כנראה יש איזו בעיה בסקריפט ההמרה...

**Comment by Sivan22** [comment]
גם באוצריא יש אותו, זה חוסר רק בקישורים, וכנראה קיים גם במקור.
![image](https://github.com/Sivan22/otzaria/assets/89018301/9f4fc6a9-cb5a-47c9-a05d-0faf06b5e653)

**Comment by Sivan22** [comment]
לגבי הרשב"א, ייתכן והוא נוסף בחודשים האחרונים מאז העדכון האחרון.

**Comment by AshiVered** [comment]
מעניין, אני פתחתי את הספרים בנפרד ואיכשהו ברח לי מהעין.
מחילה.
אולי אפשר לעשות שתצוגת הפרשנים בצד תפתח את כל הריטב"א, ולא רק את המקושר?

**Comment by AshiVered** [comment]
> וכיצד התוכנה תדע להציג לך את המסכת + דף?
אם ע"פ הקישור, יש פרשנות על הדף הזה, אז להציג את כל הפרשנות מהדף הזה, ולא רק מה שמקושר לדיבורים מתחילים מסויימים
