### ISSUE TITLE
איפה נרשמים לקבלת גירסת מפתחים??

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#131]
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

**Comment by Sivan22** [comment]
ניתן להוריד גירסאות מפתחים מכאן:
https://github.com/Sivan22/otzaria-dev-channel/releases

בתאריך יום א׳, 2 ביוני 2024, 13:47, מאת Refael11 ***@***.***

**Comment by Danthig** [comment]
![image](https://github.com/Sivan22/otzaria/assets/161762042/a242dfc7-7d58-46d2-b56e-bdbce6e86b94)
מתוך גירסה 0.1.7+6
https://github.com/Sivan22/otzaria-dev-channel/releases/tag/0.1.7%2B6
