### ISSUE TITLE
אי אפשר להעתיק

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#132]
ברוב הפעמים שאני מנסה להעתיק טקסט, אחרי שסיימתי לסמן, אני לוחץ קליק ימני כדי להעתיק והסימון נעלם, כך שלא מועתק שום דבר.
פעמים בודדות זה כן עובבד, לא הצלחתי למצוא חוקיות.
תודה רבה

https://github.com/Sivan22/otzaria/assets/76535872/db3c15d7-ebe2-4a3b-8b7f-52c9dc1d6c46

### Environment
 - OS: [WIn 10 Pro 22H2]

**Comment by mosh-dvd** [comment]
בגרסה הבאה יהיה אפשרות לבחור להוציא לטקסט או PDF וגם לבחור כמות מה שיפטור את הבעייה

**Comment by AshiVered** [comment]
איך זה יפתור?

**Comment by mosh-dvd** [comment]
יהיה שם אפשרות להדפיס לטקסט לפי כמות קטעים

**Comment by AshiVered** [comment]
זה הרבה פחות נוח מהעתקה

**Comment by Sivan22** [comment]
ממה שבדקתי, אם לוחצים לחיצה ימנית על הטקסט המודגש עצמו, זה מעתיק, אם לוחצים במקום אחר זה מבטל את ההדגשה ולא מעתיק.

**Comment by Y-PLONI** [comment]
אם כן, ניתן לסגור, לא? @Sivan22 ? @AshiVered

**Comment by AshiVered** [comment]
> ממה שבדקתי, אם לוחצים לחיצה ימנית על הטקסט המודגש עצמו, זה מעתיק, אם לוחצים במקום אחר זה מבטל את ההדגשה ולא מעתיק.

תראה בסרטון, לא
