### ISSUE TITLE
 בעייה בשמירת מיקום הקבצים 

### ISSUE THREAD

**Issue by mosh-dvd** [Sivan22/otzaria#133]
משום מה ב PDF הוא לפעמיים לא שומר מיקום אלא חוזר לתחילת הספר 
(לא הצלחתי לעלות מתי הוא שומר ומתי לא)

**Comment by Y-PLONI** [comment]
עדיין קיים, @mosh-dvd ?

**Comment by mosh-dvd** [comment]
כנראה שלא
