### ISSUE TITLE
ספר כף החיים אורח חיים

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#135]
מה קורה עם כף החיים על אורח חיים?
במהדורות הקודמות היה קיים ועכשיו אינו קיים. [אמנם הוא קיים בתיקיית הלינקים אך הספר עצמו לא קיים].
ניסיתי להוסיף אותו ידנית מהמדורה הקודמת אך התוכנה לא מזהה אותו
תודה רבה ויישר כח עצום!

**Comment by Sivan22** [comment]
נשמט מתקלה טכנית, אמור לעבוד מגרסה קודמת, צריך לוודא שיש לו סיומת txt


בתאריך יום א׳, 9 ביוני 2024, 19:22, מאת cc054848484 ‏<
***@***.***>:

**Comment by cc054848484** [comment]
זה אכן עובד בקובץ טקסט. אבל זה מציג בניווט את כל הסעיפים הקטנים שבכל סימן כשהם פתוחים וכך קשה לנווט בקלות. 
מצ"ב צילום מסך:
![צילום מסך 2024-08-13 221630](https://github.com/user-attachments/assets/96518f37-8f27-4872-8185-678e1e0bba96)
