### ISSUE TITLE
בחיפוש בPDF שנוספו למאגר, הוא אכן מחפש ומוצא את העמוד אך לא את המיקום המדויק של של מילות החיפוש.

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#136]
בחיפוש בPDF שנוספו למאגר, הוא אכן מחפש ומוצא את העמוד אך לא את המיקום המדויק של של מילות החיפוש.

_Originally posted by @SBW88 in https://github.com/Sivan22/otzaria/issues/10#issuecomment-2041219998_

**Comment by shimonshe** [comment]
יתכן שקשור לשכבת OCR שלא נמצאת במיקום המדויק של הטקסט ולכן זה נראה כך,
בעיה כעין זו נמצאת הרבה גם באוצר החכמה.

**Comment by Y-PLONI** [comment]
צריך לבדוק האם הבעיה אמיתית או לא, אם כן, אולי יעזור להשתמש במציג PDF זה:
https://pub.dev/packages/flutter_pdfium

**Comment by Sivan22** [comment]
לא הצלחתי לשחזר את הבעיה, הוא מוצא בהחלט את המיקום המדוייק של מילות החיפוש.

בתאריך יום ב׳, 12 באוג׳ 2024, 17:32, מאת Y-PLONI ***@***.***
