### ISSUE TITLE
שאלה | תחת איזה רשיון מנחת חינוך, ורמב"ן על התורה?

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#137]
רציתי לברר תחת איזה רשיון הספרים כאן מתפרסמים.
כעת מה שהמעניין אותי זה מנחת חינוך ורמבן על התורה, אך השאלה הזו היא על הרבה ספרים.
כללו של דבר: איך אני יכול לדעת כל טקסט מה המקור שלו, והרשיון שתחתיו הוא מפורסם.
תודה רבה.

**Comment by Y-PLONI** [comment]
כמעט כל הספרים שהתפרסמו הם מספרייא, עיי"ש.

**Comment by chezfo** [comment]
האם לא כדאי / מומלץ / נדרש, לציין על כל ספר תחת איזה רשיון הוא ומה מקורו?

**Comment by Y-PLONI** [comment]
מהידוע לי, ספרייא רק מבקשים או מחייבים [כבר לא זוכר, חפש בגיט] לשים סמל כמו מה שסיון שם בתוכנה.

**Comment by chezfo** [comment]
הכוונה שלי, שכדאי לכתוב בכל ספר מה המקור שלו והרשיון, בכדי שיהיה מידע עתידי על זכויות יוצרים.
זה ענין פשוט של צורה ארגונית. ותועלת הציבור.

**Comment by Sivan22** [comment]
זה בהחלט בתכנית, רק שזה לא מופיע בצורה נוחה במסד הנתונים שלהם.

‫בתאריך שבת, 15 ביוני 2024 ב-23:10 מאת ‪noty‬‏ ***@***.***
‬‏>:‬

**Comment by Y-PLONI** [comment]
כוונתך, למקרה שיתווספו ספרים?

**Comment by Sivan22** [comment]
ובנוגע לשאלה: רמב"ן על התורה המקורות הם:
https://www.sefaria.org/Ramban_on_Genesis
-http://mobile.tora.ws/

‫בתאריך שבת, 15 ביוני 2024 ב-23:12 מאת סיון רצון ***@***.***
‬‏>:‬

**Comment by chezfo** [comment]
כן.
וכפי הידוע לי ישנם כמה ספרים ממקורות אחרים. 
כמו כן, יש בספריא כמה סוגי רשיונות, כמו נחלת הכלל, או ללא תועלת מסחרית, ועוד רבים.

**Comment by Sivan22** [comment]
מנחת חינוך המקור הוא ספריא, נחלת הכלל.

‫בתאריך שבת, 15 ביוני 2024 ב-23:14 מאת ‪noty‬‏ ***@***.***
‬‏>:‬

**Comment by chezfo** [comment]
תודה רבה.
בנוגע לרמב"ן על התורה, חסום לי. אשמח למידע מקוצר.
ושוב תודה על העזרה הספיציפית בתוך כל ההשקעה המרובה!!
