### ISSUE TITLE
בפרשנים טו מגיע לאחר ט

### ISSUE THREAD

**Issue by Sivan22** [Sivan22/otzaria#140]
## Describe the bug
המיון הוא לפי א-ב ולכן טו מגיע אחרי ט ולא אחרי יד.

**Comment by Y-PLONI** [comment]
נראה כי @mendelg נתקל בבעיות מיון אלף-בית עברי, כאן:
https://stackoverflow.com/questions/74539877/how-can-i-sort-a-list-alphabetically-based-on-the-hebrew-language-in-dart
