### ISSUE TITLE
Add zmanim

### ISSUE THREAD

**Issue by mendelg** [Sivan22/otzaria#144]
<img width="733" alt="image" src="https://github.com/Sivan22/otzaria/assets/68921220/0957a80a-7e15-4509-abd4-cb5241b25cb0">

Add Zmanim functionality to the Otzaria app. 

This feature will display daily Zmanim based on the user's location and provide important times for Jewish prayers and rituals.

Bonus:
Add the daf yomi/daily Chitas

**Comment by mendelg** [comment]
If this is something that you would consider, I wouldn't mind making a PR.

**Comment by Sivan22** [comment]
I will be happy to any contribution! About the zmanim, in my opinion the
daf yomi option could be very useful. The daily Zmanim are maybe little out
of the app's scope.

בתאריך יום ב׳, 8 ביולי 2024, 03:52, מאת mendelg ***@***.***>:

**Comment by Danthig** [comment]
זמני היום יכולים להוסיף הרבה לתוכנה, כדוגמת פרשת שבוע, הדף היומי, משנה יומית, הלכה יומית, וכו'. 
כאשר זה מוגדר בתוכנה כקישור לטקסט - למשל בלחיצה על פרשת חוקת יפתח פרשת חוקת. 
אבל לכאורה זה יהיה שייך רק אחרי גרסת 0.2.

**Comment by mendelg** [comment]
@Danthig 

כן בדיוק על זה חשבתי,

יש את 
https://pub.dev/packages/kosher_dart
במיוחד ל dart/flutter
