### ISSUE TITLE
הצעות לייעול ההתמצאות והניווט

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#145]
שוב ושוב תודה וברכת הצלחה.
ארשום תיקונים שיכולים להועיל לענ"ד [חיפשתי בנושאים הקודמים והסגורים ולא מצאתי שדברו בהם, אם כי בזכרוני שהיו כאלה שעלו לדיון, וכמדומה שעדיין לא סודרו עצהיו"ט]

א. ב'עיון' - **פתיחת הספרים על פי ציון מקורות מדוייקים**, כגון 'ברכות ג, א', 'יהל אור בראשית ג'.
ב. כמו כן בניווט בספר פתוח - לפתוח **חלונית הפנייה** שאפשר לעבור מידיית למיקום מסויים, בלי לגלול את כל אילן הכותרות [כמו באוהצ"ח במהדו' החדשות].
ג. **לחצן חזרה שלב אחורה**, בענף הספרים וכד', ולחצן נפרד לחזור לעמוד הראשי.
ד. אפשרות קביעת ברירת מחדל למאגרים המשתתפים בחיפוש [נפ"מ גדולה למי שהוסיף ספרים ואינו רוצה בכל פעם להכביד על החיפוש בכל אוצרותיו].
ה. **זיהוי שמות ספרים** גם בהגדרה לא מדוייקת 'רמחל' 'רמח''ל' 'רמח"ל' [שני גרשים או גרשיים], וגם 'הרמח"ל' [זה דורש מילון רחב, כי ישנם ספרים שישנן דרכים רבות לכתוב את שמם, שו"ע שלחן ערוך שולחן ערוך, רמב"ם משנה תורה, פיה"מ פי' המשנה פירוש המשניות, וכן על זו הדרך. ומצד שני לא כדאי שיעלו סתם דברים שאינם סבירים, כמו 'או"ח שי', יעלה רק מה ששייך לאורח חיים סי' שי, ולא אור החיים הק', ולא ארחות חיים, ולא ערך שי, וכיו"ב].
ו. הלוואי - זיהוי **מקורות המובאים בספרים** בתור **קישורים** לספרים האמיתיים [אפילו אוצה"ח עד שלב מסויים לא הצליחו לייצב את זה בצורה מדוייקת. כמדו' שב'שיתופתא' יש איזו שהיא רמה של קישוריות כזו. האם הם מבוססים על הקישורים של ספריא?].
ז. עיון בספרים סביב מקור מסויים, כגון ברכות ג, א יצא כל הספרים על אתר [זה אמנם אפשרי על ידי פתיחת הדף בגמרא ואז כל המפרשים]. אמנם במידה ויתפתח האמור באות ו' - יוכל להיות כמו 'קשרים' בפרוייקט השו"ת, שיפתח כל מי שהזכיר את הציון המדובר.

עוד חזון למועד . יישר כח.

**Comment by Bshlomecha** [comment]
הערה ג - הענין אמנם תוקן בעבר, ביחס לניווט כאשר עדיין אוחזים באילן הספרים, אבל לאחר פתיחת ספר מסויים - המערכת מתאפסת. ולמעשה כדי גם אז שתהיה אפשרות לחזור שלב אחורה. כיוון שמצוי מאוד שהלומד פותח ספר ומגלה שהוא צריך ספר מקביל או כרך לפניו או לאחריו וכיו"ב.

**Comment by Sivan22** [comment]
הערות נכונות מאד. אני מעט עסוק בתקופה הקרובה, אבל בעז''ה כשאתפנה אלו הדברים
הראשונים לשפר. (וכמובן החיפוש המיוחל).

בתאריך יום ד׳, 10 ביולי 2024, 15:30, מאת Bshlomecha ‏<
***@***.***>:

**Comment by Bshlomecha** [comment]
בהצלחה, בכל הטוב, הפרטי והכללי.

‫בתאריך יום ד׳, 10 ביולי 2024 ב-16:47 מאת ‪Sivan Ratson‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
הערה א - חשוב מאד, מתוכנן לגרסה 0.2
 , הערה ב- דבר דומה יהיה  כבר בגרסה הבאה: איתור סימניה בסרגל ניווט כזה: ![Image](https://github.com/user-attachments/assets/75b973d8-9b93-4df8-8ea6-9d42227255b5)
לגבי המוזכר באות ג - בגרסה הבאה הספריה תישאר איפה שהייתה, ורק בלחיצה על לחצן הבית היא תתאפס
הערה ה -  יש תשתית מיוחדת לזה במאגר של ספריא, ואפשר ליישם את זה. בעזרת ה' מקווה שיחד עם הערה א בהגיע עתו וזמנו.
אות ו זה לא בתכנון שלי, אבל ספריא מתקדמים עם זה כל הזמן.
לגבי המוזכר באות ז זה כבר קיים בלשונית הצד->קישורים
