### ISSUE TITLE
Progressive scrolling with arrows

### ISSUE THREAD

**Issue by Sivan22** [Sivan22/otzaria#152]
## Summary
make the scrolling with keys easier and faster by increasing the speed over time of holding the key down.

**Comment by Bshlomecha** [comment]
אפשר גם להוסיף [בדומה למה שקיים בגלילה של וורד ובאופן דומה גם באוצר החכמה] שבמשך הגלילה כאשר הסמן נמצא על פס הגלילה לארכו ישנו סימון היכן הוא אוחז לאורך הספר, לפי הכותרות הראשיות והמשניות.

כל זה מלבד מה שהצעתי בזמנו שב'ניווט' תהיה אפשרות לדלג מיד לכותרת או 'מראה מקום' בהמשך הספר, כגון כאשר פותחים תהלים - יהיה אפשר לכתוב 'קלב', או כאשר פותחים שו"ע או"ח יהיה אפשר לכתוב 'סימן קכח סעיף יב', או בקיצור 'קכח, יב' [גם זה כמו שיש באוצר החכמה]. 

ושוב ושוב תודה רבה על ההשקעה בתוכנה הנפלאה.

**Comment by Sivan22** [comment]
נוספה האפשרות לגלילה פרוגרסיבית (במהירות גדלה והולכת) באמצעות חיצים.
