### ISSUE TITLE
לחיצה על הטקסט לא מעלימה את חלונית הניווט

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#154]
## החלונית אינה נכנסת חזרה
כיום המצב שרק בעת גלילה החלונית של הניווט חוזרת למקומה.
זה מעט מתסכל...

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/issues/153

**Comment by Sivan22** [comment]
duplicated #124
