### ISSUE TITLE
למקם את הסמן בשורת החיפוש בעת כניסה ל"ספריה".

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#155]
## מיקום הסמן באופן אוטומטי.
כיום המצב שכאשר לוחצים על "ספריה" ונפתח ספריית אוצרייה, צריך להעמיד את הסמן על שורת החיפוש בכדי לחפש. הדבר מיותר. וסתם מסבך את העניין

**Comment by natireed** [comment]
אם פותחים בCONTROL O זה כן עובד וצ"ע ההבדל
