### ISSUE TITLE
תצוגת שם מחבר

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#156]
בגרסת המפתחים האחרונה, התווסף לספרים שבאוצר החכמה גם שם מחבר - דבר שמאוד מאוד תועלתי, ויהיה תועלת גדולה שיהיה גם בספרי הבסיס שבתוכנה.

אגב, לגבי גודל הגופן, לדעתי כדאי שיהיה בגודל של ספרי הבסיס שבתוכנה (שם הספר, ושם מחבר בגודל של מיקום הספר):
![צילום מסך 2024-07-30 094214](https://github.com/user-attachments/assets/3c286451-6da7-4db4-aa6c-0dd836944efa)

**Comment by Y-PLONI** [comment]
תייג את @mendelg

**Comment by Sivan22** [comment]
שם המחבר מופיע בכל הספרים שקיים המידע הזה. 
![image](https://github.com/user-attachments/assets/a33b287d-949a-440c-823b-7325c048a44e)

כמו כן בגרסאות החדשות, המראה אחיד לכלל הספרים.
