### ISSUE TITLE
חזון מרחיק לכת - התאמת מקורות בזיהוי מפותח

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#164]
{אולי רעיון גדול מדיי. אולי טרם הגיע זמנו, אבל יונח לפניכם:}

האם אפשר להתאים מערכת (בינה מלאכותית) שתזהה **התאמה של מקורות**, 
כגון במקומות רבים שישנם מאמרי חז"ל מקבילים (בגמ' מינה ובה, בין בבלי וירושלמי, ווודאי במדרשים), 
וכן מצוי רבות בספרי הראשונים שמעתיקים השמועה מדור לדור.
ולמען האמת אפילו במקרא הרי ישנם פרקים מקבילים כמו שירת דו[י]ד. [ב'על התורה' יש מערכת מורכבת ומשוכללת. אני מדבר על דבר בסיסי הרבה יותר].

= התועלת כמובן יכולה בכמה כיוונים:
א. בהבאת המקורות וקיבוצם בצורה מסודרת.
ב. בהשוואת הכתוב בהם השווה והשונה.

כמובן שיש בזה שאלה לא מבוטלת, כמו כלים רבים כגון אלו, שמאפשרים לעמי ארצות להרגיש כאילו... או להציג כאילו...
אבל נשאלה נא לחכמים ויורונו, אולי גם בזה - ישרים דרכי ה' צדיקים ילכו בם....

**Comment by Sivan22** [comment]
זה בינתיים חורג מהתחום שהתוכנה מתמקדת בו, אבל יש כלים טובים כאלו במקומות אחרים, לדוגמה של דיקטה כאן: https://parallels.dicta.org.il/
