### ISSUE TITLE
חיפוש במאגרים

### ISSUE THREAD

**Issue by e0527687459** [Sivan22/otzaria#167]
מאז העידכון לחפש בהיברו בוקס זה לא מחפש אפי' באוצריא אלא מסתובב ומסתובב
כשהיה חיפוש רק באוצריא ואוצר הכחמה עבד יפה מאד

**Comment by Y-PLONI** [comment]
הבעיה מוכרת, ונמצאת רק בMSIX, ולא בEXE [בתוכנה הניידת].
מנסים למצוא פתרונות.

**Comment by Y-PLONI** [comment]
אגב, היית צריך לפתוח את הבאג בגיט של המפתחים, לא נורא.

**Comment by e0527687459** [comment]
סליחה פעם ראשונה שהשארתי תגובה ולא בדקתי מספיק
בכל אופן תודה

‫בתאריך יום ה׳, 8 באוג׳ 2024 ב-1:18 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
לא נורא... לא קרה שום דבר...

**Comment by Bshlomecha** [comment]
> הבעיה מוכרת, ונמצאת רק בMSIX, ולא בEXE [בתוכנה הניידת].
> מנסים למצוא פתרונות.

לפי הנראה - העדכון האחרון 1.8-3 מופיע _'רק בMSIX, ולא בEXE'_ ...
[ולמרות שבהפעלת התוכנה הניידת כתוב בפינה הימינית למטה 'עדכון זמין', ואח"כ 'מוריד' ואח"כ 'מוכן להתקנה' - הלחיצה עליו אינה מעדכנת את התוכנה].

ובכל זאת אתה ודאי צודק 
> לא נורא... לא קרה שום דבר...


בשורות טובות ישועות ונחומים, לעם אחד ומיוחד בין העמים.

**Comment by Y-PLONI** [comment]
> לפי הנראה - העדכון האחרון 1.8-3 מופיע _'רק בMSIX, ולא בEXE'_ ...

צודק, מתנצל...
הנה:
https://w1714935846-k2n297264.slack.com/files/U07BBUJ2C21/F07F5AJ4JKZ/dev__2.zip
זה דב 2, לא 3. לא זוכר אם את 3 הוציאו נייד.

**Comment by Bshlomecha** [comment]
תודה.
אני כשלעצמי עדכנתי גם ל-3 *בMSIX , רק הערתי על כך שבניידת אין 3 והוא עושה
'כאילו' הוא מעדכן...*

*[אגב - אשמח אם תסביר לי מה המעלות של כל אחת מהאופציות, לאחר שאני רואה שגם
הניידת מזהה את כל הקבצים שנמצאים במהדורה הראשית]*



‫בתאריך יום ה׳, 8 באוג׳ 2024 ב-14:41 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
הבאג תוקן בגרסה האחרונה.
