### ISSUE TITLE
החלפת סמל לאפליקציה באנדרואיד מכיוון שקשה לראות אותו ברקע שחור

### ISSUE THREAD

**Issue by nirmitlamed** [Sivan22/otzaria#174]
בקצרה, לטלפון שלי יש רקע שחור ומכיוון שהצבעים של הסמל של האפליקציה הם בעיקר צבעים כהים אז מאוד קשה לראות אותו על רקע שחור.
העלתי תמונה להמחשה.
![Screenshot_20240814_191704_One UI Home](https://github.com/user-attachments/assets/3eab4a60-9a6a-4f76-899d-1a6400529ff5)

**Comment by Y-PLONI** [comment]
גם בווינ' 10 קשה לראות את הסמל בשורת המשימות, כיון שהיא שחורה כברירת מחדל.

**Comment by Sivan22** [comment]
כבר תוקן לקראת הגרסאות הבאות.

בתאריך יום ד׳, 14 באוג׳ 2024, 20:07, מאת Y-PLONI ***@***.***
