### ISSUE TITLE
גרירת כרטיסיות לא פעיל

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#178]
בגירסה זו 0.1.8-beta האחרונה
באג- גרירת כרטיסיות עדיין לא עובדת.

**Comment by Y-PLONI** [comment]
היה פעם? כלומר, זה באג או שלא היה אף פעם, ואז אתה בעצם מבקש תכונה חדשה?

**Comment by IEUDI** [comment]
אכן פעם זה היה וזה התבטל.

**Comment by Sivan22** [comment]
זה היה באג והוא תוקן.

בתאריך שבת, 17 באוג׳ 2024, 23:00, מאת IEUDI ***@***.***>:
