### ISSUE TITLE
חלוקת הפרשנים לקטגוריות

### ISSUE THREAD

**Issue by Tanachy** [Sivan22/otzaria#18]
בבחירת פרשנים להוסיף חלוקה לראשונים ואחרונים שיהיה אפשר לבחור את כל הראשונים או כל האחרונים ביחד.
תודה רבה על המיזם המיוחד, כל המזכה את הרבים זכות הרבים תלוי בו!

**Comment by Y-PLONI** [comment]
הנידון שם שונה, אך קרוב.

**Comment by Tanachy** [comment]
> הנידון שם שונה, אך קרוב.

הכוונה שלי לא היתה בשביל סדר אלא שמי שרוצה לדוגמא לסמן רק את הראשונים לא יצטרך לסמן אחד אחד אלא את כולם ביחד

**Comment by Y-PLONI** [comment]
ככה"נ יסודר בע"ה הגרסה 0.2!
