### ISSUE TITLE
באג בגרסה החדשה (09)הפרשנים לא מוצגים

### ISSUE THREAD

**Issue by mosh-dvd** [Sivan22/otzaria#182]
הפרשנים לא מוצגים כלל אחרי שעדכנתי את התוכנה

**Comment by IEUDI** [comment]
אתה צודק, גם אצלי זה ככה, הנה תמונה:

![צילום מסך 2024-08-18 082252](https://github.com/user-attachments/assets/a500ecb2-6ac9-467d-a81a-851bf2729b6a)

**Comment by AshiVered** [comment]
וגם אצלי...

![image](https://github.com/user-attachments/assets/3d55e11a-46ec-4362-88ef-125c142dc07e)

**Comment by Sivan22** [comment]
תודה על הדיווח, יתוקן בגרסאות הבאות.

**Comment by Y-PLONI** [comment]
תוקן.
תודה, @Sivan22 !!!
