### ISSUE TITLE
לחיצה על לחצן הדף היומי לא מביאה לדף - אלא לתחילת המסכת

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#183]
## Describe the bug
לחיצה על הסמל של התאריך והדף היומי, מובילה לתחילת המסכת של הדף היומי (למשל: בבא בתרא) אך לא לדף הספציפי (למשל: נד)

### Environment
 - OS: [Win11Pro]
 - Otzaria 0.1.9 Alpha

**Comment by AshiVered** [comment]
ואם כבר מדברים עליו, אשמח שיופיע (לפחות התאריך) בכל המסכים בתוכנה (חוץ מההגדרות אולי) ולא רק במסך "ספריה".

**Comment by IEUDI** [comment]
כתבת :
לחיצה על הסמל של התאריך והדף היומי, מובילה לתחילת המסכת של הדף היומי (למשל: בבא בתרא) אך לא לדף הספציפי (למשל: נד)
אתה צודק, יש להדגיש שזה רק בגירסה 0.1.9 
אבל בגירסה 0.1.8 שם זה עובד מצויין.

**Comment by AshiVered** [comment]
> כתבת : לחיצה על הסמל של התאריך והדף היומי, מובילה לתחילת המסכת של הדף היומי (למשל: בבא בתרא) אך לא לדף הספציפי (למשל: נד) אתה צודק, יש להדגיש שזה רק בגירסה 0.1.9 אבל בגירסה 0.1.8 שם זה עובד מצויין.


אין לי מושג מה ב0.1.8, אבל שים לב, כתבתי בתגובה את מספר הגרסא.

**Comment by Y-PLONI** [comment]
אתה בטח יודע שבPDF זה כן עובד, נכון?
כרגע התקלה רק בטקסט.
@AshiVered

**Comment by AshiVered** [comment]
מה הכוונה בPDF?

**Comment by IEUDI** [comment]
> מה הכוונה בPDF?

זה באמת נשמע טעות.

**Comment by Y-PLONI** [comment]
> מה הכוונה בPDF?

לו היה לך גמרא בפורמת PDF, עם סימניות לפי שם הדף, היא הייתה נפתחת במקום הנכון. רק בקבצי הטקס ישנה בעיה, וסיוון אמר שהיא תתוקן בקרוב, בעז"ה.

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/c0a215b9-d5a7-46cd-86dc-80d881aa674e)

**Comment by IEUDI** [comment]
אני מנסה להבין, האם הש"ס מגיע גם PDF במהדורה 0.1.8 ??? או שצריך להכניס אותו לבד???

**Comment by Y-PLONI** [comment]
> האם הש"ס מגיע גם PDF במהדורה 0.1.8 ???

לא.


> או שצריך להכניס אותו לבד???

כן.

**Comment by IEUDI** [comment]
איך צריך לקרוא לקבצים כדי שיפתח בלחצן דף היומי?

**Comment by Y-PLONI** [comment]
זה כבר עובד, בגרסה החדשה.

‫בתאריך יום ב׳, 19 באוג׳ 2024 ב-15:14 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
זה כבר עובד.
עדכן גרסה.
