### ISSUE TITLE
קובץ PDF אינו נשמר בהיסטוריה

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#185]
בסגירת קובץ PDF אינו נשמר בהיסטוריה כלל.

**Comment by yisrael-rosen** [comment]
יש תנאי בקוד שקובע שרק טקסט ישמר בהיסטוריה
https://github.com/Sivan22/otzaria/blob/8930963dcb8fc3c3122c9a24049691c8826a39d2/lib/models/app_model.dart#L343
אבל זה מבלבל
כי בפונקציה מעליו יש טיפול מיוחד להיסטוריה לPDF
https://github.com/Sivan22/otzaria/blob/8930963dcb8fc3c3122c9a24049691c8826a39d2/lib/models/app_model.dart#L233

@Sivan22 ?

**Comment by Sivan22** [comment]
צריך לתקן.

בתאריך יום ג׳, 27 באוג׳ 2024, 23:54, מאת Yisrael Rosen ‏<
***@***.***>:

**Comment by yisrael-rosen** [comment]
מה צריך לתקן?
ולמה יש בכלל את התנאי הזה?

**Comment by Sivan22** [comment]
להסיר את התנאי, הוא כנראה קיים מסיבות היסטוריות כשהיה מימוש נפרד לכל סוג
ספר.

בתאריך יום ד׳, 28 באוג׳ 2024, 15:46, מאת Yisrael Rosen ‏<
***@***.***>:

**Comment by yisrael-rosen** [comment]
אם כבר מטפלים בהיסטוריה
האם כדאי לשים הגבלה על גודל של ההיסטוריה שלא יגיע בסוף לאלפי שורות

**Comment by Refael11** [comment]
למה לא??
אם מוסיפים אפשרות של חיפוש זה יכול להיות אפילו שימושי

**Comment by yisrael-rosen** [comment]
מה הטעם בלחפש בהיסטוריה של 5 שנים?
אם מישהו משתמש בתוכנה כל יום ופותח 100 ספרים ביום ההיסטוריה תגיע ל3000 שורות בשנה כשהרוב מן הסתם חוזר על עצמו

**Comment by yisrael-rosen** [comment]
כאן כתוב שעד 90 יום
https://support.google.com/chrome/thread/146805323/how-do-i-recover-my-browsing-history?hl=en
