### ISSUE TITLE
לחצן שיסגור את כל הספרים הפתוחים יחד

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#190]
המלצה- כשיש ספרים רבים פתוחים כדאי שיהיה לחצן שיסגור את כל הספרים הפתוחים יחד [כעת זה אפשרי רק על ידי קיצור מקשים.

**Comment by Y-PLONI** [comment]
באיזו תוכנה אחרת יש את זה?
בדפדפן יש לך כזה מקש?
יש את קונטרול + X.
לדעתי, אתה יכול לסגור.

**Comment by IEUDI** [comment]
אתה צודק שאין דבר כזה בהרבה תוכנות, אבל כל מה שיש באוצריא בינתיים אין בהרבה תוכנות,
וכיון שזה לדעתי לחצן מאד שימושי בשביל רבים ממש, על כן אני חושב שזה רעיון מצויין מאד!

**Comment by mosh-dvd** [comment]
יש בבר אילן

**Comment by Y-PLONI** [comment]
> יש בבר אילן

אבקש צילו"מ, אני לא מכיר.
אגב, הרבה מאלו שיש להם ב"T מורידים לגמרי את כל תפריטי הכלים - שתופסים המון מקום, כך שגם מה שיש להם אינו רלוונטי כ"כ.

**Comment by mosh-dvd** [comment]
יש קיצור מקשים לא קיצור כפתור קיצור

**Comment by Y-PLONI** [comment]
אהה...
קיצור מקשים יש גם באוצרייא.

‫בתאריך יום ב׳, 19 באוג׳ 2024 ב-10:26 מאת ‪mosh-dvd‬‏ <‪
***@***.***‬‏>:‬

**Comment by mosh-dvd** [comment]
והוא

**Comment by Y-PLONI** [comment]
> והוא



> יש את קונטרול + X.

**Comment by IEUDI** [comment]
בכל אופן זהו רעיון טוב מאד שיהיה כזה לחצן, וכדאי שיהיה אותו.

**Comment by Sivan22** [comment]
דווקא יש לחיצה ימנית (או ארוכה במסך מגע) על אחת הכרטיסיות ובחירה באפשרות
סגור הכל.

בתאריך יום ב׳, 19 באוג׳ 2024, 15:13, מאת IEUDI ***@***.***>:

**Comment by IEUDI** [comment]
חשבתי שיותר מומלץ שיהיה מקש גלוי ובשניה לסגור הכל, אבל איך שנראה לך.
