### ISSUE TITLE
באג (נסיון) פתיחת פרשנים גם איפה שאינם 

### ISSUE THREAD

**Issue by mosh-dvd** [Sivan22/otzaria#191]
בנוסף לתקלה הקודמת שלא מוצג פרשנים  בלחיצה על כל שורה גם אם אין לה פרשנים (כגון פרק או דף) בגרסה החדשה הוא מנסה להציג פרשנים

**Comment by Y-PLONI** [comment]
> בגרסה החדשה הוא מנסה להציג פרשנים

ו...?
פרט בבקשה.
באיזו גרסה אתה משתמש?

**Comment by mosh-dvd** [comment]
בגירסה 0.9 בנוסף לזה שלא רואים את הפרשנים הוא מנסה להראות גם במקום שאין בכלל פרשנים כמו על השורה של "פרק"

**Comment by Y-PLONI** [comment]
האם הבאג מופיע בעדכון האחרון [0.9.1]? אם לא, סגור בבקשה.

**Comment by Danthig** [comment]
באיזה מאגר אתה משתמש (כוונתי לשאול, האם אתה משתמש בגרסה [0.1.7](https://github.com/Sivan22/otzaria/releases/tag/0.1.7), או [0.1.8](https://github.com/Sivan22/otzaria-dev-channel/releases/tag/0.1.8-beta))?
ישנם כמה שינויים בקבצים, @Sivan22 יכול להיות שהגורם הוא בעיה במאגר (בקבצי הלינקס').

**Comment by Sivan22** [comment]
@mosh-dvd  נא לעדכן אם הבאג קיים גם בגרסה האחרונה (0.1.9-alpha.1)

**Comment by mosh-dvd** [comment]
הסתדר בגרסה האחרונה
