### ISSUE TITLE
המערכת נתקעת בפתיחת ספר שיובא מתוך דיקטה

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#193]
## Describe the bug
המערכת נתקעת בפתיחת ספר שיובא מתוך דיקטה
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
גירסא 0.1.9.1

**Comment by Y-PLONI** [comment]
ככה"נ יש לך עוד ספר עם אותו שם. בדוק זאת.

**Comment by YOSEFTT** [comment]
איזה ספר זה?
מה שמו?

**Comment by Refael11** [comment]
קרה לי בשאגת אריה, ובאבני נזר אני חושב

‫בתאריך יום ב׳, 19 באוג׳ 2024 ב-20:35 מאת יוסף ***@***.***
‬‏>:‬

**Comment by Refael11** [comment]
בחיפוש בתוך התוכנה הוא מראה לי שיש שאגת אריה מתוך דיקטה, ושאגת אריה החדשות
מתוך אוצריא, זה נקרא כפילות?

‫בתאריך יום ב׳, 19 באוג׳ 2024 ב-20:41 מאת ‪Peretz Itzkowitz‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
אם הספר הוא ללא מעברי שורה הוא עלול להיתקע.

בתאריך יום ב׳, 19 באוג׳ 2024, 20:44, מאת Refael11 ***@***.***

**Comment by YOSEFTT** [comment]
זה לא נקרא כפילות, רק אם זה אותו שם ממש [אפילו אם זה לא אותו סיומת, לע"ע].

בדקתי ושו"ת אבני נזר יו"ד אמור לתקוע, וכן שו"ת שאגת אריה.
אם אתה רוצה את השאגת אריה מוכן חלקית הנה זה כאן לפניך.
[שאגת אריה מוכן חלקית.zip](https://github.com/user-attachments/files/16664224/default.zip)

כמו"כ נשמח מאוד אם תוכל לעזור לנו לתקן את כל ספרי דיקטה, ולהתאים אותם לאוצריא,
ראה כאן: https://mitmachim.top/topic/73503/%D7%91%D7%A7%D7%A9%D7%94-%D7%94%D7%A4%D7%A8%D7%95%D7%99%D7%A7%D7%98-%D7%94%D7%92%D7%93%D7%95%D7%9C-%D7%9C%D7%91%D7%99%D7%9F-%D7%94%D7%96%D7%9E%D7%A0%D7%99%D7%9D-%D7%94%D7%AA%D7%90%D7%9E%D7%AA-%D7%A1%D7%A4%D7%A8%D7%99-%D7%93%D7%99%D7%A7%D7%98%D7%94-%D7%A2%D7%91%D7%95%D7%A8-%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90/20

**Comment by Y-PLONI** [comment]
אין מה לעשות, מציע לך להצטרף למאמצי העריכה, בפיקוחו של @YOSEFTT
