### ISSUE TITLE
החיפוש לא מצליח למצוא

### ISSUE THREAD

**Issue by israelzw** [Sivan22/otzaria#195]
כשמחפשים שתי מילים שאחת מהן מודגשת זה לא מצליח למצוא אותם , כנראה בגלל שבקובץ טקסט כדי להדגיש צריך להוסיף תוים סביב המילה המודגשת.
![image](https://github.com/user-attachments/assets/6109a208-2680-4979-a51e-dd7e8ef2d92a)

![image](https://github.com/user-attachments/assets/00f2b603-efc1-4b0f-81ed-0565d6d56a69)

**Comment by Sivan22** [comment]
תוקן
