### ISSUE TITLE
בעיה בגירסה החדשה alpha 0-0.2.0

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#198]
אין אפשרות לעשות חיפוש רגיל ללא יצירת אינדקס. ויצירת אינדקס לוקח שעות. 
למה אין אפשרות להוריד אינדקס מעודכן?

**Comment by Sivan22** [comment]
דבר ראשון חשוב לציין שאפשר בהחלט לעשות חיפוש רגיל, צריך להכנס להגדרות ולבחור באפשרות חיפוש ללא אינדקס.
לגבי האינדקס עצמו, מתברר שהמנוע כנראה לא מתאים לגודל של המאגר, ולכן אין כרגע אינדקס שלם. ניתן לעשות אינדקס למספר ספרים בודדים, כדי לראות ולהתרשם מהממשק של החיפוש, אבל כרגע לא מומלץ ליצור אינדקס מלא עד שיוחלף המנוע למשהו מתאים יותר.
זה היה ניסוי שככל הנראה כשל. מי שהתוכנה בגרסה הזו עובדת לו פחות טוב מהגרסאות הקודמות יכול לחזור לגרסה הקודמת.

**Comment by Y-PLONI** [comment]
טופל בגרסה החדשה.
