### ISSUE TITLE
בעיה בפיצול המסך לשניים

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#199]
כשמפצלים את המסך לשניים לא רואים כלום בתוכנה
מצ"ב תמונה
![image](https://github.com/user-attachments/assets/b35b7696-1b86-49c4-bb8f-71dfd876e270)

**Comment by Sivan22** [comment]
צודק, עדיין לא טיפלתי בתצוגה לאורך, צריך לתקן. (הבעיה החל מגרסה 0.1.9)

**Comment by Sivan22** [comment]
תוקן.

**Comment by cc054848484** [comment]
זה תוקן חלקית, כשנמצאים במצב חיפוש זה עדיין מציג מסך לבן.
מצ"ב תמונה
![image](https://github.com/user-attachments/assets/f9a8ba9a-4049-4027-82ac-5392692ad80e)
