### ISSUE TITLE
אני יכול להוסיף למאגר תלמוד בבלי PDF צורת הדף עם סימניות לכל הש"ס עמוד אחר עמוד

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#200]
@Sivan22 
אני יכול להוסיף למאגר תלמוד בבלי
 PDF
 עם צורת הדף עם סימניות לכל הש"ס עמוד עמוד, בכרך אחד או בכרכים חלוקים.
השאלה אם יש בזה ענין כי זה לוקח הרבה מקום, וחבל סתם להכביד על הורדת התוכנה.
אצלי זה לוקח בערך 440 מ"ב.
לא הצלחתי לדחוס יותר מזה.
השאלה אם זה יביא תועלת לתוכנה, 
למעשה אני חושב שאפשר לשים את זה כחבילה נפרדת להורדה לתוכנה.
אולי אתה מכיר תוכנות שיכולות לדחוס את זה יותר??
בכל אופן אשמח לשמוע את דעתך.
![image](https://github.com/user-attachments/assets/69c03382-ba31-4694-9863-458cb9800bf3)

**Comment by Y-PLONI** [comment]
אם זה מותר להפצה, זה יעזור מאוד מאוד!
שם לב שגם החינמיים לא תמיד מותרים להפצה, ומותרים רק לשימוש אישי.
לגבי הסימניות - לסיון יש סקריפט שמבצע את לבד, כך שזו לא בעייתך.
לגבי הדחיסה, שלח לי ואולי אצליח לדחוס יותר [אתה יכול לנסות בעצמך, עם ABBYY].

**Comment by IEUDI** [comment]
כבר הכל עם סימניות אצלי, ואני צריך לדעת אם זה מעניין את @Sivan22 .
לגבי זכויות בספרים, זה דבר שמפורסם בפריסה גבוהה לציבור, על ידי גמ"ח ספריה תורנית, מופץ במיר ועוד מקומות. יותר מזה איני יודע. ודאי שזה אסור במסחר בתשלום אבל בפרסום חינמי אני חושב שזה מותר, והם מפיצים את זה לאלפים באישור לכאורה.
אין לי באופן זמין אופציה להעלות הרבה חומר, אני יעלה אם אשמע שזה יכנס.

**Comment by Y-PLONI** [comment]
איזה ש"ס זה?

‫בתאריך יום ב׳, 26 באוג׳ 2024 ב-18:40 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬

**Comment by IEUDI** [comment]
נהרדעא, וגשל

**Comment by Y-PLONI** [comment]
להידוע לי א"א לפרסמו. נחכה לסיון שיכריע.

‫בתאריך יום ב׳, 26 באוג׳ 2024 ב-18:45 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬

**Comment by IEUDI** [comment]
עדכנתי פוסט קודם.

**Comment by Y-PLONI** [comment]
אני יוצר עמם קשר כעת.

**Comment by IEUDI** [comment]
קובץ דוגמא,
[אם זה יהיה מעשי בסוף].
[‏‏הוריות צורת הדף.pdf](https://github.com/user-attachments/files/16750975/default.pdf)

**Comment by Sivan22** [comment]
אני בעד, זו אמנם גרסה באיכות נמוכה יחסית ולכן מותרת בהפצה, אבל זה ודאי עדיף מכלום. ואם התנדבו להכין סימניות זה נהדר. הכי טוב אם הסימניות יתאימו במדוייק לאותו מבנה של סימניות בקבצי הטקסט המקבילים באוצריא (דהיינו רמה ראשונה שם המסכת, ורמה שניה דף X. או X:) כך יהיה קל יותר ליצור כפתור שעובר מזה לזה.

**Comment by Y-PLONI** [comment]
יש לך סקריפט לזה, לא?

**Comment by IEUDI** [comment]
תן לי כתובת להעלות את זה

**Comment by IEUDI** [comment]
[תענית תמונה.pdf](https://github.com/user-attachments/files/16837683/default.pdf)
[מועד קטן תמונה.pdf](https://github.com/user-attachments/files/16837684/default.pdf)
[שקלים תמונה.pdf](https://github.com/user-attachments/files/16837685/default.pdf)
[חגיגה תמונה.pdf](https://github.com/user-attachments/files/16837687/default.pdf)
[מכות תמונה.pdf](https://github.com/user-attachments/files/16837688/default.pdf)
[הוריות תמונה.pdf](https://github.com/user-attachments/files/16837690/default.pdf)
[עדיות תמונה.pdf](https://github.com/user-attachments/files/16837691/default.pdf)
[ברכות תמונה.pdf](https://github.com/user-attachments/files/16837746/default.pdf)
[מגילה תמונה.pdf](https://github.com/user-attachments/files/16837771/default.pdf)
[שבת תמונה.pdf](https://github.com/user-attachments/files/16837692/default.pdf)
[זבחים תמונה.pdf](https://github.com/user-attachments/files/16837696/default.pdf)
[חולין תמונה.pdf](https://github.com/user-attachments/files/16837701/default.pdf)
[מנחות תמונה.pdf](https://github.com/user-attachments/files/16837706/default.pdf)
[פסחים תמונה.pdf](https://github.com/user-attachments/files/16837710/default.pdf)
[כתובות תמונה.pdf](https://github.com/user-attachments/files/16837713/default.pdf)
[נדה תמונה.pdf](https://github.com/user-attachments/files/16837718/default.pdf)
[עירובין תמונה.pdf](https://github.com/user-attachments/files/16837720/default.pdf)
[סנהדרין תמונה.pdf](https://github.com/user-attachments/files/16837721/default.pdf)
[בבא מציעא תמונה.pdf](https://github.com/user-attachments/files/16837722/default.pdf)
[בבא קמא תמונה.pdf](https://github.com/user-attachments/files/16837725/default.pdf)
[יומא תמונה.pdf](https://github.com/user-attachments/files/16837726/default.pdf)
[נדרים תמונה.pdf](https://github.com/user-attachments/files/16837730/default.pdf)
[גיטין תמונה.pdf](https://github.com/user-attachments/files/16837733/default.pdf)
[בכורות תמונה.pdf](https://github.com/user-attachments/files/16837737/default.pdf)
[עבודה זרה תמונה.pdf](https://github.com/user-attachments/files/16837740/default.pdf)
[נזיר תמונה.pdf](https://github.com/user-attachments/files/16837743/default.pdf)
[מעילה תמונה.pdf](https://github.com/user-attachments/files/16837749/default.pdf)
[סוכה תמונה.pdf](https://github.com/user-attachments/files/16837753/default.pdf)
[סוטה תמונה.pdf](https://github.com/user-attachments/files/16837756/default.pdf)
[שבועות תמונה.pdf](https://github.com/user-attachments/files/16837757/default.pdf)
[תמורה תמונה.pdf](https://github.com/user-attachments/files/16837762/default.pdf)
[ערכין תמונה.pdf](https://github.com/user-attachments/files/16837763/default.pdf)
[ביצה תמונה.pdf](https://github.com/user-attachments/files/16837765/default.pdf)
[כריתות תמונה.pdf](https://github.com/user-attachments/files/16837767/default.pdf)
[ראש השנה תמונה.pdf](https://github.com/user-attachments/files/16837769/default.pdf)

**Comment by IEUDI** [comment]
יש עוד 3 גדולים:
יבמות מחולק ל-3
[יבמות תמונה_1.pdf](https://github.com/user-attachments/files/16837841/_1.pdf)
[יבמות תמונה_120.pdf](https://github.com/user-attachments/files/16837845/_120.pdf)
[יבמות תמונה_214.pdf](https://github.com/user-attachments/files/16837849/_214.pdf)

**Comment by IEUDI** [comment]
קדושין מחולק
[קידושין תמונה_1.pdf](https://github.com/user-attachments/files/16837857/_1.pdf)
[קידושין תמונה_128.pdf](https://github.com/user-attachments/files/16837860/_128.pdf)

**Comment by IEUDI** [comment]
בבא בתרא מחולק:
[בבא בתרא תמונה_1.pdf](https://github.com/user-attachments/files/16837872/_1.pdf)
[בבא בתרא תמונה_334.pdf](https://github.com/user-attachments/files/16837870/_334.pdf)

**Comment by IEUDI** [comment]
העליתי את כל הש"ס
:)

**Comment by IEUDI** [comment]
מקווה שזה טוב ככה.

**Comment by IEUDI** [comment]
כל הש"ס הוא רק הש"ס עצמו ובלי מפרשיו כמובן. שזה לוקח כמויות מקום.

**Comment by IEUDI** [comment]
העליתי קובץ זיפ,
אפשר להוריד מכאן כל הש"ס כקובץ זיפ
https://github.com/IEUDI/otzaria/releases
או בקישור ישיר להורדה מהירה מכאן: 
https://github.com/IEUDI/otzaria/releases/download/TORA/default.zip
כל הש"ס הוא רק הש"ס עצמו ובלי מפרשיו כמובן. שזה לוקח כמויות מקום.

**Comment by IEUDI** [comment]
עדכנתי קובץ זיפ חדש עם שמות קבצים מדוייקים וסימניות מדוייקות בהתאמה לאוצריא
ברכות
ב. ב: ג. ג:
![אנימציה](https://github.com/user-attachments/assets/9713d3b2-08c9-487c-b2b0-ad407f7f35e9)

**Comment by IEUDI** [comment]
@Sivan22 
אני לא מקבל ממך תגובה משום מה...

**Comment by IEUDI** [comment]
רציתי לשמוע, האם זה הולך להיכנס באמת לספריה בקרוב, וכדומה.

**Comment by Sivan22** [comment]
אני רוצה להכניס את זה. זה ברשימה של הדברים לעשות.

בתאריך שבת, 14 בספט׳ 2024, 23:24, מאת IEUDI ***@***.***>:

**Comment by IEUDI** [comment]
כדאי לבחון את האופציות הקיימות איך לדחוס את זה ולהשאיר את זה בחדות ובאיכות טובה.
הבאתי את זה למקסימום שיכולתי.
[לתשומת לב יש תוכנות שבמקום לדחוס רק מגדילות גודל... וכמובן צריך ליזהר מהם, ויש תוכנות שמורידות את האיכות...]

**Comment by Sivan22** [comment]
הוספתי את זה למאגר וזה עובד יפה, כעת ניתן לעבור מטקסט לPDF ולהפך: 

![otzaria_kD0YaSljDc](https://github.com/user-attachments/assets/e4fd3816-a1f9-4baf-a215-51c7336901d4)

**Comment by Danthig** [comment]
מדהים!!!
עכשיו נותר רק לבדוק האם הPDF / TXT פתוח, ולעבור אליו במקום לפתוח אותו מחדש. 

תבורך!!!
