### ISSUE TITLE
שילוב חיפוש מבוסס בינה מלאכותית

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#201]
ואני מדבר כמובן על המודל ש @Sivan22 מפתח כאן:
https://github.com/Sivan22/halacha-classification

**Comment by Sivan22** [comment]
הריני מודיע חגיגית שזהו התכנון לגרסה 0.3.0

**Comment by Refael11** [comment]
בקצב שלך כנראה שזה לא עוד הרבה זמן 😂

**Comment by Y-PLONI** [comment]
אתה יודע איזה מעבד זה יצרוך?
זו תוכנה שמיועדת בעיקרה לאברכים!
טוב, יהיה אפשר לעשות זאת אופציונלית...
