### ISSUE TITLE
התראה על עדכון

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#21]
אפילו אם עדיין מסובך להגדיר שיהיה אפשר להוריד עדכונים דרך התוכנה,
אולי אפשר שיהיה רשום בתוכנה איזה גרסא היא ואיזה גרסא של המאגר יש,
ולעשות חלונית "מידע על עדכונים" שבאמצעות RSS (או כל טכניקה דומה) תכתוב מה הגרסא הכי חדשה שיש.

**Comment by Sivan22** [comment]
אני עובד כעת על עדכון אוטומטי באמצעות מנגנון מובנה של מייקרוסופט appinstaller.

**Comment by Sivan22** [comment]
נוסף מנגנון של עדכון עצמי בגרסה 0.1.7
