### ISSUE TITLE
0.2.1-alpha.1 חיפוש מדוייק החדש לא מחפש חצאי מילים

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#213]
בגירסא האחרונה
 0.2.1-1
ישנו באג מסויים לדעתי, כי החיפוש מדוייק החדש לא מחפש חצאי מילים,
כלומר בחיפוש הישן אם אחפש ביטוי הבא "חכם מכל האדם" אקבל כמה סוגי תוצאות, אקבל תוצאה אחת ממקומות שכתוב "חכם מכל האדם", תוצאה שניה ממקום שכתוב "החכם מכל האדם" ותוצאה שלישית ממקומות שכתוב "ויחכם מכל האדם"

לעומת זה בחיפוש החדש המדוייק (לא המקורב) זה פשוט מחפש רק מילים שלמות, כך שאם ארצה לקבל שלושה סוגי תוצאות אלו אצטרך להשתמש בשלושה חיפושים נפרדים, **[כי איני רוצה חיפוש מקורב שיביא הרבה מאד תוצאות, גם רחוקות יותר]**.

לדוגמא: החיפוש הישן>>>
![צילום מסך 2024-09-01 084436](https://github.com/user-attachments/assets/c1ce6fcc-8fa6-48d9-8b2e-789ca3f4da7f)

לעומתו שלוש חיפושים נצרכו בחיפוש החדש>>>
![צילום מסך 2024-09-01 004512](https://github.com/user-attachments/assets/4efc704f-1a6e-44be-818e-bbfac1a1c72e)
![צילום מסך 2024-09-01 004530](https://github.com/user-attachments/assets/bfc20067-1a7e-4848-ad90-553979f5842c)
![צילום מסך 2024-09-01 004612](https://github.com/user-attachments/assets/9e138f8b-ebb4-4eb1-9c95-f9b3e22d566c)

**Comment by Y-PLONI** [comment]
כי לא הגדרת "חיפוש מקורב. זה בדיוק ההבדל שבין החיפושים!

**Comment by IEUDI** [comment]
> כי לא הגדרת "חיפוש מקורב. זה בדיוק ההבדל שבין החיפושים!

הסברתי כבר שחיפוש מקורב מביא הרבה יותר תוצאות, ואני שואף בחיפוש רגיל לדיוק כמו בחיפוש הישן שמספק תוצאות לחצאי מילים במילה ראשונה ואחרונה.

**Comment by Danthig** [comment]
לכאורה יהיו בחיפוש כמה רמות - 3 או 4, כאשר יהיה אפשרות לבחור בצורת החיפוש
את הדברים כגון אלו.

‫בתאריך יום א׳, 1 בספט׳ 2024 ב-13:47 מאת ‪IEUDI‬‏ ***@***.***
‬‏>:‬

**Comment by Sivan22** [comment]
כרגע יש רק שני אפשרויות חיפוש: מדוייק, ומקורב. חיפוש מקורב יכול להוסיף אות אחת למילה. אבל חיפוש של מילה באופן חלקי לא נתמך. [אגב, גם בבר אילן זה לא נתמך] 
ייתכן שבהמשך יהיו מספר דרגות חיפוש נוספות, ואולי זה יכלול גם חיפוש מילה כחלק ממילה אחרת, וכנראה שזה יהיה בכל מילה ומילה ולא רק בהתחלה ובסוף.

**Comment by IEUDI** [comment]
> אבל חיפוש של מילה באופן חלקי לא נתמך.

מעניין לציין כי בתוכנת חיפוש הישנה בתוכנה זה כן נתמך, ולדעתי זה היה פגז...!
