### ISSUE TITLE
0.2.1-alpha.1 החיפוש לא מחפש במילים עם ניקוד

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#214]
החיפוש לא מחפש במילים עם ניקוד בין בחיפוש רגיל ובין בחיפוש מקורב,
כדוגמא חיפשתי בחומש בראשית את המילה השמים>>>
![image](https://github.com/user-attachments/assets/2c93b076-ace4-4671-a51a-1ba6d84238a0)

**Comment by israelzw** [comment]
אחרי שהחלפת גירסה, יצרת את האינדקס מחדש?

**Comment by Y-PLONI** [comment]
כללית, בשל ריבוי הגרסאות חובה לכתוב על איזו גרסה נכתב הבאג/הצעה לשיפור.

**Comment by IEUDI** [comment]
נכתב בכותרת מה הגירסה.
והאינדקס כמובן חדש.

**Comment by IEUDI** [comment]
![אנימציה](https://github.com/user-attachments/assets/12030749-58a0-4aba-a540-79cd178b121c)

**Comment by Sivan22** [comment]
תוקן.
