### ISSUE TITLE
קבצי PDF  [בעיקר גדולים] נפתחים בתוכנה באופן איטי מאד

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#215]
קבצי PDF  [בעיקר גדולים] נפתחים בתוכנה באופן איטי מאד
אולי כדאי להחליף את קורא הPDF לקורא מהיר יותר, לשם דוגמא, הקורא PDF הכי מהיר שאני מכיר נקרא SumatraPDF (דף הבית: https://www.sumatrapdfreader.org/free-pdf-reader )

**Comment by Y-PLONI** [comment]
באיו גרסה אתה משתמש?

**Comment by Sivan22** [comment]
צריך ספריית קוד פתוח של פלאטר, זו שהשתמשתי היא הטובה ביותר ממה שקיים.

בתאריך יום א׳, 1 בספט׳ 2024, 11:21, מאת IEUDI ***@***.***>:

**Comment by IEUDI** [comment]
זה קוד פתוח:
https://github.com/sumatrapdfreader/sumatrapdf/releases

**Comment by Y-PLONI** [comment]
הוא כתב לך: זה לא לפלאטר.
