### ISSUE TITLE
0.2.1-alpha.1 אינדוקס קבצי PDF מאד איטי

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#216]
שמתי לב שאינדוקס קבצי PDF מאד איטי.
האם שייך לפתור את זה?

**Comment by Y-PLONI** [comment]
באיזו גרסה אתה משתמש?

**Comment by Sivan22** [comment]
יש לזה כמה סיבות, ואין לכאורה דרך לפתור את זה.

בתאריך יום א׳, 1 בספט׳ 2024, 12:21, מאת Y-PLONI ***@***.***>:

**Comment by Y-PLONI** [comment]
לסגור, @Sivan22
