### ISSUE TITLE
לא מצליח לפתוח את האפליקציה android 10

### ISSUE THREAD

**Issue by 218218y** [Sivan22/otzaria#217]
שלום, אני לא יודע אם יש דרישות מערכת מסוימות, אבל ניסיתי להפעיל באנדרואיד 10 בשתי מקומות ונתקע לי מסך לבן בתחילה ולא נותן לי לבחור את תקית הספרים, ניסיתי גם גרסא 0.1.7 וגם 0.2.1 alpha
<img width="867" alt="צילום מסך 2024-09-01 122047" src="https://github.com/user-attachments/assets/41fa7506-c4d2-46a7-bfa0-3f6cb7cdd038">

יש לציין שגרסא 0.1.6 כן עובדת, אבל חבל מאוד לוותר על כל השידרוגים המועילים

**Comment by Sivan22** [comment]
תנסה עם הספרייה של גרסה 0.1.7

**Comment by Sivan22** [comment]
התכנון הוא שהאפליקציה תגיע ללא ספרייה, ותוריד הכל מהשרת. זה אמור לפתור את הבעיה.
