### ISSUE TITLE
בחזרה לחיפוש אחרי פתיחת תוצאת חיפוש חוזרים לתחילת הרשימה

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#218]
יש לי גירסה 0.2.1-alpha.1
רציתי לציין כי בחזרה לחיפוש אחרי פתיחת תוצאת חיפוש חוזרים לתחילת הרשימה של תוצאות החיפוש.
לכאורה היה כדאי שישאר פתוח באותו מקום שאחז ברשימת התוצאות.
להלן הסרטה חיה>>>
![אנימציה](https://github.com/user-attachments/assets/dadad788-fed2-4821-af74-dce788eb73ae)

**Comment by Danthig** [comment]
ולא רק, אלא גם אם חיפשת רק בספרים מסויימים, לאחר פתיחת תוצאה וחזרה לחיפוש,
החיפוש כולל את כל הספרים...
ידוע, וכנראה יטופל בגרסה הבאה.

‫בתאריך יום א׳, 1 בספט׳ 2024 ב-15:08 מאת ‪IEUDI‬‏ ***@***.***
‬‏>:‬

**Comment by Sivan22** [comment]
תוקן בגרסה 0.2.3
