### ISSUE TITLE
בגירסה חדשה 0.1.8 כדאי לתת אופציה להוריד בנפרד את הספרים שנוספו לספריה

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#220]
בגירסה חדשה 0.1.8 כדאי לתת אופציה להוריד בנפרד את הספרים שנוספו לספריה
שלא נצטרך להוריד הכל מחדש.

**Comment by Sivan22** [comment]
סדר הספרים השתנה מאד, ויש לכך גם השפעה על הקטגוריות של הספרים, ולכן מומלץ
להוריד הכל. הוא לא מוחק את הספרים שהמשתמש הוסיף, אבל כן את הספרים שהגיעו
בגרסה הקודמת ולא בגרסה הזאת, וניתן להוריד אותם בנפרד.

‫בתאריך יום א׳, 1 בספט׳ 2024 ב-20:43 מאת ‪IEUDI‬‏ ***@***.***
‬‏>:‬
