### ISSUE TITLE
בעיה בהתקנה

### ISSUE THREAD

**Issue by mitchazek** [Sivan22/otzaria#225]
אני מנסה להתקין ומופיעה לי הודעת שגיאה כזו:
![image](https://github.com/user-attachments/assets/b300c4a0-d55f-48e2-a29f-3133fd24c085)

מה עושים?

**Comment by Sivan22** [comment]
תתקין את זה קודם: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by mitchazek** [comment]
אכן, התקנתי ונפתרה הבעיה!!!!
תודה רבה מאוד!!!

**Comment by Y-PLONI** [comment]
@Danthig 
תוסיף זאת להדרכה!
