### ISSUE TITLE
כאשר יש שני ספרים  עם שם זהה יש באג אפילו כשאחד מהם קובץ PDF

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#229]
כאשר יש שני ספרים בספריה עם אותו שם זה עושה באג 
לפעמים זה קורה אפי' כשאחד מהם קובץ PDF
לדוגמא אם יש קובץ אחד בבא בתרא טקסט וקובץ אחד בבא בתרא PDF לפעמים אי אפשר לפתוח כלל את הקובץ טקסט.

**Comment by IEUDI** [comment]
בדקתי איך אפשר לעקוף את הבעיה, 
וגיליתי שאם תיקיית הקבצים של PDF תהיה עם שם יותר מוקדם כגון "גמרא" שזה אות ג וזה לפני "תלמוד בבלי"
ככה אפשר לפתוח גם את הקבצים של PDF וגם את הקבצים של טקסט
השאלה אם אפשר לפתור את הבעיה לגמרי.

**Comment by Y-PLONI** [comment]
הבעיה ידועה, הפתרון [הזמני] שלך מעניין. תודה!

**Comment by Sivan22** [comment]
הבעיה נפתרה.
