### ISSUE TITLE
Does version 0.18 not support Android?

### ISSUE THREAD

**Issue by 78417571** [Sivan22/otzaria#230]
Tantivy should be cross-platform, right?

**Comment by 78417571** [comment]
I’m mainly interested in the approach of implementing full-text search locally. If it can’t be cross-platform, it loses its value entirely.​

**Comment by Sivan22** [comment]
theoretically, tantivy should be cross-platform, as it is written in Rust. in reality, however, there is some bug on android. i opened issue in tantivy's repository: https://github.com/quickwit-oss/tantivy/issues/2480.
hopefully i will find a solution.
E.g. the version supporting fast search is 0.2.1 and higher.

**Comment by Sivan22** [comment]
for now i was able to run tantivy on android only inside the RAM, not on disk.

**Comment by Sivan22** [comment]
Solved in 0.2.3
