### ISSUE TITLE
החיפוש לא תקין. 0.2.1

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#233]
הוא כמעט ולא מוצא תוצאות לדוגמא
![image](https://github.com/user-attachments/assets/7d4c7adb-38ab-4734-b643-960f858f909e)
 זה היה אמור להיות הרבה יותר
שמתי את מספר התוצאות על מקסימום וסימנתי אל כל הספרים

**Comment by Danthig** [comment]
שינית את אינדקס?
הוספת והסרת ספרים?
כמה זמן ערך בניית האינדקס?

**Comment by Refael11** [comment]
עדכנתי אינדקס לקח כמה דקות בודדות

**Comment by Refael11** [comment]
כן יש לי כמה ספרים שהוספתי

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/493de1f9-3456-4cad-a51d-db7842fb8235)
להערכתי, האינדקס שבנית היה האינדקס של "איתור" ולא של "חיפוש". של חיפוש אמור לקח יותר מאשר כמה דקות.
אם עדין לא עובד, נסה להסיר את התוכנה **לגמרי**, ולהתקין ולאנדקס מחדש.

**Comment by Refael11** [comment]
זה דוקא כן היה של חיפוש.
אנסה להסיר ולהתקין

**Comment by Refael11** [comment]
כדאי למחוק את הקבצים, או להסיר דרך ווינדוס?

**Comment by Y-PLONI** [comment]
גם וגם.
דרך ווינ' יסיר את התוכנה, ואח"כ תמחק ידנית את תיקית אוצריא.
לא ידועה לי כל בעיה בהוספת ספרים עצמאית.

‫בתאריך יום ה׳, 5 בספט׳ 2024 ב-20:40 מאת ‪Refael11‬‏ <‪
***@***.***‬‏>:‬

**Comment by Refael11** [comment]
הוא תקוע לי על המסך הזה כבר 4 דק'
![image](https://github.com/user-attachments/assets/967902df-8e93-44a8-ac82-1e9ba94c6d33)

**Comment by Refael11** [comment]
@Danthig 
@Y-PLONI 
אז הסרתי והתקנתי מחדש, והוא  אכן מביא לי יותר תוצאות,
אבל כשאני עושה חיפוש רק בגמרא הוא לא מוצא כלום
למה זה קורה?

**Comment by Y-PLONI** [comment]
תסביר ותתן צילו"מ

**Comment by Refael11** [comment]
כשאני עושה חיפוש בחלון עצמו 
![image](https://github.com/user-attachments/assets/19df8ae5-e94d-4963-b88e-666fcb29aa76)
ואילו דרך כרטיסיית חיפוש 
![image](https://github.com/user-attachments/assets/d9af0f53-d632-4cb3-ba66-96364f2f6527)

**Comment by Sivan22** [comment]
היתה בעיה מסויימת עם חיפוש בטקסט עם ניקוד אבל זה נפתר בגרסאות האחרונות.

**Comment by Refael11** [comment]
אתה מתכון לגירסאות שעדיין לא שוחררו?
כי יש לי את הגירסא הכי מועדכנת מ DEV CHANNEL

**Comment by Danthig** [comment]
זה כבר שוחרר בגרסת DEV האחרונה, מעניין שלא מחפש אצלך.
מה שכן כרגע זה מחפש גם בקבצים עם ניקוד, אך לא מדגיש תוצאות.

‫בתאריך יום ה׳, 5 בספט׳ 2024 ב-21:40 מאת ‪Refael11‬‏ <‪
***@***.***‬‏>:‬

**Comment by Refael11** [comment]
![image](https://github.com/user-attachments/assets/e1f1050f-0aba-4d67-a0e4-223ddd7d8d2b)
מוזר...
