### ISSUE TITLE
לא מצליח להוריד את קבצי ה BIN בגירסא 0.2.1

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#240]
אני מוריד את הקבצים ואחרי שהוא מוריד בערך 20% הוא כותב שהקבצים לא זמינים באתר
ניסיתי גם בדפדפן EDG וגם בCHROME

**Comment by abeperl** [comment]
![image](https://github.com/user-attachments/assets/7bf02ddc-76d6-42db-b4cb-a074b298e327)

**Comment by Bshlomecha** [comment]
גם אצלי כותב 'אין אפשרות להוריד. נדרשת הרשאה' [כנראה תרגום של הנ"ל].
![בעיה בהרשאה](https://github.com/user-attachments/assets/a5fd9d6a-f1cc-4125-91b9-b928fc25f037)

**Comment by YisroelTech** [comment]
נראה לי שזו בעיה באירוח/שרתים של GitHub (שמתגלים בגלל גודל הקובץ הגדול והזמן שלוקח להורדה). העליתי את הקבצים (שהורדתי דרך חיבור לאינטרנט מהיר יותר) לאירוח אחר כאן:
https://mega.nz/folder/A8EThT6Q#jObf7AkMhiF6b6lVrNDH0w

**Comment by Bshlomecha** [comment]
תודה. אבל האתר חסום לנו.

האם ישנה אפשרות להעלות לדרייב [או מגיקוד וכד', אתר שפתוח למשתמשי נטפרי]?

![עדיין חסום בנטפרי](https://github.com/user-attachments/assets/4863ec34-f457-43ec-a9f4-f2342721028f)

**Comment by YisroelTech** [comment]
בדרייב לא שייך לי, זה ימלא החשבון שלי...

הנה במגיקוד (אבל היא רק לשני ימים...):
https://send.magicode.me/send-file/file/e152124a7cc107e6f1781291798fe99d337f483d/view
https://send.magicode.me/send-file/file/dd073b2c6f8b1d1327ea324f1c4b9b0d9ef94387/view
https://send.magicode.me/send-file/file/3df986cb96ea330e1e77dfc26902a5b17c0dcdb0/view

**Comment by Y-PLONI** [comment]
https://drive.google.com/drive/folders/1qkgceNC2X******** *****tYulI-sJ6DiL00zH3dZHLam?usp=sharing

**Comment by Bshlomecha** [comment]
ראשית תודה.למעשה ראיתי שהעירו שאפשר להוריד בגירסאות מפתחים.וכיוון שמשם כבר
הורדתי מזמן ואני משתמש היטב - רצוני לדעת האם ישנה מעלה כלשהי בקבצים החדשים
 (אלו עם הסיומת bin)

‫בתאריך יום ה׳, 12 בספט׳ 2024 ב-20:00 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by YOSEFTT** [comment]
זה ס"ה ביחד עם האינדקס מוכן, במקום שתצטרך להעמיס על המחשב דלך ליצור אותם לבד, זה הכל.
ואדרבה, אין בהם את כל הספרים שנוספו בגירסא 018 האחרונה מלפני כמה ימים.
אז ככה שאם כבר עשית אינדקס, ויש לך גירסת 021 אז אין לך בזה שום ענין.

**Comment by Y-PLONI** [comment]
> ראשית תודה.למעשה ראיתי שהעירו שאפשר להוריד בגירסאות מפתחים.וכיוון שמשם כבר הורדתי מזמן ואני משתמש היטב - רצוני לדעת האם ישנה מעלה כלשהי בקבצים החדשים (אלו עם הסיומת bin) ‫

טען לי מישהו שגם יצר אינדקס וגם הוריד את הקבצים, שההתקנה עם הקבצים המותקנים קטנה בהרבה מיצירה עצמאית, לא בדקתי זאת וזה מאוד מוזר.
