### ISSUE TITLE
למה השתנה צורת הורדת התוכנה מפעם לריבוי של ג'יגות?

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#241]
0.2.1-alpha
למה השתנה צורת הורדת התוכנה מפעם לריבוי של ג'יגות?
עדיף לדעתי שתהיה הורדה כמו פעם של מינימום ספריה בנפרד ותוכנה בנפרד, עם אפשרות להורדת גם אינדקס בנפרד.

**Comment by IEUDI** [comment]
מעניין למה נסגר?

**Comment by Y-PLONI** [comment]
> מעניין למה נסגר?

כי לא השתנה לריבוי של ג'יגות, אלא שמי שרוצה אינדקס מובנה ומוכן, שיוריד את זה.
לדוגמא, אם אתה יודע משהו משהו מהחיים שלך [ואתה יודע...], תוריד את הקטן ותבנה אינדקס לבד.
אבל אם אתה רוצה לתת לחבר שלך, שהוא אברך שאינו מבין בזה כלום, לא תוכל לומר לו לאנדקס את "איתור", ורח"כ את "חיפוש", אז תן לו את הקבצים הללו וחסל.
https://github.com/Sivan22/otzaria/issues/240#issuecomment-2348185972

**Comment by IEUDI** [comment]
@Sivan22 
הבנתי את הצורך שיהיה אופציה להוריד את כל התוכנה עם אינדקסים ביחד, וזה רעיון ממש טוב וחזק,
אבל למעשה אני חושב שכן כדאי שתהיה אופציה נוספת,
להוריד את הספריה בנפרד ואת התוכנה בנפרד (SMIX) ואת האינדקסים בנפרד.
בפרט עבור רבים מאיתנו שאין להם גלישה טובה או שהם בחדר מחשבים שכל רגע מיותר עולה הרבה, 
ולכן מומלץ שתהיה אופציה להורדה קלילה יותר.
בתודה.

**Comment by Y-PLONI** [comment]
לא הבנתי אותך בכלל.
יש אפשרות להוריד את התוכנה בנפרד ואת הספרייה בנפרד.
מה צריך יותר מזה? גם את האינדקסים בנפרד? אם אתה מוריד את האינדקסים, אז חהוסיף לכובד שלהם עוד קצת בשביל התוכנה והספרייה זה כלום, וזה מה שיש כעת [הקבצים הגדולים].

**Comment by IEUDI** [comment]
בגירסה האחרונה 0.2.1 יש אופציה להוריד רק הכל יחד,
אין אופציה להוריד רק את הספרים בנפרד. 
תבדוק.

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/releases/tag/0.1.8
ואז תוריד את התוכנה מפה
https://github.com/Sivan22/otzaria-dev-channel/releases/tag/0.2.1-alpha.1

**Comment by IEUDI** [comment]
אני ממליץ את זה בעיקר בשביל הגירסאות הבאות,
תוך כמה גירסאות כבר 0.1.8 לא יהיה מעודכן. וגם יש שינויים בגירסאות רגילות לטובה ממה שהיה בגירסת מפתחים
