### ISSUE TITLE
פתיחת ספרי אוצר החכמה דרך התוכנה

### ISSUE THREAD

**Issue by mynim** [Sivan22/otzaria#243]
לאוצר החכמה יש אפשרות להכניס את המאגר לתוך המחשב ולהפעיל אותה דרך דיסק אונקי
במקרה כזה התוכנה לא נותנת אפשרות לפתוח את ספרי אוצר החכמה שעל המחשב המקומי רק דרך האתר
כמו"כ יועיל מאוד אם תתאפשר גם לחפש בתוכן הספרים של אוצר החכמה דרך התוכנה כך שבמקרה ואין תוצאות חיפוש בתוכנה או שהתוצאות אינן משביעות רצון שיתאפשר בלחיצת כפתור לערוך את החיפוש באוצר החכמה
תודה רבה!

**Comment by Y-PLONI** [comment]
@mendelg 
זה התחום שלך.

**Comment by YOSEFTT** [comment]
אני בדקתי, וזה עובד מצוין, גם כשהאוצר הוא בכונן פנימי. [והדיסק אונקי של הרשיון מבחוץ]
כנראה יש אצלכם תקלה אחרת

**Comment by mynim** [comment]
הבנתי שאצל אחרים זה כן עובד גם כאשר מדובר באוצר החכמה בכונן הפנימי
כיצד אני יכול לבדוק אם מספרי ID שווים
כמו כן האם ייתכן וזה נגרם בעקבות כך שהדיסק של אוצר החכמה אינו בכונן הראשי במחשב אלא בכונן משני?

דרך אגב יש אולי אפשרות להוסיף פונקציה של העברת החיפוש בתוכן הספרים מאוצריא לאוצר החכמה?

**Comment by mynim** [comment]
@mendelg @Sivan22 
אין לי מושג למה אבל הבעיה עדיין לא נפתרה אצלי ואין לי אפשרות לפתוח ספרים באוצר בחכמה באופן מקומי.
כמו כן האם ניתן לפתח אפשרות של לשלוח טקסט החיפוש לחיפוש בתוכן ספרים באוצר החכמה?
