### ISSUE TITLE
מקשי חצים הפוכים

### ISSUE THREAD

**Issue by 218218y** [Sivan22/otzaria#245]
ראשית אומר ישר כח על התוכנה המדהימה
תקלה קלה ישנה בהקלדה בתוכנה גם בספריה איתור חיפוש, אם רוצים לתקן משהו בהקלדה ולחזור אחורה המקשים הפוכים, מקש ימין הולך שמאלה ושמאל ימינה, דהיינו זה מותאם לאנגלית שהמקש השמאלי הוא חזרה אחורה למילה וימינה מתקדם

**Comment by Bshlomecha** [comment]
הוער בעבר - ראה כאן [באות א]:
https://github.com/Sivan22/otzaria/issues/103#issuecomment-2112189706

**Comment by Y-PLONI** [comment]
אין מה לעשות עם ה, זו בעיה בבסיס התוכנה.
