### ISSUE TITLE
יש הרבה לינקים מיותרים של ספרים שכבר נמחקו

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#247]
157 לינקים שצריך לכאורה למחוק כי כבר נמחקו הספרים [יתכן שיש עוד]:
זה פשוט תופס הרבה מקום במחשב...
C:\אוצריא\links\אֲהֵבוּךָ עַד מָוֶת_links.json
C:\אוצריא\links\פניני הלכה, ברכות_links.json
C:\אוצריא\links\פניני הלכה, העם והארץ_links.json
C:\אוצריא\links\פניני הלכה, זמנים_links.json
C:\אוצריא\links\פניני הלכה, טהרת המשפחה_links.json
C:\אוצריא\links\פניני הלכה, ימים נוראים_links.json
C:\אוצריא\links\פניני הלכה, כשרות_links.json
C:\אוצריא\links\פניני הלכה, ליקוטים א_links.json
C:\אוצריא\links\פניני הלכה, ליקוטים ב_links.json
C:\אוצריא\links\פניני הלכה, מועדים_links.json
C:\אוצריא\links\פניני הלכה, משפחה_links.json
C:\אוצריא\links\פניני הלכה, סוכות_links.json
C:\אוצריא\links\פניני הלכה, פסח_links.json
C:\אוצריא\links\פניני הלכה, שביעית ויובל_links.json
C:\אוצריא\links\פניני הלכה, שבת_links.json
C:\אוצריא\links\פניני הלכה, שמחת הבית וברכתו_links.json
C:\אוצריא\links\פניני הלכה, תפילה_links.json
C:\אוצריא\links\פניני הלכה, תפילת נשים_links.json
C:\אוצריא\links\דרכי משה (עמיאל)_links.json
C:\אוצריא\links\אדם מן האדמה_links.json
C:\אוצריא\links\הגיוני עוזיאל_links.json
C:\אוצריא\links\דרכה של תורה_links.json
C:\אוצריא\links\דרשות אל עמי_links.json
C:\אוצריא\links\הגיונות אל עמי_links.json
C:\אוצריא\links\המידות לחקר ההלכה_links.json
C:\אוצריא\links\הצדק הסוציאלי והצדק המשפטי והמוסרי שלנו_links.json
C:\אוצריא\links\לנבוכי התקופה_links.json
C:\אוצריא\links\אורות הקודש_links.json
C:\אוצריא\links\אורות התורה_links.json
C:\אוצריא\links\אורות התשובה_links.json
C:\אוצריא\links\הערות שוליים על אורות_links.json
C:\אוצריא\links\אורות_links.json
C:\אוצריא\links\לנבוכי הדור_links.json
C:\אוצריא\links\מדבר שור_links.json
C:\אוצריא\links\מוסר אביך_links.json
C:\אוצריא\links\עולת ראיה_links.json
C:\אוצריא\links\שמונה קבצים_links.json
C:\אוצריא\links\זכרון ליום ראשון_links.json
C:\אוצריא\links\על כפות המנעול; דרשות לימי התשובה וליום הכיפורים_links.json
C:\אוצריא\links\פור הוא הגורל; דרשות לפורים_links.json
C:\אוצריא\links\פניך אבקש_links.json
C:\אוצריא\links\פני שביעית נקבלה_links.json
C:\אוצריא\links\שיעורים בגמרא - שמיטה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה אבות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה אהלות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה בבא בתרא_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה בבא מציעא_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה בבא קמא_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ביכורים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ביצה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה בכורות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ברכות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה גיטין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה דמאי_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה הוריות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה זבחים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה זבים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה חגיגה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה חולין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה חלה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה טבול יום_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה טהרות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה יבמות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ידיים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה יומא_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה כלאים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה כריתות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה כתובות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מגילה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מדות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מועד קטן_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מכות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מכשירין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מנחות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מעילה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מעשר שני_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מעשרות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה מקואות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה נגעים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה נדה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה נדרים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה נזיר_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה סוטה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה סוכה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה סנהדרין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה עבודה זרה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה עדיות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה עוקצין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה עירובין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ערכין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ערלה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה פאה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה פסחים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה פרה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה קידושין_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה קינים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה ראש השנה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה שבועות_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה שביעית_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה שבת_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה שקלים_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה תמורה_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה תמיד_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה תענית_links.json
C:\אוצריא\links\משנת ארץ ישראל על משנה תרומות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על בבא בתרא_links.json
C:\אוצריא\links\ביאור שטיינזלץ על בבא מציעא_links.json
C:\אוצריא\links\ביאור שטיינזלץ על בבא קמא_links.json
C:\אוצריא\links\ביאור שטיינזלץ על ביצה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על בכורות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על ברכות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על גיטין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על הוריות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על זבחים_links.json
C:\אוצריא\links\ביאור שטיינזלץ על חגיגה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על חולין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על יבמות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על יומא_links.json
C:\אוצריא\links\ביאור שטיינזלץ על כריתות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על כתובות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על מגילה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על מועד קטן_links.json
C:\אוצריא\links\ביאור שטיינזלץ על מכות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על מנחות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על מעילה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על נדה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על נדרים_links.json
C:\אוצריא\links\ביאור שטיינזלץ על נזיר_links.json
C:\אוצריא\links\ביאור שטיינזלץ על סוטה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על סוכה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על סנהדרין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על עבודה זרה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על עירובין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על ערכין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על פסחים_links.json
C:\אוצריא\links\ביאור שטיינזלץ על קידושין_links.json
C:\אוצריא\links\ביאור שטיינזלץ על ראש השנה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על שבועות_links.json
C:\אוצריא\links\ביאור שטיינזלץ על שבת_links.json
C:\אוצריא\links\ביאור שטיינזלץ על תלמוד ירושלמי שקלים_links.json
C:\אוצריא\links\ביאור שטיינזלץ על תמורה_links.json
C:\אוצריא\links\ביאור שטיינזלץ על תמיד_links.json
C:\אוצריא\links\ביאור שטיינזלץ על תענית_links.json
C:\אוצריא\links\שות במראה הבזק חלק חמישי_links.json
C:\אוצריא\links\שות במראה הבזק חלק ראשון_links.json
C:\אוצריא\links\שות במראה הבזק חלק רביעי_links.json
C:\אוצריא\links\שות במראה הבזק חלק שביעי_links.json
C:\אוצריא\links\שות במראה הבזק חלק שישי_links.json
C:\אוצריא\links\שות במראה הבזק חלק שלישי_links.json
C:\אוצריא\links\שות במראה הבזק חלק שמיני_links.json
C:\אוצריא\links\שות במראה הבזק חלק תשיעי_links.json
C:\אוצריא\links\בדי הארון - שביעית_links.json
C:\אוצריא\links\שות בני בנים_links.json
C:\אוצריא\links\איש כלבבו; שמואל_links.json
C:\אוצריא\links\איש לשבטו; שופטים_links.json
C:\אוצריא\links\מעבור הארץ; יהושע_links.json
C:\אוצריא\links\ברכת אשר על התורה_links.json

יתכן שיש עוד.

**Comment by Y-PLONI** [comment]
אלו של הספרים שהוסרו, מחמת שאינם מקובלים על הציבור החרדי. כיון שיש שירצו את הספרים, קבצי הלינק שלהם הושארו.
