### ISSUE TITLE
המלצה לשנות את "משנה תורה" ל- "משנה תורה להרמבם"

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#248]
פעמים רבות קרה לי שחיפשתי רמבם או ספרים על הרמבם ולא מצאתי,
וחיפשתי וחיפשתי עד שמצאתי שקוראים לרמבם "משנה תורה" ...
לדעתי רצוי מאד להוסיף בכל מקום שכתוב 
"משנה תורה"
שיהיה כתוב:
"משנה תורה להרמבם"

**Comment by Sivan22** [comment]
היום סיימתי להטמיע את ה"כותרות נוספות" מספריא, וכעת ניתן לחפש רמבם או משנה תורה וכן שוע או  שולחן ערוך וכדומה. יופץ בגרסאות הבאות אם ירצה ה'.
![image](https://github.com/user-attachments/assets/07e3abd6-6387-4cec-b523-5c1d56294a82)

**Comment by IEUDI** [comment]
ואווו!!! עבור סימניות באיתור זה ממש מטורף!
אבל כוונתי היתה שבחיפוש שם ספר בספריה יהיה כתוב רמבם,
ועדיין אני חושב שזה מאד כדאי ויועיל מאד.

**Comment by Danthig** [comment]
אולי שינוי הספרים כID יעזור גם לזה...
https://github.com/Sivan22/otzaria/issues/246#issuecomment-2351113844
