### ISSUE TITLE
באג בגירסא alpha.1 -0.2.1

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#249]
יש בעיה בחיפוש שאי אפשר לחפש מילה עם ראשי תיבות לדוגמא - ז"ל
![image](https://github.com/user-attachments/assets/70b80de3-9be5-4f9f-bf1f-28a8e12bfc45)

**Comment by Sivan22** [comment]
תוקן בגרסאות האחרונות.

**Comment by Y-PLONI** [comment]
> תוקן בגרסאות האחרונות.

שהופצו?

**Comment by IEUDI** [comment]
בגירסת מפתחים עדיין לא תוקן
[אפשר לעקוף את הבעיה ולהקיש במקום גרשיים ? או *, אבל הבעיה עצמה לא תוקנה, גרשיים כרגע מיועד לסמן טקסט משני צידיו]

**Comment by Y-PLONI** [comment]
כנראה זה תוקן בגרסה שעוד לא הופצה. חכה בסבלנות, ובטח סיון ישלח גרסה בשבועיים הקרובים.
