### ISSUE TITLE
הגדלת שטח המסך להצגת הספרים בתוכנה

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#25]
כדי להרוויח מקום במסך, אולי כדאי להעביר את המיקום של הסימניות לשורה העליונה ביותר, היכן שנמצא הלחצן של סגור/מזער/הרחב, וכמו שקיים בדפדפנים Edge ו - כרום.

**Comment by yoseftct** [comment]
עכשיו נזכרתי שגם ב - SUATRA PDF זה גם כך.
צילו"מ:
![image](https://github.com/Sivan22/otzaria/assets/115775588/08ab715d-a385-488c-ad0c-c3a20fc3ef1b)
