### ISSUE TITLE
עזרה - עדכון אינדקס

### ISSUE THREAD

**Issue by yossef999** [Sivan22/otzaria#251]
הוספתי ספרים אבל אי אפשר לבצע בהם חיפוש,
האם אפשר שהאינדקס יתעדכן אוטומטית,
או שאני צריך לעשות פעולה מסויימת כדי לעדכן אותו?

**Comment by Sivan22** [comment]
אפשר בהגדרות חיפוש לעדכן את האינדקס.

בתאריך יום ב׳, 16 בספט׳ 2024, 16:19, מאת yossef999 ‏<
***@***.***>:

**Comment by Y-PLONI** [comment]
זה לא עדכון, אלא בניה מחדש. האם אני טועה, @SIVAN ?

‫בתאריך יום ב׳, 16 בספט׳ 2024 ב-22:39 מאת ‪Sivan Ratson‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
באיתור - בניה מחדש, בחיפוש - עדכון.

בתאריך יום ב׳, 16 בספט׳ 2024, 23:02, מאת Y-PLONI ***@***.***

**Comment by yossef999** [comment]
מעולה, תודה רבה.

**Comment by Sivan22** [comment]
להריץ את הסקריפט איפוס הגדרות אוצריא, למחוק את האינדקס ולעדכן מחדש.

בתאריך יום ד׳, 18 בספט׳ 2024, 17:38, מאת yossef999 ‏<
***@***.***>:

**Comment by yossef999** [comment]
תודה [@sivan](https://github.com/sivan) 
היכן נמצא הסקריפט הזה? איך השם שלו?

**Comment by Refael11** [comment]
[Uploading איפוס-הגדרות-אוצריא-במקרה-תקלות.zip…]()

**Comment by yossef999** [comment]
תודה על התגובה המהירה,
אבל הקישור אינו תקין, לא הצלחתי למצוא את הסקריפט.

‫בתאריך יום ד׳, 18 בספט׳ 2024 ב-20:58 מאת ‪Refael11‬‏ <‪
***@***.***‬‏>:‬

**Comment by IEUDI** [comment]
איפוס הגדרות אוצריא להורדה מכאן בקישור ישיר:
https://mitmachim.top/assets/uploads/files/1725266772574-%D7%90%D7%99%D7%A4%D7%95%D7%A1-%D7%94%D7%92%D7%93%D7%A8%D7%95%D7%AA-%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90-%D7%91%D7%9E%D7%A7%D7%A8%D7%94-%D7%AA%D7%A7%D7%9C%D7%95%D7%AA.exe

**Comment by yossef999** [comment]
תודה רבה
