### ISSUE TITLE
ערכתי טוב יותר את "חדושי רבנו חיים הלוי" והמרתי אותו לקובץ TXT

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#252]
ערכתי טוב יותר את "חדושי רבנו חיים הלוי" שנכנס למאגר בגירסה 0.1.8
הוספתי לו הרבה מאד כותרות,
תיקנתי כותרות עם טעויות,
שיניתי את הכותרות לכותרות מוכרות וברורות לפי פרקים והלכות,
המרתי כל הכורות שיהיה מותאם לקובץ TXT שיהיה מותאם בצורה רגילה ככל קבצי אוצריא
והכל עכשיו מותאם לאוצריא בצורה טובה יותר.
 והנה הוא:
[חדושי רבנו חיים הלוי על הרמבם.zip](https://github.com/user-attachments/files/17017495/default.zip)

@Sivan22 
נשמח שתעדכן אותו בספריה בגירסאות הבאות

**Comment by Y-PLONI** [comment]
יפה מאוד!
אנחנו מתקדמים לאט בספרים, בא תעזור! העבודה שלך הכי מוצלחת!

‫בתאריך יום ב׳, 16 בספט׳ 2024 ב-21:03 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬

**Comment by IEUDI** [comment]
> אשמח שתשלח לי את הקבצים

איזה? 
ולאיפה?

**Comment by Y-PLONI** [comment]
שלחת לי משהו בצ'אט, וכתבת לי שאתה רוצה תגובה.
אז קודם כל שלחתי לך מייל, שלא יראה כאילו אני מתעלם.
אני מאוד מאוד מעריך את העבודה שלך! השאר עושים עבודה הרבה פחות טובה.
כעת, אשמח אם תכתוב לי במייל את מה שכתבת לי בצ'אט.

‫בתאריך יום ג׳, 17 בספט׳ 2024 ב-20:30 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬
