### ISSUE TITLE
זהר בלי ו' וזוהר חדש עם ו

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#258]
ספרי הזהר נקראים "זהר" בלא ו' אבל זהר חדש נקרא "זוהר חדש" עם ו' וגם חלק מהמפרשים על "זהר" וחלק מהמפרשים הם על "זוהר"
זה כמובן ענין של נוחות בגישה לספרים

**Comment by Bshlomecha** [comment]
נראה לי שהיה טוב להגדיר את מציאת שמות הספרים בצורה רחבה יותר, כך שיזהה כתיב שונה [קידושין קדושין], וכן עם ובלי ראשי תיבות [מהרש"א מהרשא], וסימנים נוספים, וכן ספרים שיש להם שמות נוספים.
עוד יותר - שמות שאפשר לכתבם גם בראשי תיבות - פירוש המשניות פירוש המשנה פיה"מ פיהמ"ש להרמב"ם להר"מ, וכן על זה הדרך....
