### ISSUE TITLE
אני מצרף כאן רשימה חדשה של 30 קבצים נוספים הכפולים בספריה

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#259]
רשימה של 30 קבצים הכפולים בספריה
הקבצים הכפולים נמצאים כל זוג באותה התיקייה...!!!
![צילום מסך 2024-09-17 215502](https://github.com/user-attachments/assets/7a663212-6f9f-46e9-acbf-0d7a59c1eeb9)

איך זה הגיוני?
הרי לא שייך 2 קבצים באותו שם באותה תיקיה?

**התשובה היא, כי באחד הקבצים בכל זוג יש ריוח לפני שם הקובץ**
למשל: 
קובץ אחד נקרא
"דברי חמודות"
וקובץ שני נקרא
 " דברי חמודות"
עם ריוח לפניו.

וזו הרשימה הבאה
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר זרעים\ דברי חמודות על ברכות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר זרעים\דברי חמודות על ברכות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר טהרות\ דברי חמודות על נדה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר טהרות\דברי חמודות על נדה.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר קדשים\ דברי חמודות על מנחות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\דברי חמודות\סדר קדשים\דברי חמודות על מנחות.txt

------------------------------------

C:\אוצריא\אוצריא\תלמוד בבלי\אחרונים\חידושי הלכות\סדר נשים\ חידושי הלכות על מסכת כתובות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\אחרונים\חידושי הלכות\סדר נשים\חידושי הלכות על מסכת כתובות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\אחרונים\חידושי הלכות\סדר טהרות\ חידושי הלכות על מסכת נדה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\אחרונים\חידושי הלכות\סדר טהרות\חידושי הלכות על מסכת נדה.txt

------------------------------------

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר זרעים\ מעדני יום טוב על ברכות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר זרעים\מעדני יום טוב על ברכות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר טהרות\ מעדני יום טוב על נדה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר טהרות\מעדני יום טוב על נדה.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר קדשים\ מעדני יום טוב על מנחות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\מעדני יום טוב\סדר קדשים\מעדני יום טוב על מנחות.txt

------------------------------------

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על בבא מציעא.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על בבא מציעא.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על עבודה זרה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על עבודה זרה.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על שבועות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על שבועות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על בבא בתרא.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על בבא בתרא.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על מכות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על מכות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\ פלפולא חריפתא על סנהדרין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\פילפולא חריפתא\סדר נזיקין\פלפולא חריפתא על סנהדרין.txt

------------------------------------

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\ קרבן נתנאל על עירובין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\קרבן נתנאל על עירובין.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\ קרבן נתנאל על פסחים.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\קרבן נתנאל על פסחים.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\ קרבן נתנאל על ראש השנה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\קרבן נתנאל על ראש השנה.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\ קרבן נתנאל על תענית.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר מועד\קרבן נתנאל על תענית.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\ קרבן נתנאל על גיטין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\קרבן נתנאל על גיטין.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\ קרבן נתנאל על יבמות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\קרבן נתנאל על יבמות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\ קרבן נתנאל על כתובות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\קרבן נתנאל על כתובות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\ קרבן נתנאל על נדרים.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\קרבן נתנאל על נדרים.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\ קרבן נתנאל על קידושין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\קרבן נתנאל\סדר נשים\קרבן נתנאל על קידושין.txt

------------------------------------

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר מועד\תפארת שמואל על סוכה.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר מועד\ תפארת שמואל על סוכה.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר מועד\תפארת שמואל על פסחים.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר מועד\ תפארת שמואל על פסחים.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נזיקין\ תפארת שמואל על שבועות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נזיקין\תפארת שמואל על שבועות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\ תפארת שמואל על קידושין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\תפארת שמואל על קידושין.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\תפארת שמואל על גיטין.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\ תפארת שמואל על גיטין.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\תפארת שמואל על יבמות.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\ תפארת שמואל על יבמות.txt

C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\תפארת שמואל על נדרים.txt
C:\אוצריא\אוצריא\תלמוד בבלי\ראשונים\ראש\מפרשים\תפארת שמואל\סדר נשים\ תפארת שמואל על נדרים.txt

**Comment by Y-PLONI** [comment]
@Sivan22 
לסגור?
