### ISSUE TITLE
ממשק משתמש דינמי ואינדיבידואלי

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#26]
אולי כדאי לאפשר למשתמש להגדיר להעביר את התפריט בצד של דפדוף, איתור ספר, סימניות וכו', לצד השני או למעלה או למטה [כעין מה שיש בדפדפן 'כרטיסיות אנכיות']. 

אתה לא חייב להסכים איתי, אבל אני אוהב את הגישה שאומרת לתת למשתמש לעשות כל מה שרק אפשר, ושהכל יהי' דינמי ואינדבידואלי.

**Comment by yoseftct** [comment]
נכון, וזה יפה מאוד.
וכבר הספקתי לכתוב לך על זה אישיו נוסף.

**Comment by yoseftct** [comment]
עכשיו אני שם לב, שטעיתי בכתיבה, וכוונתי היתה לכתוב את זה לגבי הסימניות של הספרים שנמצאים למעלה, להעביר אותם לצד, ולא לגבי התפריט של דפדוף, איתור ספר, סימניות וכו', כמו שכתבתי כאן בטעות.

ומה שאתה אומר זה לא שימושי, תרשה לי להניח שגם בדפדפן אתה לא משתמש בזה. ומיש משתמש כך בדפדפן וודאי יסכים איתי שזה כן שימושי.
ולא לחינם גוגל ומייקרוסופט נתנו כזו אופצי'.
השאלה העיקרית היא כמה ספרים פותח המשתמש בבת אחת. אני חושה שבזה תלוי הנקודה.
