### ISSUE TITLE
הספרים החדשים מדיקטה

### ISSUE THREAD

**Issue by israelzw** [Sivan22/otzaria#260]
הספרים החדשים מדיקטה שנערכו והוכנסו בעדכון האחרון, אף שחלקם על מסכתות, הם משום מה לא הוכנסו בפרשנים של אותה מסכת.

**Comment by Sivan22** [comment]
זהו פרוייקט לעצמו לקשר את הספרים החדשים לטקסט המקור. בספרים על התנ"ך
והמשניות והרמב"ם ניתן יהיה להיעזר בסקריפטים, אבל על הש"ס כנראה תידרש יותר
עבודה ידנית. [אולי בעתיד יפותחו כלים נוחים לזה]

‫בתאריך יום ג׳, 17 בספט׳ 2024 ב-22:45 מאת ‪israelzw‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
אנחנו במגעים עם ספריא. ה' יעזור והכל יכנס, והם כבר יקשרו הכל.
