### ISSUE TITLE
באג בסינון של חיפוש לפי עץ הספרים

### ISSUE THREAD

**Issue by yossef999** [Sivan22/otzaria#263]
יש באג בסינון של חיפוש לפי עץ הספרים,
אחרי שאני נכנס לאחת התוצאות וחוזר לדף החיפוש - כל הסינון לפי עץ הספרים מתבטל, וצריך לסנן מחדש.
האם יש לכך פתרון?

**Comment by Y-PLONI** [comment]
זה באמת באג רציני, כתבתי ע"ז כבר, כאן:
https://github.com/Sivan22/otzaria/issues/250

**Comment by Danthig** [comment]
@Y-PLONI 
לא הבנתי מה הזכרת שם שמופיע פה?
@yossef999 
תתקין את השחרור [הזה](https://github.com/Sivan22/otzaria/releases/tag/0.2.1-alpha) שם זה תוקן (גרסה יותר מתקדמת מהשחרור למפתחים האחרונה).
@Sivan22 
למה לא שחררת את 0.2.1 אלפא 2 בגרסת מפתחים?
ישנם לפחות שני באגים מאוד משמעותיים שתיקנת, וזה מאוד יעזור במקום להוריד את כל החבילה כולל אינדקס, ואחר כך לאנדקס ספרים אישיים וכודמה, שיוכלו לעדכן רק את הגרסה...
יישר כוחך
תראה עד כמה חשוב אפילו עדכון קטן!

**Comment by yossef999** [comment]
@Danthig
תודה על התגובה,
אבל הגירסה שאני משתמש היא 0.2.1 אלפא,
וגם שם הבאג קיים.
האם התכוונת אולי לקישור אחר עם גרסה מתקדמת יותר?

אגב, המשתמש Y-PLONI הזכיר את הבאג הזה בקישור ששלח, רק בשפה קצרה

**Comment by Danthig** [comment]
> 0.2.1 אלפא

0.2.1 אלפא 1. או 0.2.1 אלפא 2?



> רק בשפה קצרה

אולי תסביר לי למה אתה מתכוון?
זה מה שהוא כתב שם:
> א. F5 לריענון ספר.
> ב. לחצן/קיצור לפתיחת כל עץ הניווט.
> ג. הדגשת המיקום בניווט [כרגע, גם בלחיצה על לחצן בניווט ומעבר וכותרת, אין שום הדגשה שהמסמך שם. מקווה שהסברתי את עצמי נכון].
> ד. כשעוברים ל"חיפוש" [יתכן לחלונות נוספים], כל סרגל הניווט נסגר [כלומר: מצטמצם]. זה משגע לגמרי.

אולי נשמט ממני משהו...

**Comment by yossef999** [comment]
לגבי אלפא 1 או אלפא 2,
כפי שהבנתי כדי להתקין את התוכנה צריך להוריד 2 קבצי bin - אלפא 1 ואלפא 2,
וזה מה שעשיתי.
קובץ התקנה יש רק אחד.

אולי יש משהו שלא הבנתי נכון?

לגבי מה Y-PLONI כתב, אתה צודק,
ממבט ראשון היה נראה לי שסעיף ד הכוונה לבאג שהזכרתי,
אבל מהתבוננות נוספת הבנתי שכוונתו למשהו אחר.

תודה

**Comment by Danthig** [comment]
> לגבי אלפא 1 או אלפא 2, כפי שהבנתי כדי להתקין את התוכנה צריך להוריד 2 קבצי bin - אלפא 1 ואלפא 2, וזה מה שעשיתי. קובץ התקנה יש רק אחד.
> 
> אולי יש משהו שלא הבנתי נכון?

מוזר, אם התקנת כך ועדיין קיים הבאג.
תבדוק בהגדרות התוכנה בשורה הכי למטה, מה כתוב - בגרסה.

**Comment by yossef999** [comment]
![image](https://github.com/user-attachments/assets/1db681a3-08d6-473d-a5c5-6a1db66c1bc9)
כתוב שם אלפא 2, מצורף צילום מסך.

שוב אחזור על הפעולות שאני עושה כאשר אני נתקל בבאג:
- ביצוע חיפוש וסינן את התוצאות לפי עץ הספרים.
- כניסה לאחת התוצאות.
- חזרה לכרטיסייה של החיפוש
- בשלב זה החיפוש מתאפס לחיפוש כללי בלי סינון של עץ הספרים.
אם יש צורך אוכל לשלוח הקלטת מסך.
תודה רבה

**Comment by Danthig** [comment]
טעות שלי, הבאג עדיין קיים. 
כשאני עשיתי חיפוש רק על חלק מהתוצאות, ופתחתי תוצאה אחת, וחזרתי לעמוד התוצאות היה נראה לי שזה נשאר עם הסינון ספרים שבחרתי, אבל בבדיקה אחר כך ראיתי שהבאג הזה עדיין לא תוקן.

**Comment by yossef999** [comment]
תודה,
נקווה שיתוקן בהקדם,
מדובר בבאג מאד משמעותי.

‫בתאריך יום א׳, 22 בספט׳ 2024 ב-16:49 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by motel12** [comment]
https://github.com/Sivan22/otzaria/issues/218

**Comment by Y-PLONI** [comment]
ככה"נ עדיין לא הופץ.
מסתבר שבסוף ביה"ז יהיה עדכון.
