### ISSUE TITLE
בעיה בהתחברות

### ISSUE THREAD

**Issue by A072365** [Sivan22/otzaria#264]
שלום.
רוצה להתחבר לתוכנה, הורדתי אותה - וכאשר אני חילצתי את הקבצים ובוחר את התיקיה הוא לא נותן לי. גם כאשר שיניתי את מיקום התיקיה. 
מצורף תמונות, אשמח לעזרה. תודה.
![צילום מסך 2024-09-19 122131](https://github.com/user-attachments/assets/da42ec07-deb5-4e5b-b90b-6b25fbef32d1)
![צילום מסך 2024-09-19 122123](https://github.com/user-attachments/assets/a1e7d9f3-634b-41de-9f5b-e1586e56237e)

**Comment by Refael11** [comment]
כנראה לא הורדת את 2 הקבצים עם סיומת BIN
או שהקבצים לא נמצאים באותו מיקום בו נמצא קובץ ה EXE

‫בתאריך יום ה׳, 19 בספט׳ 2024 ב-13:36 מאת ‪A072365‬‏ <‪
***@***.***‬‏>:‬

**Comment by A072365** [comment]
דווקא אני חושב שכן
מוזר

‫בתאריך יום ה׳, 19 בספט׳ 2024 ב-14:08 מאת ‪Refael11‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
@A072365 
התוכנה לא אמורה בכלל להקפיץ לך את החלון הזה. תוריד את שלשת הקבצים, שים באותה התיקייה, והכל יעבוד אוטומטית.
