### ISSUE TITLE
בבחירת תוצאה מתוך החיפוש, רשימת החיפוש חוזרת לתחילתה

### ISSUE THREAD

**Issue by motel12** [Sivan22/otzaria#266]
כשבוחרים בתוצאה מתוך רשימת התוצאות, התוצאה נפתחת אוטומטית בדף חדש, כשחוזרים לרשימת התוצאות, הרשימה מתרעננת שוב וחוזרת לתחילתה
בדקתי את זה על חיפוש מהיר שע"י יצירת אינדקס
באופן שיש רשימת תוצאות ארוכה מאד זה יכול להיות מאד מתיש, הכי טוב יהיה עם הרשימה תשאר באותו מצב

תודה רבה על הכל!!!

**Comment by Danthig** [comment]
עיין https://github.com/Sivan22/otzaria/issues/263#issuecomment-2362812617

**Comment by Sivan22** [comment]
תוקן

**Comment by motel12** [comment]
> תוקן

איך אני מקבל את התיקון?
תודה רבה!
