### ISSUE TITLE
אפשרות להוסיף למאגר קיצור דרך לתיקיית ספרים

### ISSUE THREAD

**Issue by motel12** [Sivan22/otzaria#269]
במקרה שכבר יש במחשב מאגר ספרים, שיהיה אפשר להכניס קיצור דרך ממאגר הספרים לתוך התיקייה של המאגר של 'אוצריא' והתוכנה תדע לקרוא משם את הספרים דרך 'דפדוף בספריה' וכן ליצור על זה אינדקס
כעת האופציה היחידה היא להעתיק את כל הספרים ולהכניס לתוך תיקיית הספרים של אוצריא מה שלא אפשרי במחשב עם זיכרון מוגבל יותר.
תודה!

**Comment by Y-PLONI** [comment]
נכתב כבר, ישנה אפשרות להוסיף לינק-קיצור דרך מיוחד, שגורם לתוכנה לחשוב כאילו תיקיה אחרת נמצאת שם...
חפש פה, באחד הסגורים כמדומני.

**Comment by motel12** [comment]
תוכל לפרט יותר את הפתרון?
חיפשתי בכל הסגורים ולא מצאתי...
תודה בכל אופן!

**Comment by Y-PLONI** [comment]
זה באמת נעלם בתוך משהו אחר...
הנה:
https://github.com/Sivan22/otzaria/issues/181#issuecomment-2293573729
הסבר: פתח שורת פקודה [לא פוואר-של!], הזן את הפקודה:
`MKLINK /J "C:\אוצריא\אוצריא\LDPlayerLink" "C:/LDPlayer"`
ואז תיווצר לך בתוך תיקית הספרים תיקיה בשם LDPlayer.
כמובן, שאם לתיקיה שלך קוראים PDF, תחליף את השמות...

**Comment by Y-PLONI** [comment]
@Danthig 
תכניס זאת למדריך, בבקשה.

**Comment by Danthig** [comment]
טרם יקראו ואני אענה...
https://mitmachim.top/topic/70394/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%95%D7%94%D7%95%D7%A8%D7%90%D7%95%D7%AA-%D7%9C%D7%91%D7%A2%D7%99%D7%95%D7%AA-%D7%A0%D7%A4%D7%95%D7%A6%D7%95%D7%AA-%D7%91%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90#:~:text=%D7%99%D7%A9%20%D7%9C%D7%9B%D7%9D%20%D7%AA%D7%99%D7%A7%D7%99%D7%99%D7%94%20%D7%A2%D7%9D%20%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%A8%D7%91%D7%99%D7%9D%20%D7%A9%D7%91%D7%A8%D7%A6%D7%95%D7%A0%D7%9B%D7%9D%20%D7%9C%D7%94%D7%95%D7%A1%D7%99%D7%A3%2C
כתבתי את זה לפני שביקשת, אבל עכשיו אני חושב שכדאי לעשות לזה כותרת כדי שזה
יהיה ניכר.
כמו כן, אשמח שיעברו על זה לבדיקה מטעויות...

‫בתאריך יום ה׳, 26 בספט׳ 2024 ב-22:49 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬
