### ISSUE TITLE
כפתורי הסינון

### ISSUE THREAD

**Issue by SUSTKYNI** [Sivan22/otzaria#274]
יש משהו קצת דבילי בזה שכל האפשרויות שמופיעות בתוצאות מופיעות גם בכפתורים למעלה, במקום שהם יסננו לי את התוצאות לפי תקיות ראשיות.
מצורף דוגמא: למעלה יש אותו מספר אפשרויות כמו למטה אז מה הקטע בו?
![image](https://github.com/user-attachments/assets/8489c269-0041-4b73-a4bc-d256b93c2ca0)

אם זה היה נותן לסנן תוצאות לפי קטגוריות ראשיות ממש כמו ראשונים אחרונים הלכה רמבם ותלמוד בבלי, כדי שיהיה יותר קל לבחור את התוצאה הרצויה אז זה היה תועלתי

2 עוד בענין הלחצנים למעלה, אי אפשר לבחור שתי לחצנים ביחד
בדוגמא הבאה בתחילה בחרתי לסנן מסדר טהרות כשהוספתי שיסנן מסדר זרעים, נמחקו כל התוצאות, במקום שיתווספו גם הספרים מהמסנן הנוסף
![image](https://github.com/user-attachments/assets/80ea20ad-ac74-4ab3-b5d3-2c4c907d38a1)

**Comment by Y-PLONI** [comment]
> יש משהו קצת דבילי

סגנון הכתיבה אינו נעים לאוזן. כלומר, לעין.

**Comment by Y-PLONI** [comment]
לגבי 1: הסיון נותן לך אפשרות לבחור על נושא. למשל, בדוגמא שלך, אם תבחר את "ביכורים", תקבל רק תוצאות ששייכות לזה.
לגבי 2: אתה בחרת לחפש ספר שהוא גם על סדר זרעים, וגם על סדר טהרות. כיון שאין כזה ספר, אין לך כלום.
האם היה נכון יותר לעשות שזה יהיה או או ולא גם וגם? היה על זה דיון בקבוצת הפיתוח, ולמעשה הוחלט כך. @Sivan22 יכול לשנות זאת אם הוא רוצה, אך זו ההגדרה כרגע.

**Comment by SUSTKYNI** [comment]
אני באמת מלא הערכה על העבודה העצומה שנעשית כאן, והתוצאה מדהימה.

לגופם של דברים, אני גם חושב שהסינון אמור לתת לי אפשרות לבחור נושא.
אבל כשאני כותב ביכורים הנושאים שהוא נותן לי לבחור מהם זה בין היתר: אור שמח בן אריה ברטנורא חשק שלמה יד איתן יצחק ירנן ציוני מוהרן מקורי הרמבם לרשש והרשימה עוד ארוכה.
זה לא באמת חלוקה לנושאים, ועובדה שרשימת הנושאים חופפת לרשימת התוצאות.
אני משער שהוגדר בתוכנה, שתקיית אב נקראת נושא, לכן חשבתי להציע שנושא יוגדר רק מה שהוא ממש ראשי בעץ הספרים, דהיינו שהלכה נקרא נושא, ואפשר גם מה שתחתיו בעץ יקרא נושא כדי שגם הרמבם יקרא נושא, אבל לא יותר.

ושוב הערכה עצומה על העמל ועל התוצר

**Comment by SUSTKYNI** [comment]
סליחה על שהדברים מתארכים, אבל עכשיו אני רואה שבמהדורות קודמות באמת הסינון היה לפי נושאים.
ראה כאן https://github.com/Sivan22/otzaria-dev-channel/releases/tag/0.1.8-dev.4
את הנושאים למיילה 'מנחת' שמופיעים בצילום המסך והשווה לנושאים שעולים היום בכתיבת אותה מילה

**Comment by Sivan22** [comment]
הנושאים נגזרים מהתיקיות ותיקיות המשנה, וקשה עד בלתי אפשרי להחליט איזו רמה
קובעת, כי בתוך שס/אחרונים/פני יהושע יש סדר זרעים. אגב, רוב הנושאים נקבעו
מראש כבר במאגר של ספריא, ונעשו שינויים הכרחיים. אם יש נושאים רבים כנראה יש
ספרים עוד יותר רבים. האם כדאי לתת אפשרות לחיפוש נושאים כמו בסינון ספרים
בחיפוש החדש?

בתאריך יום ו׳, 20 בספט׳ 2024, 11:27, מאת SUSTKYNI ***@***.***
