### ISSUE TITLE
חיפוש

### ISSUE THREAD

**Issue by SUSTKYNI** [Sivan22/otzaria#276]
. כדאי לעשות בחיפוש, אפשרויות חיפוש לפי קטגוריה של כל ספרות הראשונים או האחרונים על מסכת מסויימת, לעומת המצב הנוכחי, שבאם אני רוצה לחפש בספרות הראשונים על מסכת בבא קמא, צריך לפתוח תקית רשבא ולסמן בבא קמא, ואז לפתוח את תקית רמבן ולסמן בבא קמא וכולי.
וכן בשולחן ערוך שיהיה אפשרויות חיפוש בכל המפרשים על חלק אורח חיים והכי מוצלח יהיה חיפוש בכל המפרשים על הלכות שבת בחלק אורח חיים [אבל עכשיו השולחן ערוך לא מחולק לפי הלכות רק לפי סימנים]
2. האופציה 'בחר קטגוריות' בחיפוש בגירסא 2אלפא, לא ברור מה זה נותן יותר מהבחירה לפי עץ הספרים. אין שם באמת קטגוריות חדשות. וסתם עכשיו יש בו ריבוי אפשרויות מגובבות של אבן האזל עם תפסיר יונתן ועוד המון הלכות ברמב"ם. ממליץ במקום זאת לעשות בקטגוריות את המוצע לעיל, בחירת מפרשים על מסכת מסויימת וכן בחירת כל המפרשים על הלכות ברמב"ם.
3. באיתור בתוך ספר פתוח הייתי מציע שיהיה אפשר להגדיר לחפש גם בפרשנים שנבחרו להצגה עם הספר

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/b5917b17-1cd0-48c9-9894-5b16d4d4e5b0)
![image](https://github.com/user-attachments/assets/66561564-e146-4c7d-ac55-e797e11de71e)
זה בדיוק מה שנותן הסינון, לא אפשרוות מגובבות [כלומר: כן מגובבות, אבל יש חיפוש למעלה... פשוט חפש "בבא קמא" ו"ראשונים", וזהו!

**Comment by Y-PLONI** [comment]
אפשר לסגור [את 3 תוכל לכתוב מחדש בגיליון אחר]?

**Comment by Sivan22** [comment]
שתי ההערות הראשונות מתורצות אחת בחברתה, התפקיד של הקטגוריות הוא לעשות בדיוק מה שביקשת. 
למעשה, היה דיון גדול אם בבחירת 2 קטגוריות יוצגו רק ספרים שעונים על שתי הקטגוריות, או ספרים שעונים על אחת מהן, וכרגע המצב הוא כמו האפשרות האחרונה, ולכן כדי להגיע למצב שבו רק ראשונים על בבא קמא ייבחרו, נדרש תחילה לבחור את קטגוריית בבא קמא ולבחור את כולה, ואז לבחור את הקטגוריות אחרונים ומחברי זמננו ולהסיר את הסימון מהכל, כך יישארו רק הראשונים על בבא קמא.
יתכן שבעתיד תהיה אפשרות לסנן גם כפי האפשרות הראשונה שהוצעה, ואז זה יהיה פשוט כמו במסך הספרייה, לבחור ראשונים ובבא קמא וזהו.
ההערה האחרונה כבר נכתבה במקום אחר.
