### ISSUE TITLE
גודל האייקונים, וצורתם

### ISSUE THREAD

**Issue by yoseftct** [Sivan22/otzaria#28]
לתת למשתמש להגדיר את גודל האותיות והאייקונים של התפריט של דפדוף, איתור ספר, סימניות וכו', שבצד ימין.

ובמחשבה שני', אפשר להגדיר שיראה רק האייקון בלי המילים, כמו הסמלים שבצד שמאל למעלה (של הגדלה והקטנה, והקטע הקודם והבא וכו'), וכמו בהרבה תוכנות [וגם בווינדוס 11].

**Comment by Y-PLONI** [comment]
אתה יכול להגדיר את האייקונים של המחשב?
אגב, גם בווינ' 11 הולכים להחזיר את המילים, אך אין כאן המקום.
קיצורו של דבר, הריני מתנגד להצעה זו!

**Comment by yoseftct** [comment]
אאם אתה לא רוצה, לא צריך. אבל מה איכפת לך אם אני יהנה????
כמו"כ [אין לי מושג], אבל מסברא גם כשווינ' יחזירו את המילים, הם יתנו גם אפשרות להישאר כמו שהי' עד עכשיו.

**Comment by Sivan22** [comment]
כרגע לא בתכנון.
