### ISSUE TITLE
אפשרות להגדרת מספר נתיבים עבור מיקום הספריה

### ISSUE THREAD

**Issue by HeroldGr** [Sivan22/otzaria#281]
הוספת אופציה להגדרת מספר מיקומים עבור הספרייה, מועיל במקרים כגון מאגר ספרים גדול המאוחסן על התקן חיצוני, ללא צורך להעמיס את כל הקבצים על זיכרון האחסון המובנה במחשב

תודה ענקית על כל מה שנעשה כאן

**Comment by Y-PLONI** [comment]
נכתב כבר פתרון לזה, חפש בסגורים.

**Comment by HeroldGr** [comment]
תודה. אך לא הצלחתי למצוא, אולי יש לך לינק?

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/issues/269

**Comment by HeroldGr** [comment]
תודה רבה עובד מצויין
