### ISSUE TITLE
בעיות שונות באוצריא

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#283]
התבקשתי לפרסם:
1. כשעושים חיפוש (כללי) הוא לא מחפש בספרים מנוקדים שזה כולל ש"ס ותנ"ך. 
2. כשעושים חיפוש מסונן (בחירת ספרים בהם עושים את החיפוש) אם יוצאים מהחלון של החיפוש הסינון מתבטל והוא מציג תוצאות מכל הספרים.
3. בpdf הלשונית של ניוט וכו' לא נכנס באופן אוטמוטי כשמתחילים לגלול.
4. הטעינה בPDF היא מאוד איטית כדאי להגדיר לתוכנה לטעון בכל פעם רק כמה עמודים (כך זה באוצר החכמה).
5. את הטור ומפרשיו כדאי לחלק לארבעה ספרים נפרדים (אורח חיים יורה דעה וכו'). כרגע הקובץ מאוד כבד ונטען לאט.
6. במסמכי וורד אין חיפוש ואינדוקס בהערות שוליים.
7. בשימוש בעכבר - בלחיצה על הגלגלת -  הגלילה האוטומטית לא פועלת.

גרסה: אחרונה. [0.2.1.1]
מערכת הפעלה: ווינ' 11.

**Comment by Y-PLONI** [comment]
1. נכתב כבר.
2. 2. כנ"ל.
3. כנ"ל.
6. ג"כ [כמדומה].

**Comment by Sivan22** [comment]
תודה על הבדיקות, אני אבדוק מה אפשר לעשות בעניין.

בתאריך יום ב׳, 23 בספט׳ 2024, 23:30, מאת IEUDI ***@***.***>:

**Comment by YOSEFTT** [comment]
אולי כדאי שתפרט כאן או לסיון בפרטי את כל השלבים של הבדיקות שעשית, זה יעזור
לו להבין את הבעי' וצורת הפתרון

‫בתאריך יום ג׳, 24 בספט׳ 2024 ב-13:44 מאת ‪Sivan Ratson‬‏ <‪
***@***.***‬‏>:‬

**Comment by IEUDI** [comment]
אני יוסיף דוגמא, ספר בית יוסף לוקח בערך 30 מגה, 
אני הכנסתי איזה ספר שיצרתי שלוקח 50 מגה וזה היה יותר מהיר, כשהיו בו כותרות מועטות, 
וכשהוספתי בו הרבה כותרות נהיה איטי להחריד.

**Comment by IEUDI** [comment]
כהמשך להודעותי הקודמות, אני מביא כאן דוגמא לבדיקה פשוטה שערכתי בספר בית יוסף שנחשב לאחד הספרים שגורמים לתוכנה ליהפך להיות איטית מאד,
ואלו תוצאות הבדיקה:
ספר בית יוסף מכיל **מספר אסטרונומי** של כותרות עבור סימנים וסעיף קטן:   ---16,388---
כאשר הוא מכיל 1,699 כותרות עבור סימנים
ועוד 14,689 כותרות משנה עבור סעיף קטן.
כדי לוודא שזה גורם את האיטיות של הקובץ,
החלפתי את הכותרות של כל ה"סעיף קטן" לקידוד  של שורה מודגשת במקום קידוד כותרת,
והתוצאה היא קובץ מהיר בהחלט, עם פעולה חלקה גם עבור כותרות וגם עבור קישורים ופרשנויות שלא ניזוקו מאומה ממהלך זה.
לדעתי יכולה אומנם להיות בכותרות אלו של סעיף קטן תועלת מרובה בספרים שמהירים יותר, אבל בספר איטי כזה, התועלת של מהירות התוכנה לדעתי מרובה הרבה יותר, מה שגורם לי להמליץ להפוך את הכותרות האלו של סעיף קטן לשורה מודגשת ותו לא כמו שאני עשיתי.
ואני מצרף את קובץ המתוקן שעשיתי, לבדיקתכם.
[כמובן פשוט ואין צריך לאומרו שצריך להוציא מהתוכנה את ספר בית יוסף הקיים כבר, לפני שבודקים את הקובץ החדש כדי שלא תהיה כפילות].
[בית יוסף.zip](https://github.com/user-attachments/files/17135586/default.zip)

**Comment by IEUDI** [comment]
והנה דוגמא נוספת,
משנה ברורה גודל קטן יחסית, **פחות מ-7 מ"ב**
והוא קובץ מהיר מאד מאד,
ניסיתי להוסיף לו כותרות לסעיף קטן, שחסרות בו כרגע,
הוא נהיה איטי מאד,
הסיבה לכך כי בתחילה היה מכיל בערך **700** כותרות שהיו בו, 
ואילו עכשיו הוא מכיל אחרי שטיפלתי בו,  תוספת של **17,394** כותרות של סעיף קטן.
מצרף כאן את הקובץ שערכתי לדוגמא כמה נהיה איטי.
[משנה ברורה.zip](https://github.com/user-attachments/files/17138041/default.zip)

**Comment by SUSTKYNI** [comment]
האם ההחלפה של סעיף קטן רק לשורה מוגדשת, לא תגרום שלא יהיה אפשר להגיע ישירות אליו דרך איתור?

**Comment by IEUDI** [comment]
> האם ההחלפה של סעיף קטן רק לשורה מוגדשת, לא תגרום שלא יהיה אפשר להגיע ישירות אליו דרך איתור?

כלפי בית יוסף-
ודאי שזה גורם שלא יגיעו אליו דרך איתור.
אבל אל תשכח שבבית יוסף במקור אין באמת  סעיף קטן וזה תוספת שלא באמת חשובה כל כך...

כלפי משנ"ב באמת כרגע אין סעיף קטן בכותרות,
ומה שעשיתי במשנ"ב כמובן משבש את הקישורים ופרשנות שבנויים על מספר הקטע וזה תוספת קטע.
דוקא בבית יוסף מה שעשיתי לא משבש כלום, כי זה נשאר אותו מספר קטע.

**Comment by Sivan22** [comment]
ניסיתי את הקובץ וזה אכן משתפר אבל קשה לומר שהבעיה נעלמה לגמרי. רק עם שינוי דרסטי של התשתית למסד נתונים SQL יהיה אפשר לשפר את המהירות.
