### ISSUE TITLE
צביעת תוצאות החיפוש בתוך הספר בקובץ פי די אף

### ISSUE THREAD

**Issue by mynim** [Sivan22/otzaria#284]
כהיום כשעושים חיפוש בתוך ספר מסויים בקובץ פי די אף התוצאות נצבעות בצהוב כדי שיהא ניתן לזהות אותן בקלות
אך בחיפוש הכללי של התוכנה התוצאות אינן נצבעות ורק נפתח העמוד ובו התוצאה 
יעזור מאוד אם תתאפשר לראות את התוצאות בדומה לאוצר החכמה ולא להצטרך לחפש זאת בכל העמוד

**Comment by motel12** [comment]
https://github.com/Sivan22/otzaria/issues/267#issue-2536932533
