### ISSUE TITLE
הגדרות ציון המקורות ב'איתור'

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#287]
**האיתור** הוא כלי שימושי מצויין ביותר [תרתי משמע..]
אמנם נראה שהוא זקוק להגדרות יותר ממוקדות וממודרות על מנת לדייק את ההתאמה של ציוני המקורות לפי המבוקש. 

אזכיר כמה אופנים מצויים:

א. **לכלול צורות שונות של כיתוב** 
ראוי שהמערכת תזהה צורות שונות של מיספור [מלבד מה שכבר הוזכר לגבי שמות הספרים],  
כגון: **כה עמוד ב** / כה ע"ב / כה, ב / כה: ; (ואולי גם כל האופנים האלה כאשר מופיע **כ"ה**). 
וכמו כן סימן א סעיף א / סי' א סעי' א / ס"א. 
וכן ס"ק א / סק"א. 
וכן הלכה א / הל' א / ה"א.

[ואולי גם - עם גרשיים של ראשי תיבות ובלעדיהן, וכן לזהות שני גרשים [''] כמו גרשיים ["] !].

ב. **זיהוי של ערכים עיקריים בציון מראי המקומות** 
למשל כאשר כותבים **'פרק ג'** - ראוי שהמערכת תקדם את הציונים הרלוונטיים [ואולי אפילו תשמיט את כל השאר !!],
כגון אלו שרשום בהם '**פרק ג**', ולא '**פרק** כ**ג**', ולא '**פרק** א משנה **ג**'.
ובודאי שלא '**פרק**י דר"א ל**ג**' או 'ל**פרק**ים סימן י**ג**'.

זה עתה חיפשתי 'שבת לא' והביא לי גם את אלו:
1. קובץ שיטות קמאי על תמיד **לא** , שמקורו מרבנו פרחיה על **שבת**.
2. וגם ספר 'וביום ה**שבת** הלכות מ**לא**כת בורר...
3. וכן ספר חמדת ימים וכולי וכו' **שבת** וכו' וכו' ש**לא** לעקור וכו' וכו'....
4. ואפילו 'מלאכת מח**שבת** ח**ל**ק **א**'. (זה כבר כשרון של המנגנון לערוך דילוגי אותיות ופרפראות לחכמה...).

ג. **סידור הגיוני של המקורות המופיעים בתוצאות** 
כדאי שהתוצאות תהיינה מסודרות [ואולי גם מחולקות למדורים] לפי דרגת ההתאמה שלהם לשאילתה, או לפי סדר כרונולוגי של הספרים [או לפי תיקיות המקור].

ד. מלבד זאת - בסוף הרשימה הופיעו כמה 'ציונים' שהם העתקות פיסקאות שלמות וארוכות מכמה ספרים, ולא הצלחתי למצוא בה בהגדרות גרם להם שיעלו.
הנני מצרף צילו"ם.

![איתור מקורות באוצריא](https://github.com/user-attachments/assets/3f420318-64d6-410a-97cf-1b55e94e680c)

**Comment by Refael11** [comment]
ממה שאני מבין חלק גדול מהבעיות אמורות להיפתר בגירסא הבאה

**Comment by Sivan22** [comment]
מכיון שקשה מאד לערוך את כל האפשרויות הללו ידנית (כמו שאכן עשו בבר אילן) אז אני משתמש ב"מרחק לוינשטיין" שנגזר מכמות השינויים שצריך לעשות בתוצאה כדי להגיע לשאילתה. וכמובן שהמיון הוא לפי רמת ההתאמה.
בגרסה הבאה יהיו בעזרת ה' גם שמות נרדפים לספרים (מתוך מאגר ספריא).

**Comment by Bshlomecha** [comment]
ייש"כ.

באמת בבר אילן [עכ"פ בגירסה החדשה] - הרשימה חולשת על אפשרויות רבות ומגוונות:

כתיב מלא וחסר: מידות מדות

שמות קרובים: פירוש המשנה [אבל לא 'פירוש המשניות'] - פיה"מ פיהמ"ש פיהמ פיהמש
וכד'.

[וגם בלי ראשי תיבות שוע אוח מב וכיוצא באלו].


‫בתאריך שבת, 12 באוק׳ 2024 ב-22:37 מאת ‪Sivan Ratson‬‏ <‪
***@***.***‬‏>:‬
