### ISSUE TITLE
צורת הדף באוצריה

### ISSUE THREAD

**Issue by DVD150** [Sivan22/otzaria#288]
האם יש אפשרות לדבר כזה בתוכנה כי כשניסיתי להכניס קובץ וורד עם טבלה הוא לא הצליח להציג אותה והוא הציג לי כל קובייה כשורה

**Comment by Danthig** [comment]
כדי לשמור על צורת הדף, השתמש בקובץ PDF.



‫בתאריך יום ג׳, 24 בספט׳ 2024 ב-23:49 מאת ‪DVD150‬‏ <‪
***@***.***‬‏>:‬

**Comment by DVD150** [comment]
אני רוצה שיהיה אפשר להעתיק ממנו אבל זה יהיה מעומד בצורת הדף
בPDF לא נותן להעתיק רק את הטור האמצעי אלא את כל השורה מצד לצד לכן אני מנסה בוורד שאז יש לך קובייה בפני עצמה
