### ISSUE TITLE
המלצה- להגדיר שהיסטוריית אינדוקס תהיה בתוך תיקית האינדקס

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#289]
כיום ההגדרה בתוכנה שהתוכנה זוכרת איזה קבצים אונדקסו, וזה נמצא יחד עם כל ההיסטוריה והגדרות משתמש בתיקיה כל שהיא במחשב,
מה שגורם שמי שרוצה למחוק את האינדקס עדיין לא יכול לאנדקס מחדש גם אחרי מחיקת תיקיית האינדקס עד שימחוק את הגדרות והיסטוריית המשתמש.
והמלצתי  להגדיר בתוכנה שהקובץ מערכת שבו נמצא היסטוריית האינדוקס יהיה בתוך תיקית האינדקס.
זה גם מאד יועיל למי שהתוכנה נמצאת לו על אונקי ומשתמש פעם במחשב זה ופעם במחשב אחר שיכול לעדכן את האינדקס גם אם בנה אותו במחשב אחר, כי כיום אין אופציה כזו אלא לבנות את כולו מחדש.

**Comment by Sivan22** [comment]
בתכנון

בתאריך יום ה׳, 26 בספט׳ 2024, 20:25, מאת IEUDI ***@***.***>:

**Comment by Sivan22** [comment]
בוצע
