### ISSUE TITLE
חלון קדם-פתיחה, ובאג קטן.

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#292]
כיון שבמחשבים איטיים לוקח לתוכנה כמה וכמה שניות להפתח, כדאי לעשות חלונית קטנה [כמו באופיס, ובשו"ת בר אילן], המקדימה את התוכנה.
כשמוגדר לתוכנה מיקום שונה לספריה, והיא לא מוצאת אותו [לדוגמא: אם הוא בדיסק אחסון חיצוני], יהא מקפיצה שוב ושוב חלון שמבקש להגדיר את מיקום הספריה, **ולא ניתן לסגור את התוכנה** [חוץ מבמנהל המשימות].

**Comment by 0504117825** [comment]
> כשמוגדר לתוכנה מיקום שונה לספריה, והיא לא מוצאת אותו [לדוגמא: אם הוא בדיסק אחסון חיצוני], יהא. מקפיצה שוב ושוב ולא חלון שמבקש להגדיר את מיקום הספריה, ניתן לסגור את התוכנה [חוץ מבמנהל המשימות].

זה קרה לי גם. עד שהבנתי שהטעות היא שלא מגדירים את מיקום הספריה עצמה ממש: E:\אוצריא\אוצריא
אלא את המיקום שבתוכו נמצאת התיקיה של הספריה: E:\אוצריא
ואז זה עובד מצויין!!

**Comment by Sivan22** [comment]
החלון המעצבן לא יהיה קיים החל מגרסה 0.2.3

‫בתאריך יום ה׳, 14 בנוב׳ 2024 ב-10:36 מאת אליהו ט. <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
אז נשאר מזה רק את ההצעה לחלון קדם-פתיחה.
לשיקולך, אם לסגור.

**Comment by Sivan22** [comment]
אני חושב על שיפור מסויים שיזרז את הפתיחה.
