### ISSUE TITLE
אם יהיה אפשר לפנות לציבור להתחיל לערוך ספרים למאגר

### ISSUE THREAD

**Issue by DVD150** [Sivan22/otzaria#296]
אולי אפשר להקים לזה אתר כמו מתמחים או אפילו בתוך האתר הזה ולשם יעלו או ייקחו קבצים למאגר 
ועדיף שזה יהיה מחולק לכמה רמות לדוגמה  טקסט   כותרות   ועריכה סופית
גם לספרים שקיימים במאגר (ראשונים ואחרונים יש בלי סוף טעויות כתיב קטעים חסרים וכו')
וגם לספרים חדשים שחסרים במאגר

**Comment by Sivan22** [comment]
יש פרוייקט שלם שעוסק בזה, ראה כאן https://mitmachim.top/topic/73503/%D7%91%D7%A7%D7%A9%D7%94-%D7%94%D7%A4%D7%A8%D7%95%D7%99%D7%A7%D7%98-%D7%94%D7%92%D7%93%D7%95%D7%9C-%D7%9C%D7%91%D7%99%D7%9F-%D7%94%D7%96%D7%9E%D7%A0%D7%99%D7%9D-%D7%94%D7%AA%D7%90%D7%9E%D7%AA-%D7%A1%D7%A4%D7%A8%D7%99-%D7%93%D7%99%D7%A7%D7%98%D7%94-%D7%A2%D7%91%D7%95%D7%A8-%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90?_=1728761264358
