### ISSUE TITLE
באגים שונים [תוקנו]

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#3]
תודה רבה על המיזם הנפלא - מיוחד ביותר
הערות:
1. מקשי החיצים לא עובדים.
2. אי אפשר להעתיק כמות טקסט גדולה בבת אחת.
3. 3. איך מורידים חבילת התקנה לאפל ולאנדרואיד.
4. 4. מתי יצא גירסא מעודכנת של התוכנה?

**Comment by Sivan22** [comment]
תודה על ההערות.
1+2. אני מקווה שבגירסאות הבאות הבעיות הללו ייפתרו.
3. אפליקציה לאנדרואיד כעת בשלבי בדיקה אחרונים. אפליקציה ללינוקס בשלבי אריזה. אפליקציה לאפל (מק ואייפון) כרגע אין באפשרותי לבנות (מחפש מתנדבים).
4. בעזרת ה' אני מקווה שבשבועות הקרובים. הקוד מתעדכן מידי פעם, וניתן לבנות לבד.

**Comment by cc054848484** [comment]
תודה רבה על המענה המהיר! יישר כח גדול על העבודה הנפלאה.

‫בתאריך יום ו׳, 23 בפבר׳ 2024 ב-16:58 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by cc054848484** [comment]
אם כבר בנושא שיפורים עסקינן -
1. אין אפשרות לערוך את הטקסט במקרה של טעות.
2. יש ספרים חשובים שלא נמצאים במאגר, ונמצאים במאגר של תורת אמת כגון חברותא
על כל מסכתות הש"ס ועוד ספרים. אשמח אם תוסיפו זאת למאגר. או לחלופין שתהיה
אפשרות להוסיף קבצי טקסט.
תודה רבה על כל ההשתדלות המרובה. תזכו למצוות

‫בתאריך שבת, 24 בפבר׳ 2024 ב-21:10 מאת עשהאל ק ***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
ניתן בהחלט להוסיף קבצי טקסט למאגר. נדרש רק להעתיקם לתיקיית אוצריא. עם זאת, תוכן העניינים לא יוצג אלא אם כן הוגדרו כותרות באמצעות תגי html.

**Comment by Sivan22** [comment]
> @Sivan22 HTML או MarkDown?

כרגע - קבצי טקסט עם תגיות html.

**Comment by Sivan22** [comment]
כעת שוחררה גרסה לאנדרואיד.

**Comment by cc054848484** [comment]
הצעת ייעול נוספת:
1. הוספת אפשרות להדפסה מתוך התוכנה עצמה
2. כשלוחצים על הלחצן איתור ספר זה לא מתחיל לחפש עד שמסמנים עם העכבר בשורת החיפוש.
3. נראה לי שעדיף שברירת המחדל שפותחים ספר תהיה שחלונית הניווט והחיפוש יפתחו באופן אוטומטי.
4. תודה רבה

**Comment by cc054848484** [comment]
ילקוט יוסף עין יצחק שות הראשון לציון.rar
<https://drive.google.com/file/d/1oxdJgE3IsgE4yGPXNN4msWnxYFpS3-FM/view?usp=drive_web>
הקבצים הנ"ל חדשים יותר ממה שיש בהברו בוקס
הקבצים הנל עם אפשריות חיפוש
