### ISSUE TITLE
באג כשחלון התוכנה מוקטן

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#30]
כשחלון התוכנה פתוח בגודל כזה כמצורף,
אז התפריט שבצד ימין עובר למטה, אבל האייקון של הסימניות לא קיים משום מה, למרות שיש לו הרבה מקום.
![צילום מסך 2024-04-05 113943](https://github.com/Sivan22/otzaria/assets/115775588/9d7138cb-fb8e-47b8-9f88-9015e0ab4c75)

**Comment by yoseftct** [comment]
תוקן בגירסא 0.1.6
אפשר לנעול את השיחה הזו.
