### ISSUE TITLE
הצעת ייעול ושיפור לאוצריא

### ISSUE THREAD

**Issue by haimargeman** [Sivan22/otzaria#301]
1. להוסיף אפשרות לכתוב הערות על גוף הטקסט (כמו באוצר החכמה, כלומר שיהיה אפשר לסמן מילה או משפט, ועליו לכתוב הערות או מו"מ אישיים)
2. להוסיף תמיכה בהוספת ספרים על ידי קיצורי דרך או תמיכה בעידכון ספרים ממקור חיצוני. כלומר לדוג' יש לי דיסק או קי עם 150 ג'יגה ספרים, ולהכניס את הכל למחשב זה מורכב. אך אם אוכל להכניס לספריית אוצרייא רק קיצורי דרך, או שהתוכנה עצמה תתמוך בקליטת ספרים ממקור חיצוני (כמו הנגן של ווינדוס - אפשר להגיד לו איפה לחפש שירים) זה יהיה מאוד יעיל וישפר את התוכנה לתוכן בלתי נדלה של ספרים בעיצוב החדשני שייחודי לה. (וזה בלא שיגרע מכך שספריית הבסיס של אוצריא תהיה בתיקיית אוצריא הרגילה כדי שלא יהיו קריסות וכד'.
יישר כח על החדשנות והרצון להתקדם ולשפר.

**Comment by Danthig** [comment]
> @Y-PLONI תוכל להפנות אותי לפתרון (לבעייה 2) ? אני לא מוצא אותו.

https://mitmachim.top/topic/70394/%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%95%D7%94%D7%95%D7%A8%D7%90%D7%95%D7%AA-%D7%9C%D7%91%D7%A2%D7%99%D7%95%D7%AA-%D7%A0%D7%A4%D7%95%D7%A6%D7%95%D7%AA-%D7%91%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90#:~:text=%D7%99%D7%A9%20%D7%9C%D7%9B%D7%9D%20%D7%AA%D7%99%D7%A7%D7%99%D7%99%D7%94%20%D7%A2%D7%9D%20%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%A8%D7%91%D7%99%D7%9D%20%D7%A9%D7%91%D7%A8%D7%A6%D7%95%D7%A0%D7%9B%D7%9D%20%D7%9C%D7%94%D7%95%D7%A1%D7%99%D7%A3%2C%20%D7%90%D7%9A%20%D7%90%D7%AA%D7%9D%20%D7%A6%D7%A8%D7%99%D7%9B%D7%99%D7%9D%20%D7%90%D7%95%D7%AA%D7%94%20%D7%91%D7%9E%D7%A7%D7%95%D7%9E%D7%94%2C%20%D7%95%D7%90%D7%99%D7%A0%D7%9B%D7%9D%20%D7%A8%D7%95%D7%A6%D7%99%D7%9D%20%D7%9C%D7%94%D7%A2%D7%AA%D7%99%D7%A7%20%D7%90%D7%AA%20%D7%9B%D7%9C%20%D7%94%D7%A7%D7%91%D7%A6%D7%99%D7%9D%3F%0A%D7%A0%D7%99%D7%AA%D7%9F%20%D7%9C%D7%94%D7%95%D7%A1%D7%99%D7%A3%20%D7%A7%D7%99%D7%A6%D7%95%D7%A8%20%D7%AA%D7%99%D7%A7%D7%99%D7%99%D7%94%20%D7%93%D7%A8%D7%9A%20%D7%A9%D7%95%D7%A8%D7%AA%20%D7%94%D7%A4%D7%A7%D7%95%D7%93%D7%94%2C%20%D7%9B%D7%9A%20%D7%A9%D7%AA%D7%95%D7%9B%D7%9C%D7%95%20%D7%9C%D7%A4%D7%AA%D7%95%D7%97%20%D7%90%D7%AA%20%D7%94%D7%A1%D7%A4%D7%A8%D7%99%D7%9D%20%D7%A9%D7%9E%D7%9E%D7%95%D7%A7%D7%9E%D7%99%D7%9D%20%D7%91%D7%9E%D7%A7%D7%95%D7%9D%20%D7%A9%D7%90%D7%99%D7%A0%D7%95%20%D7%A1%D7%A4%D7%A8%D7%99%D7%99%D7%AA%20%D7%90%D7%95%D7%A6%D7%A8%D7%99%D7%90%2C%20%D7%95%D7%90%D7%A4%D7%99%D7%9C%D7%95%20%D7%9C%D7%90%D7%A0%D7%93%D7%A7%D7%A1%20%D7%90%D7%95%D7%AA%D7%9D!%0A%D7%94%D7%95%D7%A8%D7%90%D7%95%D7%AA%3A

**Comment by Y-PLONI** [comment]
> העצה. להוסיף שנים מקרא ואחד תרגום, וכן שיהיה אופציה בתורה לפי פרשיות ולא רק לפי פרקים

תפתח גיליון חדש.
