### ISSUE TITLE
0.2.1-alpha.2 יש גם עדכון לווינדוס?

### ISSUE THREAD

**Issue by IEUDI** [Sivan22/otzaria#303]
בהקשר לעדכון שיצא 0.2.1-alpha.2 יש עדכון חדש גם לווינדוס?
https://github.com/Sivan22/otzaria-dev-channel/releases/tag/0.2.1-alpha.2

**Comment by Sivan22** [comment]
לא גמור עדיין.

‫בתאריך יום ד׳, 30 באוק׳ 2024 ב-14:19 מאת ‪IEUDI‬‏ <‪
***@***.***‬‏>:‬
