### ISSUE TITLE
כמה הצעות יעול בנושא הניווט בתוכנה

### ISSUE THREAD

**Issue by efratnoi** [Sivan22/otzaria#309]
כמה הצעות יעול:

1. במפרשים שיהיה כפתור לפתוח את המקור שעליו המפרש מוסב.
2. אפשר לעשות כפתור תחת המועדפים של לוח העתקות. לפעמים רוצים להעתיק גם חלק מהגמ' וגם מרש"י וריטב"א, אז במקום לצאת מהתוכנה כל פעם אפשר שההעתקה תתבצע ללוח העתקות. אם המשתמש מדביק בוורד זה רק העתקה אחרונה אבל אם הוא רוצה את הכל הוא יכול לגשת ללוח העתקות ולהעתיק משם את כל הלוח.
3. ואולי אפשר עוד להוסיף שהוא יוכל ממש לשמור לוחות כעין מראה מקומות.בניווט למשל בסידור אפשר לעשות שאם יש כותרת משנה אז לחיצה על הכותרת גם תגלול לשם אבל גם תפתח את העץ באותו מקום לכותרות המשנה.
4. סתם מועיל, אם כבר יש תאריך עברי שיהיה כבר לוח שנה עברי בסיסי.

**Comment by Sivan22** [comment]
אפשר להשתמש בלוח המורחב של ווינדוס.
