### ISSUE TITLE
מקשי קיצורים באות אחת

### ISSUE THREAD

**Issue by mosh-dvd** [Sivan22/otzaria#31]
אני חושב שיש כמה קיצורי דרך חשובים כמו לעבור בין תיקיות וחיפוש בתוך ספר (בנוסף שיהיה אפשר לעשות קיצור דרך עם אות אחת בלי cotrl 
בנוסף היה מאוד מוסיף אם יהיה אפשר לגשת למיקום מדוייק (כמו שבת לג ברכות כ עמוד ב)

**Comment by Y-PLONI** [comment]
מיקום מדוייק הוזכר כאן:
https://github.com/Sivan22/otzaria/issues/23

**Comment by mosh-dvd** [comment]
> לא סביר לעשות קיצור באות אחת, ללא קונטרול. מכיר תוכנה שיש בה את זה? ואם אתה מקליד משהו, זה יפעיל את הקיצור?
> 
האם ראיתי כן בר אילן 
זה ממהר מאוד את הגישה לחיפוש ועוד
עם אתה מקליד משהוא כשאתה עומד על התוכנה סתם זה יפתח ואם אתה בתוך חיפוש לא

**Comment by Y-PLONI** [comment]
להידוע לי גם בבר אילן זה קונטרול + אות. רוצה לספר לי למה אתה מתכוון, ובאיזו גרסה?

**Comment by mosh-dvd** [comment]
בבר אילן אפשר לשנות את זה במנהל הקיצורי דרך (גם פו בקשתי היא שיהיה אפשר לשנות לזה)
