### ISSUE TITLE
באג במצב כהה

### ISSUE THREAD

**Issue by efratnoi** [Sivan22/otzaria#310]
לא בטוח שזה באג, אבל מצב כהה משפיע גם על קבצי PDF מה שאומר שאם אני פותח צורת הדף של הש"ס זה שחור עם אותיות לבנות וזה ממש לא נוח.
אולי לעשות אפשרות של מצב כהה נפרד לPDF.
![Screenshot (1)](https://github.com/user-attachments/assets/de0c5ded-a1db-41e6-9af8-97f1b6dbca30)

**Comment by Sivan22** [comment]
זה ממש לא באג, להפך זה בכוונה תחילה, זה כל הרעיון של מצב כהה.

‫בתאריך יום ה׳, 31 באוק׳ 2024 ב-23:44 מאת ‪efratnoi‬‏ <‪
***@***.***‬‏>:‬

**Comment by efratnoi** [comment]
אתה צודק.
התכוונתי שבFOXIT למשל, יש מצב כהה שהוא רק על התצוגה. ושוב הסיבה היא שצורת הדף רגילים לראות כמו שמכירים אפילו שטקסט רגיל יש שיותר נוח להם בכהה. לכן זה נקרא צורת הדף. והצעתי גם פיתרון.
צירפתי תמונה. בכל אופן תודה על התגובות והתיחסות.
![Screenshot (1)](https://github.com/user-attachments/assets/abe4d939-6246-42a0-9aba-3ab1e7c75a0d)

**Comment by Y-PLONI** [comment]
@Sivan22 
לסגור, או שאתה מתכנן לעשות עם זה משהו?
