### ISSUE TITLE
דפדוף PDF

### ISSUE THREAD

**Issue by efratnoi** [Sivan22/otzaria#312]
המלצה.
כיון שאי אפשר לנווט במסמך PDF בלי סימניות מוכנות, אולי אפשר שיהיה אפשר לדפדף לעמוד מסוים. 
לפעמים מישהו נמצא בעמוד 345 ואחרי כמה ימים הוא רוצה להמשיך אז הוא צריך לדפדף כל הדרף עמוד עמוד.

**Comment by Sivan22** [comment]
בתכנון, כבר מופיע כאן. כרגע ניתן לגרור את הלשונית השחורה.

בתאריך יום ב׳, 4 בנוב׳ 2024, 21:01, מאת efratnoi ***@***.***

**Comment by Sivan22** [comment]
Duplicated #97
