### ISSUE TITLE
נוסח הספר עשרה פרקים לרמח"ל

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#32]
שלו' וברכה

הנוסח שבספריא וכן במאגרים התורניים עד החודשים האחרונים - נוסח משובש ומסורס.
העלנו לרשת ב'אוצר הספרים היהודי השיתופי' וב'תא שמע' נוסח מתוקן [שהוא גם מוגה, מפוסק ומנוקד, ומחולק כראוי]
ברשות העורך הרב שמואל וויס שליט"א מהעיר העתיקה תובב"א. 
אנא הביאוהו משם להגדיל תורה ולהאדירה. 
https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%9B%D7%9C%D7%9C%D7%95%D7%AA_%D7%94%D7%90%D7%99%D7%9C%D7%9F_%D7%94%D7%A7%D7%93%D7%95%D7%A9

[וכמדומני שראוי למחוק הנוסח המשובש, ואל תשכן באהליך עולה]
[עשרה פרקים לרמח''ל - מתוקן.txt](https://github.com/Sivan22/otzaria/files/14883272/-.txt)

תודה רבה על המפעל הכביר שחיכינו לו חדשים ארוכים. חפץ ה' בידכם יצליח.

**Comment by Danthig** [comment]
תייגתי את הקובץ המתוקן שהרב @Bshlomecha הביא, לאוצריא, @Sivan22 חשוב שתחליפו במאגר.
[עשרה פרקים לרמחל מוגה.TXT](https://github.com/Sivan22/otzaria/files/14906044/default.TXT)
(מעניין שגיטהב אינם תומכים בקובץ ללא סיומת).

**Comment by Bshlomecha** [comment]
תודה . יישר חילכם לאורייתא.

‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-16:27 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
לתשומת לבך,
@Sivan22

**Comment by Sivan22** [comment]
טופל.

**Comment by Bshlomecha** [comment]
איישר.
האם אוכל לקבלו להוסיפו לתוכנת שברשותי?
האם ישנם עוד עדכונים?

חפץ השי"ת בידכם יצליח, להגדיל תורה ולהאדירה.

‫בתאריך יום א׳, 2 ביוני 2024 ב-8:56 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
תמיד ניתן להוסיף / להסיר ספרים במאגר ידני. 

במחשב המחובר לרשת, ניתן להרשם לקבלת גרסת מפתחים - העדכונים החדשים, אבל עדיין לא יציבים לגמרי, שיכול להיות שהם או התוכנה לא תעבוד כמצופה. 
כעת תוכל להוריד [מכאן](https://github.com/Sivan22/otzaria-dev-channel/releases) ידני את הקובץ האחרון, אם התקנת את התוכנה - שאינך משתמש בגרסה הניידת.

**Comment by Bshlomecha** [comment]
תודה.
התקנתי וכתב שמעדכן.
עכשיו מבקש קוד? היכן אני נרשם ?


‫בתאריך יום א׳, 2 ביוני 2024 ב-10:14 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
זה לא אמור לבקש קוד, אם הוא מבקש קוד, זה בדרך כלל באג בנסיון פתיחת קובץ PDF, כאשר הנתיב של הקובץ השתנה מהפתיחה הקודמת. 
תסגור את המסמך ואחר כך את התוכנה, פתח מחדש ולא אמור לבקש שום קוד בשום שלב.

**Comment by Bshlomecha** [comment]
אכן. תודה.


‫בתאריך יום א׳, 2 ביוני 2024 ב-13:38 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Bshlomecha** [comment]
אם אינה טירחה אנא עזרני:
הוספתי את 'ספרי דיקטה לאוצריא' אבל התוכנה אינה מזהה אלא את התיקיה הראשית
ואת שמות התיקיות. אולי בגלל שאין קישורים מובנים כמו לספרים של התוכנה עצמה?
מצ"ב צילו"ם

נ.בב. ביקשתי את ה'עשרה פרקים' בנוסח המחודש כי חשבתי שטוב להכניסו לאוצריא
שאצלי בגירסתו המקודדת. אם אינה הטרחה אשמח לקבל הקובץ המתוקן.

‫בתאריך יום א׳, 2 ביוני 2024 ב-14:27 מאת שלום איש-שלום <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
הקובץ נמצא כאן למעלה מזה עידן ועידנים https://github.com/Sivan22/otzaria/issues/32#issuecomment-2042758836.
התמונה של מה שמופיע לך בתוכנה לא עלתה. 
לגבי ספרי דיקטה, כנראה שהוא לא נפתח לך משום שהקבצים הם בפורמט ansi, והתוכנה תומכת רק בקבצי txt בפורמט unf8. 
תוכל להוריד את דיקטה בקבצי txt לאוצריא [מכאן](https://did.li/otzaria-).

**Comment by Bshlomecha** [comment]
בס"ד

השלו' והברכה

עדיין אינני מצליח להכליל את *הספרייה של דיקטה *בתוך התוכנה.
מצורפת הסרטה המראה כיצד אני מכניס את התיקייה בשני אופנים:
1. בשם שאני נתתי לה, ואז התיקיות המשניות מזוהות אבל הספרים נעלמיים,
2. בשם המקורי [לכאורה] כמו שקיבלתיה בהורדה, ואז אפילו התיקיות אינן מופיעות
אלא כמו רשימה סתמית [לא במשבצות פעילות בכלל], כמו שנראה ברור בתיעוד.
https://drive.google.com/file/d/1iMCFog7IXffjQzbqkqVC4UYZv-L2OF94/view?usp=sharing
האם צריך להגדיר אחרת?
האם בגלל שאין קישוריות?

האם ישנה עצה ?

ועל הכל אנחנו מודים ומברכים...

*בברכה"ת, ותפילה*

‫בתאריך יום א׳, 2 ביוני 2024 ב-20:36 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
באיזה פורמט הקבצים?
פתח קובץ TXT, ובדוק בשורה למטה מה כתוב:
![image](https://github.com/Sivan22/otzaria/assets/161762042/1b9abe3d-8454-45dc-a391-ed91bce8623f)
אם כתוב utf-8 זה באמת באג. 
אם כתוב ANSI התוכנה אינה תומכת בפורמט זה, כך שלא יעזור שתכניס שוב ושוב...

**Comment by Bshlomecha** [comment]
מצורפת תוצאת הבדיקה.
כתוב utf-8.
זה באמת באג?
איך אף אחד לא התלונן שאינו נפתח?
האם ישנה אפשרות להחיל הגדרות אחרות על תיקיה / תיקיות שלמות של קבצי טקסט ?

תודה.

‫בתאריך יום ד׳, 5 ביוני 2024 ב-13:58 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
לא מצורף שום דבר. 
אם כתוב utf-8 אז זה כנראה באג. 
אתה הראשון שמתלונן שלא נפתח.

**Comment by Danthig** [comment]
בגלל שאתה שולח את זה דרך המייל, אם אתה רוצה שיראו את זה בגיטהב, אתה צריך להכנס לגיטהב, ולגרור / להוסיף את התמונה, ולהמתין עד שיטען התמונה לפוסט.

**Comment by Danthig** [comment]
בגלל שאין לקבצים סיומת כלל. כעת התוכנה משתמשת בקבצים עם סיומת.
 ניתן להוריד את ספרי דיקטה עם סיומת [מכאן](https://did.li/otzaria-).

**Comment by Bshlomecha** [comment]
תודה רבה.


‫בתאריך יום ד׳, 5 ביוני 2024 ב-15:28 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬
