### ISSUE TITLE
שגיאה בהורדת הספריה לאנדרואיד בגירסא החדשה

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#322]
## Describe the bug
![image](https://github.com/user-attachments/assets/f901e3df-d88b-411f-858b-0d46b1a9b29e)

### Environment
 אימולטור WSA, נטפרי

**Comment by mendelg** [comment]
גם אצלי

@Sivan22 
צריך להוסיף הראות אינטרנט.


הוסף

`    <uses-permission android:name="android.permission.INTERNET" />
`
ל Android Manifest

**Comment by Sivan22** [comment]
כן היתה בעיה שחסר גישה לאינטרנט. טיפלתי בזה. עדיין יש בעיה עם החילוץ, כשזה
יסתדר אני אעלה גרסה יותר טובה.

‫בתאריך יום ב׳, 11 בנוב׳ 2024 ב-23:09 מאת ‪mendelg‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
זו בעיה עם תעודת האבטחה, כנראה קשור לנטפרי, כנראה זו בעיה במכשיר שלך ולא
בתוכנה.

‫בתאריך יום ג׳, 12 בנוב׳ 2024 ב-16:01 מאת ‪Refael11‬‏ <‪
***@***.***‬‏>:‬
