### ISSUE TITLE
Out of / too much memory exhaust when extracting the books on Mobile.

### ISSUE THREAD

**Issue by mendelg** [Sivan22/otzaria#324]
## Describe the bug
in the new version, where you can extract the library, it give an error something like "too much memory":

![image](https://github.com/user-attachments/assets/ff666b9c-5f13-4ade-852f-dfa890815faa)

This happened to me on both, IOS and Android.

so, I exited the app and reopened it, but I don't think all files were extracted.

### Steps to reproduce
1. get the latest version.
2. run the app, and download the library. In the middle of extracting, the memory will exhaust. 
### Expected behavior
Should extract all books.
### Environment
- IOS, Android

**Comment by Sivan22** [comment]
related to https://github.com/brendan-duncan/archive/issues/343

**Comment by Sivan22** [comment]
the solution should be moving to https://pub.dev/packages/flutter_archive.
