### ISSUE TITLE
אפשרות עדכון גירסת התכנה ע"י קובץ התקנת עדכון למחשבים שלא מחוברים לרשת

### ISSUE THREAD

**Issue by 0504117825** [Sivan22/otzaria#326]

**Comment by Sivan22** [comment]
כדי לעדכן את גרסת התוכנה עצמה (לא הספרייה) בכל עת להוריד את הגרסה האחרונה (גרסת מפתחים) מהעמוד הבא: https://github.com/Sivan22/otzaria-dev-channel/releases/latest
זהו קובץ שאפשר להעביר אותו לכל מחשב.
לעדכון הספרייה במחשבים שלא מחוברים לרשת צריך להתקין את הגרסה המלאה האחרונה מכאן: https://github.com/Sivan22/otzaria/releases/latest
לחלופין ניתן להוריד רק את הספרייה בלבד מכאן: 
https://github.com/Sivan22/otzaria-library/releases/latest

**Comment by 0504117825** [comment]
כבוד הרב סיון. אני התכוונתי קובץ שיתקין עדכון על התכנה בצורה כזאת שזה לא מתקין מחדש אלא על התכנה הקיימת.
כך שכל ההגדרות והסימניות וההסטוריה וכל ההוספות ושינויים אישיים שנעשו ע"י המשתמש ישארו. כמו כאשר אני עושה עדכון מתוך התכנה במחשב שלי שהוא מחובר לרשת.
תודה רבה רבה!!!

**Comment by Y-PLONI** [comment]
כל התקנת עדכון לתוכנה מוגדרת כעדכון ולא כהתקנה מחדש.
תוכל להסביר?

**Comment by eliahu22** [comment]
הכל בסדר. כבר שברתי את הראש כמה פעמים וכבר הבנתי הכל. חבל להאריך להסביר את כל ההסתבכות שלי..
בכל אופן תודה ל @eliahu22  ולך @Y-PLONI על כל העזרה וההסברים. עזרתם לי מאד מאד. ולא רק לי- לעוד הרבה אנשים!!
אשריכם ואשרי חלקיכם!!
