### ISSUE TITLE
סנכרון הקבצים - האם נצרך? ולמה נתקע?

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#327]
קיבלנו בתודה את המהדורה החדשה, ובכללה יכולת הסנכרון של הקבצים.

שאלתי ובקשתי:
א. האם לאחר עדכון התוכנה צריך לסנכרן הקבצים , או שזה היה כלול?

ב. למעשה לחצתי על סמל הסנכרון, הוחל בעבודה בקצב משמעתי. עתה נתקע בקובץ מספר 669.
מה עליי לעשות?
אם צריך לסדר הקובץ עצמו - איך נסתדר מבחי' ההפרדה?

ג. אני משער שכל מי שעושה סנכרון - מאבד את השינויים בקבצים שערך באופן פרטי, בזהירות המתבקשת.
האם יש לזה פתרון או רק ליצור גיבוי ידני לקבצים ?

**Comment by Sivan22** [comment]
הסנכרון מיועד בעיקר למי שכבר שיש לו ספרייה מעודכנת לעדכן את החידושים שיהיו
מכאן ואילך. לכן מומלץ להוריד את הקובץ
https://github.com/Sivan22/otzaria-library/blob/main/files_manifest.json u
ולשים אותו בתיקייה. או להוריד את כל הספרייה המעודכנת מכאן :
https://github.com/Sivan22/otzaria-library/releases/download/latest/otzaria_latest.zip
הסנכרון לא מוחק את קבצי המשתמש, רק אם יש שינויים בין רשימת הקבצים מהגרסה
הקודמת לגרסה הזו, הוא מסנכרן.

‫בתאריך יום ג׳, 12 בנוב׳ 2024 ב-1:14 מאת ‪Bshlomecha‬‏ <‪
***@***.***‬‏>:‬
