### ISSUE TITLE
יש דרך להכניס את הספריה אופליין באפליקציה?

### ISSUE THREAD

**Issue by MARK-Git-N** [Sivan22/otzaria#329]
בפתיחת האפליקציה לאנדרואיד הוא מציע להוריד את הספריה,
השאלה אם יש נתיב ששם אפשר להכניס את הספריה ידנית בשביל שיקרא את זה, לצורך שימוש אופליין.

**Comment by Sivan22** [comment]
בגרסה הזו לא, משום שזה דורש הרשאות מיוחדות לגישה לקבצי המשתמש, שביטלתי אותם
מסיבות שונות.
תוכל להשתמש בגרסה הקודמת.

‫בתאריך יום ד׳, 13 בנוב׳ 2024 ב-13:55 מאת ‪MARK-Git-N‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
אני עובד כרגע על פתרון למכשירים ללא אינטרנט,

בתאריך יום ד׳, 13 בנוב׳ 2024, 14:31, מאת סיון רצון ***@***.***

**Comment by Bshlomecha** [comment]
> > אני עובד כרגע על פתרון למכשירים ללא אינטרנט, בתאריך יום ד׳, 13 בנוב׳ 2024, 14:31, מאת סיון רצון ***@***.***


> […](#)
אנא ואנא [וסליחה ששוב אני מטרידך באותה בקשה, אבל כיוון שעלה הענין] -
אם תוכל לעבוד על גירסה למכשירים שאי אפשר להתקין בהם אפליקציות
כלומר לנגן אנדרואיד שחסום להתקנת כל אפליקציה שהיא.
אפשר להכניס בו קבצים בלי הגבלה, אבל אם אין אפליקציה משוייכת הוא כמובן לא מזהה ולא מפעיל אותם.
האם יש היתכנות שה'אוצריא' תעבוד בלי שום התקנה?
זו תהיה ברכה גדולה.
ייש"ח לאורייתא [ולאוצריא].

**Comment by Sivan22** [comment]
זה בלתי אפשרי להריץ אפליקציה על מכשיר שחסום להתקנת אפליקציות.

‫בתאריך יום ד׳, 13 בנוב׳ 2024 ב-17:14 מאת ‪Bshlomecha‬‏ <‪
***@***.***‬‏>:‬

**Comment by Bshlomecha** [comment]
שיערתי כך. אבל כיוון שההודעה הרשמית שהמכשיר רושם היא שאי אפשר להתקין אפליקציות ממקור חיצוני מטעמי אבטחה - אולי אפשר להכין את האפליקציה בצורה כזו שהיא לא תהיה בכלל החשש מפני החיצונים... [כלומר שתזוהה כאפליקציה בטוחה וראויה].
אבל באמת יתכן שניסחו את זה כך רק בתור לשון עדינה ולא מחייבת, ואכן אי אפשר להתקין שום אפליקציה חדשה [מה שגורם כמובן לעולם הפוך. שהמכשיר מלא במשחקים מיותרים אבל אינו יכול לשמש לאפליקציות תורניות ושימושיות]...

**Comment by Y-PLONI** [comment]
זה לא רלוונטי.
תנסה לפרוץ את המכשיר או את מה שיש לך שם, זה לא קשור לאוצריא, ולא יכול להיות קשור אליה....

**Comment by Bshlomecha** [comment]
את המכשיר אני לא רוצה לפרוץ. לא סתם קניתי אותו דוקא.
בכל אופן תודה רבה.

‫בתאריך יום ו׳, 15 בנוב׳ 2024 ב-2:16 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬
