### ISSUE TITLE
בעיה בחילוץ חלק מקבצי הספרים

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#33]
בחילוץ הקבצים מתקבלת הודעת שגיאה על קובץ
'ביאורי מהרי קורקוס על משנה תורה הלכות כלי המקדש והעובדים בו'.
כתבתי לו 'דלג' והמשיך חלק. אבל כדאי לתקן קובץ זה ג"כ כמובן.

**Comment by Bshlomecha** [comment]
כך גם :
הגהות מהרם פאדווא על משנה תורה הלכות ביכורים....

חידושים ומקורים של בעל המנחת חינוך על משנה תורה הלכות ציצית, הלכות קריאת שמע, ועוד הרבה....

**Comment by Y-PLONI** [comment]
זה קורה בהרבה קבצים, יש לדווח על זה כבאג, @Sivan22 אנא כווץ את הספרה עם תוכנה פחות מעודכנת.

**Comment by yoseftct** [comment]
גם לי זה קרה בכמה ספרים, למרות שניסיתי גם בווינ' 11 מעודכן, וגם בווינראר מעודכן.

**Comment by Y-PLONI** [comment]
מוזר.
לי זה קרה רק בחלק מהשחרורים.

**Comment by mosh-dvd** [comment]
אולי תנסו עם z7

**Comment by Danthig** [comment]
אני משתמש בתוכנת [bandizip](https://www.bandisoft.com/bandizip/), ולא הייתה לי שום תקלה בחילוץ הקבצים.

**Comment by Refael11** [comment]
הבעיה קיימת גם בגירסא 0.1.6
![DD](https://github.com/Sivan22/otzaria/assets/165617135/11ab3a42-fa46-4101-b3ba-8f558690c15f)

**Comment by Danthig** [comment]
> הבעיה קיימת גם בגירסא 0.1.6 ![DD](https://private-user-images.githubusercontent.com/165617135/320312987-11ab3a42-fa46-4101-b3ba-8f558690c15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MjQ0NTEsIm5iZiI6MTcxMjUyNDE1MSwicGF0aCI6Ii8xNjU2MTcxMzUvMzIwMzEyOTg3LTExYWIzYTQyLWZhNDYtNDEwMS1iM2JhLThmNTU4NjkwYzE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QyMTA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTU3YzRlMTM3MmE4ZjJhNzIzMmZmYjBmYTJlZjRlNGIzMTQyZjYyZmVkZWM1YTJiZTg4OTM2OGVhNzJhOGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dTdptUy1p3qN9LWhL8rHHSzGrpEJjiQbUc5C-SC2QDY)

עם איזה תוכנת חילוץ השתמשת?
תנסה [עם התוכנה הזו](https://www.bandisoft.com/bandizip/).

**Comment by Refael11** [comment]
השתמשתי עם תוכנת WinRar
בכל אופן חייבים לתקן את הבאג כדי שאנשים יוכלו לחלץ עם כל תוכנת חילוץ

**Comment by Bshlomecha** [comment]
בס"ד

שוב תודה על העבודה העצומה. הערתי כמה דברים באתר גיטהאב
כאן אני פונה בבקשה פרטית.

ברשותי מכשיר אנדרואיד כשר, נגן סופר סטאר, שהוא מנותק מן הרשת,
ובנוסף גם חסום להתקנת אפילקציות מלבד מה שכבר מובנה בו מהחברה.

האם ישנה דרך לקבל את אוצריא בתוכנה כזו שאינה צריכה התקנה אלא תפעל על מכשיר
אנדרואיד בלי צורך בקובץ APK?
האם זה חוסר הבנה בסיסי איך עובדות התוכנות?

אשמח לקבל הכוונה.

**Comment by Y-PLONI** [comment]
זה ככל הנראה חוסר הבנה, בכל מקרה זה לא קשור לגיליון הזה שמדבר על נושא אחר לגמרי. @Bshlomecha
