### ISSUE TITLE
קישורים ישירים עם הוראות ברורות להתקנה

### ISSUE THREAD

**Issue by eliahu22** [Sivan22/otzaria#330]
שלום לכבוד הרב  @Sivan22 
אני מתנצל על כל ההטרדות בענין. אבל אני ממש מסתבך עם כל הקישורים הגרסאות והקבצים. ואני ישמח אם תהיה פה הודעה ברורה אחת עם **קישורים ישירים** לכל קבצי ההתקנה המעודכנים ביותר - לכל אפשרויות ההתקנה. למחשב מחובר לרשת / לא מחובר לרשת. - כל מי שיוכל לעזור בענין אודה לו מאד.
לדוג': [קישור ישיר להורדת קובץ לעדכון לגירסת מפתחים האחרונה בווינדוס](https://github.com/Sivan22/otzaria-dev-channel/releases/download/0.2.3-alpha/otzaria-0.2.3-alpha-windows.msix) [- גם זה לא ברור לי אם זה מיועד למחשב שמחובר לרשת או למחשב שלא מחובר לרשת, אבל אפשר לראות שלוחצים על הקישור הזה וזה מתחיל ישירות בהורדה]

מה שהכי חשוב לי:
1. קישורים ישירים להורדת קבצים להתקנת כל התכנה כולה הכי מעודכנת למחשב מחובר לרשת.
2. קישורים ישירים להורדת קבצים להתקנת כל התכנה כולה הכי מעודכנת למחשב שלא מחובר לרשת.
3. קישור ישיר להורדת קובץ לעדכון התכנה עצמה בלבד למחשב שלא מחובר לרשת. [בלי שהגדרות סימניות והסטוריה יפגעו]
4. קישור ישיר להורדת כל הספריה בלבד הכי מעודכנת.
5. קישור ישיר להורדת קובץ לעדכון הספריה בלבד למחשב שלא מחובר לרשת. [בלי שקבצים ושינויים אישיים יפגעו]

מסתמא יש עוד הרבה אופציות ואפשרויות. וכל המוסיף מוסיפין לו.

בסוף עוד לפני כל הבאגים וכו' מה שהכי חשוב זה התכנה עצמה..

אני לא מגזים: יש לפחות "עשרה" אברכים/בחורים שמחכים ומשוועים ומתחננים שאני יתקין/יעדכן להם את התכנה ובכל אחד אני נתקל בבעיה אחרת כי אני מסתבך עם כל הקישורים והקבצים כנ"ל.

תודה רבה רבה!!

נ.ב. הדרך לעשות קישור בטקסט כמו שעשיתי הוא ללחוץ על סימן הקישור בכלי העריכה. הטקסט יוקף בסוגריים מרובעות ומה שצריך זה פשוט להדביק את הקישור המתאים בתוך הסוגריים העגולות. אפשר לראות שזה הצליח בתצוגה מקדימה.

**Comment by Danthig** [comment]
https://mitmachim.top/post/874565

בעז"ה ההמשך יבוא (כרגע אין לי זמן)...

‫בתאריך יום ה׳, 14 בנוב׳ 2024 ב-9:51 מאת ‪0504117825‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
1-2:
https://github.com/Sivan22/otzaria/releases/download/0.2.3/otzaria-0.2.3-windows.exe
3:
https://github.com/Sivan22/otzaria-dev-channel/releases/download/0.2.3-alpha/otzaria-0.2.3-alpha-windows.msix
4:
https://github.com/Sivan22/otzaria-library/releases/download/latest/otzaria_latest.zip
5: כרגע אין כזו אפשרות, צריך להשתמש באפשרות הראשונה.

‫בתאריך יום ה׳, 14 בנוב׳ 2024 ב-9:51 מאת ‪0504117825‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
> ואשמח לדעת על שני האופציות שהבאתם אם זה יעבוד גם במחשב שלא מחובר לרשת.

יש לך טעות בסיסית.
ההתקנה הראשונית היא אותו דר, בין אם יש רשת ובין אם אין.
ההבדל הוא אם יוצאת גרסת תוכנה חדשה, שהתוכנה מציעה עדכון אוטומטי [שאגב, יורד לתיקית הורדות ומותקן משם, הרשת חוסכת רק את ההגעה לגיט וההורדה הידנית...].

יש גם הבדל קטן בספריית הספרים, שלאחר ההתקנה, אם אין רשת הספרייה נשארת סטטית, ואם יש זה מתעדכן.
 מקווה שברור לך.

**Comment by eliahu22** [comment]
@Sivan22 עבודה מושלמת!! אני מוקסם!!
עכשיו תורי להעביר את ההוראות המסודרות למתמחים טופ להשלים את העבודה.
אם תרצה תראה מה שכתבתי לך שם [ע"ש "אשמח לקבל עזרה"] על הנסיונות שעשיתי.
תודה רבה רבה!!
@Y-PLONI אני לא חשבתי שיש הבדל בין אחד לשנים. התכוונתי "לשאול" אם יש הבדל. כי נתקלתי בהרבה בעיות במחשבים חסומים מרשת. ברוךה' עכשיו אחרי מלא נסיונות ובזכות כל העזרה וההסברים שלכם אני חושב שאסתדר עם כל בעיה.
אשריכם!! תודה רבה!!
