### ISSUE TITLE
אופציא להורדת ספר ישירות מהיברובוקס לתוך התוכנה

### ISSUE THREAD

**Issue by Yonahv** [Sivan22/otzaria#331]
## Summary
When finding a sefer on hebrewbooks in the ספריה , In addition to having a direct link to open it on their site, have the option to download the Sefer into Otzaria.
### Basic example
Self explanatory

### Motivation
Lot's of users work offline in Kollel etc. This will give the ability to easily download a Sefer for use later on.

@Sivan22 אין אנחנו מספיקים להודות לך על כל העבודה!

**Comment by 0504117825** [comment]
אני לא כל כך הבנתי מה כתבת באנגלית.
אבל אני תמיד מגדיר בגוגל שיתן לי לבחור את נתיב ההורדה ואז אני פשוט בוחר את הנתיב המדוייק בתוך הספריה של אוצריא וזה מוריד ישירות לשם.

**Comment by Yonahv** [comment]
סליחה אבל לא הבנתי כל כך.
תוכל לפרט יותר?
מה זה אומר מגדיר בגוגל?
הרי אתה פותח את הספר בהיברובוקס ומוריד משם לא?

**Comment by 0504117825** [comment]
יש בגוגל הגדרה שבכל פעם שאתה עושה הורדה הוא פותח לך חלון של סייר הקבצים שתבחר להיכן להוריד את הקובץ.
אכן. פותח בהיברובוקס. לוחץ להורדת הספר. בוחר מיקום. ומאשר. סוגר ופותח את התכנה מחדש וזה עובד.

**Comment by Yonahv** [comment]
אכן ככה אני עושה את זה.
אלא שאם כבר בתוך אוצריה יש אופציא לאתר את הספר, יהיה הרבה יותר נח ללחוץ על כפתור ולהוריד ישירות.

**Comment by 0504117825** [comment]
צודק. והאמת שזה לא מאד מסובך.
צריך רק להוסיף כפתור להורדה ולהגדיר אותו במקום עם הקישור הזה: https://beta.hebrewbooks.org/ ומספר הספר.
עם הקישור הזה: https://download.hebrewbooks.org/downloadhandler.ashx?req= ומספר הספר.
אבל עדיין זה יפתח את הדפדפן.

**Comment by Y-PLONI** [comment]
היה איזה איום מהיברובוקס.
לא נראה שהיה לאיום רגלים, אבל יותר קל להרוס מלתקן, ולא הצלחנו לשכנע את סיון שאין בכך כל רע...

@Sivan22 
כעת אני חושב על רעיון חדש:
שיהיה לחצן הורדה, שיתפח את דף הספר + פקודת הורדה, כך הם לא יוכלו להתלונן. מה אומר?

**Comment by Sivan22** [comment]
הם כתבו לי שהורדה אוטומטית מהאתר שלהם תכביד על המשאבים ותסכן את המשתמשים באתר, והיא מנוגדת לתנאי השימוש באתר. לכן כל מה שיכולנו לעשות זה להפנות לאתר שלהם.
