### ISSUE TITLE
באג רציני בתלמוד בבלי החדש - לא עובד.

### ISSUE THREAD

**Issue by eliahu22** [Sivan22/otzaria#332]
שלום.
יש עוד מישהו שהתלמוד בבלי בגירסה החדשה לא עובד לו כלל?
כשאני פותח טקסט אני מקבל את הדף הזה.
![image](https://github.com/user-attachments/assets/f2becbb6-4492-4816-ba49-23c2cd03030f)

וכשאני פותח PDF את הדף הזה. - דפים לבנים.
![image](https://github.com/user-attachments/assets/a38b3028-89e7-4914-acb7-92e75932a837)

והמעבר מטקסט ל-PDF ולהיפך לא עובד כלל.

נ.ב. ניסיתי לפתוח את הקבצים עצמם. הטקסט נפתח מצויין. וה-PDF נפתח עם דפים לבנים כמו בתכנה.

**Comment by Sivan22** [comment]
זה בגלל נטפרי שמסננים קבצי PDF.

‫בתאריך יום ה׳, 14 בנוב׳ 2024 ב-11:08 מאת אליהו ט. <‪
***@***.***‬‏>:‬

**Comment by eliahu22** [comment]
ולמה הטקסט לא עובד?

**Comment by Bshlomecha** [comment]
אפשר לבקש מהם אישור על תיקיה מסויימת, ולהסביר להם [ויבדקו ויראו שאכן זה כך] שיש שם רק ש"ס.
אולי אפשר בתיקיה מכווצת?

**Comment by Danthig** [comment]
צריך לבקש מנטפרי שלא יסננו כלל את תוכן הספרים, היות והמאגר עומד בדרישות שהם
הציבו, וזה גורם לביטול תורה וכו'.

‫בתאריך יום ו׳, 15 בנוב׳ 2024 ב-0:02 מאת ‪Bshlomecha‬‏ <‪
***@***.***‬‏>:‬

**Comment by mendelg** [comment]
זה קרה לי גם. ואין לי נטפרי...

**Comment by Danthig** [comment]
אז אולי זה קשור לתהליך הדחיסה @סיון22 ***@***.***> ?

‫בתאריך יום ו׳, 15 בנוב׳ 2024 ב-5:38 מאת ‪mendelg‬‏ <‪
***@***.***‬‏>:‬

**Comment by eliahu22** [comment]
איך מתייגים? [באג/בעיה במאגר/הצעה ליעול וכו']

**Comment by Sivan22** [comment]
אני מבין שזה באג, הספרייה בטעות לוקחת את ספרי הPDF במקום את ספרי הטקסט. אני אנסה לבדוק מה אפשר לעשות.

**Comment by eliahu22** [comment]
זה מה שחשבתי מהתחלה. אבל חשבתי ש"מה אני מבין"..
עכ"פ לאחר כמה נסיונות נוספים אני מבין שהתקלה של ה-PDF היא תקלה בפנ"ע בלי קשר לבאג הזה. וזה כנראה באמת בגלל "נטפרי".
גם כשהתקנתי במחשב אחד את כל התכנה ע"י הקובץ החדש שעשית להתקנת כל התכנה ע"י קובץ אחד- גם בזה ה-PDF יוצא דפים לבנים ככל הנראה בגלל נטפרי. מה שעשיתי החלפתי את כל הששה סדרים שבתוך התלמוד בבלי בששה סדרים שמתוך הקובץ הדחוס של הספריה בלבד ששם ה-PDF יצא תקין גם בנטפרי. ואז הכל עובד מצויין- גם המעבר מ-PDF לטקסט ולהיפף עובד מצויין.

רק עדיין אני זקוק לפתרון בשביל המחשב שלי שאני לא רוצה להתקין מחדש וצריך לתקן את הבאג הזה.

נ.ב. לגבי המעבר מ-PDF לטקסט. אני חושב אם בהמשך תוכל לשדרג שזה לא יפתח כל פעם חדש. אלא אם עברתי ל-PDF ולחצתי שוב למעבר לטקסט זה יחזור לפתוח ולא יפתח חדש- מסתמא יותר נח. אולי אפי' שיתחלף באותה כרטיסיה ולא יפתח חדשה בכלל.

**Comment by eliahu22** [comment]
💯💯
רק תיקון אחד קטן: בעיה מס' 1. קיימת גם בתכנית ההתקנה החדשה.
הדרך להתגבר עליה. זה להעתיק את כל הששה סדרים מתוך הקובץ ספריה הדחוס ולהחליף.
