### ISSUE TITLE
בעיה בקבצי פד"ף הדורשים סיסמה

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#333]
כבר קרה בעבר, ואינני זוכר מה יעצו והועילו:

בפתיחת קבצי פד"ף מסויימים [אולי אלו שהוכנסו על ידי המשתמש]
התוכנה מבקשת קוד:
![image](https://github.com/user-attachments/assets/95af0f5a-b448-47cf-89bc-4d8f40213f25)

ואחרי שלוחצים ביטול מופיע עמוד תקלה כזה:
![image](https://github.com/user-attachments/assets/cb3371d9-b609-4ef3-8da0-6e0de87d53ce)

מה נדרש לעשות? האם להתקין רכיב נוסף במחשב שלי? האם להגדיר אחרת את קבצי הפד"ף?

**Comment by motel12** [comment]
אצלי זה קורה רק כשהקובץ לא קיים בספריה והשם נשאר מפעמים קודמות

**Comment by Sivan22** [comment]
בדרך כלל מספיק להפעיל  את התוכנה מחדש.
