### ISSUE TITLE
הוספת תמיכה להורדת או הצגת ספרים מהיברובוקס ואוצר החכמה

### ISSUE THREAD

**Issue by zevisvei** [Sivan22/otzaria#34]
יש לי קובץ אקסל שכולל בתוכו לינקים ישירים להורדת והצגת ספרים מהיברו בוקס, אני חושב שאם יוסיפו בחיפוש ספרים לינק להורדת הpdf במקרה שהספר לא קיים בספריא זה יעזור מאוד.
כמו"כ לגבי אוצר החכמה, רק שכמובן לאוצר החכמה אין הורדה, השאלה היא אם ניתן יהיה להציג תוכן דף אינטרנט בתוך התוכנה.
[היברו בוקס](https://mitmachim.top/assets/uploads/files/1700641976982-%D7%94%D7%99%D7%91%D7%A8%D7%95-%D7%91%D7%95%D7%A7%D7%A1.xlsx)
[אוצר החכמה](https://mitmachim.top/assets/uploads/files/1700186066394-%D7%90%D7%95%D7%A6%D7%A8-%D7%94%D7%97%D7%9B%D7%9E%D7%942.xlsx)
@mendelg

**Comment by Y-PLONI** [comment]
זה רעיון אדיר!
ניתן להשתמש במציג המובנה של ווינדוס לדפי אינטרנט.
אבל לא יהיה בו חיפוש.

**Comment by zevisvei** [comment]
@Y-PLONI לפחות לגבי היברו בוקס ניתן יהיה להוריד את הקובץ ישירות לתוך תיקיית התוכנה וכך יהיה חיפוש

**Comment by Y-PLONI** [comment]
נכון, אך החיפוש יהיה רק לאחר הורדת הקובץ.
אולי ניתן איכשהו לשלב את החיפוש הלא מקוון עם המקוון, נראה לי שזה יצריך פיתוח רציני מדי, אין לי מושג בזה, נצטרך לחכות להכרעתו של סיון (אם הוא יגיע להצעה הזו באלף שנה הקרובות...)

**Comment by zevisvei** [comment]
@Y-PLONI
לשלב את החיפוש הלא מקוון עם המקוון זה לא כזה מסובך, סה"כ צריך לשחק קצת עם כתובת הurl

**Comment by Sivan22** [comment]
אני מקווה בעתיד לשלב את זה. זה רעיון טוב. בינתיים @אביי עובד להשיג רשימה של הספרים עם המטא-דאטה שלהם. כי שם לבד זה לא מספיק.

**Comment by Y-PLONI** [comment]
יש את זה כבר! @zevisvei תוכל להעלות?
יעזור לך, @Sivan22 ???

**Comment by zevisvei** [comment]
> אני מקווה בעתיד לשלב את זה. זה רעיון טוב. בינתיים @אביי עובד להשיג רשימה של הספרים עם המטא-דאטה שלהם. כי שם לבד זה לא מספיק.

אולי זה יעזור:
https://github.com/david-lev/hebrewbooksbot

**Comment by Sivan22** [comment]
שם זה חיפוש מקוון ממש, דרך API של האתר שלהם. אני חשבתי על כיוון של מסד נתונים מקומי עם כל שמות הספרים ושאר הנתונים, כולל תמונה ממוזערת. בכל אופן אני אבדוק בעזרת ה' את כל הכיוונים.

**Comment by zevisvei** [comment]
@Sivan22 אני התכוונתי שאולי ניתן לגשת ל API של היברו בוקס באותה צורה שהבוט ניגש
אגב העליתי  [כאן](https://github.com/Sivan22/otzaria-library/tree/main/books%20lists) כמה אקסלים עם המטא-דאטה של היברו בוקס, אולי אחד מהם יעזור.

**Comment by Y-PLONI** [comment]
> @Sivan22 אני התכוונתי שאולי ניתן לגשת ל API של היברו בוקס באותה צורה שהבוט ניגש אגב העליתי [כאן](https://github.com/Sivan22/otzaria-library/tree/main/books%20lists) כמה אקסלים עם המטא-דאטה של היברו בוקס, אולי אחד מהם יעזור.

אם אתה רוצה שהפוסט יוצג בצורה תקינה, עליו להתחיל בתווים עבריים, ולא בתיוג

**Comment by mendelg** [comment]
@zevisvei 
הלינק להיברובוקס
https://mitmachim.top/assets/uploads/files/1700641976982-%D7%94%D7%99%D7%91%D7%A8%D7%95-%D7%91%D7%95%D7%A7%D7%A1.xlsx
אינו תקין
