### ISSUE TITLE
בעיה באיתור - הטקסט בחלון נשאר גם לאחר מעבר לחלון אחר

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#340]
כתבתי באיתור ברכות דף ב - לדוגמא, מצאתי, עברתי לשם, ואז חזרתי לחלון איתור כדי לאתר משהו אחר והטקסט "ברכות דף ב" עדיין שם, 
מה שאומר שצריך כל פעם למחוק ואז להקליד טקסט חדש

מדובר אגב בבעיה שנוצרה מאז הגירסא החדשה 0.2.3

**Comment by Y-PLONI** [comment]
אולי זו מעלה?
ככה זה עובד גם בבראילן.

**Comment by Danthig** [comment]
לי קרה באג שבלחיצה על DELET או BACKSPACE החיפוש הקודם ב'איתור' לא נמחקו,
והייתי צריך למחוק אותם עם הX שבסוף השורה!

ואם כבר עושים שישאר טקסט החיפוש הקודם, אז שהטקסט יהיה בחור (מוכחל), כך
שבאיתור חדש, זה ימחק את הקודם, ורק בלחיצה על חץ ימינה / שמאל, או עם העכבר
אני יוכל להוסיף על הכתוב.
כמו בבר אילן, ובאוצר החכמה המקוון...

‫בתאריך יום ה׳, 21 בנוב׳ 2024 ב-23:02 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
הפתרון הוא אכן להדגיש את הטקסט. מופיע כבר ב #188
