### ISSUE TITLE
באנדרואיד F22 פרו כשנמצא על מצב חיפוש או איתור המקלדת נדלקת ונכבית כל הזמן, ואין אפשרות לכתוב כלום

### ISSUE THREAD

**Issue by israelsky** [Sivan22/otzaria#347]
## Describe the bug | תיאור הבאג
תיאור מפורט וברור שמגדיר מהו הבאג

### Steps to reproduce | צעדים לשחזור
Steps to reproduce the behavior.
כיצד ניתן לשחזר שוב את הבאג?

### Expected behavior | התנהגות צפוייה
תיאור ברור של מה שמצופה מהתוכנה לעשות.

### Environment | סביבה 
 - OS | מערכת הפעלה: [e.g. Arch Linux]
 - version | גרסת התוכנה:

**Comment by Sivan22** [comment]
נפתר ב #350

**Comment by israelsky** [comment]
הבעיה נפתרה רק חלקית שהמקלדת לא משתוללת. אבל עדיין אין אפשרות לכתוב כלום, כי המקלדת נסגרת מיד
