### ISSUE TITLE
עדכון חדש?

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#348]
@Sivan22 

קיבלתי הודעה דרך התוכנה על עדכון חדש זמין.
גם הוא ממוספר 0.2.3
האם זה שאין לו הגדרה alfa משנה משהו?

כעת אני רואה שגם אחרי התקנה חדשה הוא כותב לי 'עדכון זמין', ואם כן אין לדבר סוף...

וגם ב'הגדרות' עדיין מסומן 'אלפא'
[או בגלל שלא מחקתי את הגירסה הקודמת, וכמו שהוא לוקח את הספרים משם. 
_באמת איך הוא עושה את זה?_]

**Comment by Bshlomecha** [comment]
כעת אני רואה שגם אחרי התקנה חדשה הוא כותב לי 'עדכון זמין', ואם כן אין לדבר סוף...

**Comment by Sivan22** [comment]
תודה על הדיווח, בגלל ששוחררה גרסה יציבה, אז גם מי שרשום לגרסאות בדיקה קיבל הודעה, למרות שהוא יותר מעודכן. צריך לתקן את זה
