### ISSUE TITLE
רוחב משתנה של פנל ניווט

### ISSUE THREAD

**Issue by David-1684** [Sivan22/otzaria#351]
רוחב של פנל הניווט ניתן לשינוי ע"י גרירה, להתאמה טובה יותר, ויותר נוחה.
כמו כן מצב 'פין' (נעיצה) יכול על כל המסמכים באופן אוטומתי, בלי צורך להגדיר את זה לכל מסמך בנפרד (לפחות כאופציה בהגדרות).
![צילום מסך 2024-12-01 094322](https://github.com/user-attachments/assets/fd9e44ef-a9f0-49d7-a848-0fc2ae5144f7)

**Comment by IEUDI1** [comment]
אני גם חושב שזה דברים מאד חשובים, לי אישית יועילו מאד מאד, בפרט הנעיצה הקבועה של תפריט הניווט.

**Comment by Y-PLONI** [comment]
כפול:
https://github.com/Sivan22/otzaria/issues/85
