### ISSUE TITLE
הגדלת הפונט באמצעות צביטה

### ISSUE THREAD

**Issue by Sivan22** [Sivan22/otzaria#36]
מומלץ שתהיה אפשרות להגדיל ולהקטין את הפונט באמצעות מחווה של צביטה (זום) במסכים שתומכים במגע.

**Comment by Danthig** [comment]
וכן על ידי צביטת לוח מגע (במחשבים ניידים).

**Comment by Sivan22** [comment]
הפונקציה נוספה בגרסה 0.1.7 אבל מאד קשה למצוא את התנועה המדוייקת.

**Comment by Danthig** [comment]
> הפונקציה נוספה בגרסה 0.1.7 אבל מאד קשה למצוא את התנועה המדוייקת.

במסך עצמו זה עובד מצויין, רק בלוח מגע מסובך...
יישר כוחך!!!
