### ISSUE TITLE
איתור מקורות ויצירת קישורים באופן אוטומטי

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#360]
עליית מדרגה גדולה יכולה להיות אם אפשר לכלול בתוכנה גם **מנוע המאתר ציונים ומראי מקומות**,
שתפעל לתרי גיסי:

**א. למצוא ציונים ומראי מקומות**, כמו ב'איתור' , למשל 'שבת קלג, ב' ולהפוך אותו לקישור.

**ב. למצוא ציטוטים ומובאות** ולציין עליהם מקור [מעין מה שיש בדיקטה, אבל שיעבוד בצורה מקומית על החומר שיש בתכונה עצמה],
כגון אם היה כתוב "שמע ישראל ה' אלקינו ה' אחד" יציין עליו (דברים ו).
ואם ימצא כתוב 'מאימתי קורין את שמע בערבין' - יציין עליו (ברכות פ"א) או (ברכות ב, א).
= להרחיב תכונה זו אפשר אם ימצא גם מובאות שאינן מדוייקות, ויציין המקור האפשרי, וגם יציע הגהה.... [במיוחד אם יהיה משולב בינה מלאכותית...]

**Comment by Y-PLONI** [comment]
זה נחמד מאוד, ובגדר הדמיוני...
יש כמה 'דברים קטנים' לפני...

**Comment by Danthig** [comment]
זה לא כזה דמיוני, (לכל הפחות חלק), סיון כתב היכן שהוא, שבספריא יש כזה דבר,
ואולי ישנה היתכנות שזה מתי שהוא ייכנס לאוצריא!
אגב, תראה את המראי מקומות שבאוצר החכמה, לדעתי זה לא כל כך שונה מקישור טקסט
לPDF שכבר קיים בתוכנה! רק הרבה יותר עבודה.

‫בתאריך יום ה׳, 5 בדצמ׳ 2024 ב-21:03 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
הפיתוח של דבר כזה חורג מגבולות התוכנה כרגע. אבל זה בהחלט מעסיק ומעניין. מי
שפעילים יותר בזה הם ארגון דיקטה. דיברנו איתם וזה אכן אחד הנושאים שהם עובדים
עליהם כרגע. אם זה יהיה בשל וישוחרר לציבור נוכל לשקול להטמיע את זה בתוכנה.
ואגב, אוצר החכמה זו הראייה שהכלי עוד לא בשל.

בתאריך יום ו׳, 6 בדצמ׳ 2024, 08:30, מאת Danthig ***@***.***>:

**Comment by Bshlomecha** [comment]
כתב  @Sivan22:
> הפיתוח של דבר כזה חורג מגבולות התוכנה כרגע. אבל זה בהחלט מעסיק ומעניין. מי שפעילים יותר בזה הם ארגון דיקטה. 

ברוך שכיוונתי  לדבריו כשכתבתי לעיל:
> ב. למצוא ציטוטים ומובאות ולציין עליהם מקור [מעין מה שיש בדיקטה, אבל שיעבוד בצורה מקומית על החומר שיש בתכונה עצמה],

אצל זה עובד יפה מאוד. יכול להיות שזה דורש מנוע עיבוד כמו שיש להם ולא יכול לעבוד אופליין? 
אולי עכ"פ זה יעבוד כאשר ה'אוצריא' מחובר לרשת? [מאידך אני מבין שהמטרה להעמיד תוכנה שמשמשת את האברכים, ואם חלק מהתכונות תהיינה תלויות־חיבור זה מאבד את הריכוז בעיקר...].
