### ISSUE TITLE
תמיכה בהערות שוליים בגירסה החדשה 0.2.4 אופן הצגת ההערות

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#361]
התמיכה בהצגת הערות שוליים - חשובה ומועילה מאוד.
יש אולי מקום לשקול אם להגדיר אותן כמו טקסט מפרשים, שאפשר להציג ולהעלים.
[למרות שהם מתוך הקובץ עצמו ולא קובץ אחר מקושר כמובן].
זה יקל על הקריאה הרציפה, במיוחד כשיש הערות ארוכות.
וזו תהיה בשורה בכלל לכל האופן של טיפול במסמכים בעלי הערות, גם בתוכנות כמו אופיס וכד'...

**Comment by Bshlomecha** [comment]
הערה נוספת באותו ענין, במה שהתמיכה בהערות אינה מושלמת: 
כאשר יש באותה שורה שתי הערות - הוא מחליף המספרים, מצורפת תמונה.

![image](https://github.com/user-attachments/assets/a2bd5e8c-01cd-4228-bd7d-b849b5f9203d)

**Comment by Sivan22** [comment]
כרגע זה קשה טכנית לביצוע, ובשביל האפשרות הזו נדרש הכלי "וורד לאוצריא" שיוצר קבצים מקושרים. לגבי הבאג, זה בספרייה התומכת ולא בקוד שלי, אז כרגע זה לא בתכנון.

**Comment by Bshlomecha** [comment]
תודה על הדיוק.
שבת שלו'.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
ללא
וירוסים.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום ו׳, 6 בדצמ׳ 2024 ב-12:58 מאת ‪Sivan Ratson‬‏ <‪
***@***.***‬‏>:‬

**Comment by motel12** [comment]
> בשביל האפשרות הזו נדרש הכלי "**וורד לאוצריא**" שיוצר קבצים מקושרים. 

איפה משיגים אותו?

**Comment by Bshlomecha** [comment]
ספריית דיקטה להורדה עבור אוצריא – Google Drive
<https://drive.google.com/drive/folders/1Sqj3sCyYJnVB60KAZxgmDNO7x52qoVm6>
עיי"ש ותשכח.

‫בתאריך יום א׳, 8 בדצמ׳ 2024 ב-20:19 מאת ‪motel12‬‏ <‪
***@***.***‬‏>:‬
