### ISSUE TITLE
i tried download and it says "can not download needs authorization"

### ISSUE THREAD

**Issue by Goodman3177** [Sivan22/otzaria#363]

**Comment by Y-PLONI** [comment]
עדיין לא הסתדרת?

**Comment by Goodman3177** [comment]
ניסיתי אולי חמש פעמים ומוריד ואחרי כשעה אני מקבל תגובה הנל
תודה
Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602  S. Magnolia  St. Denver CO
80224
Zelle: ***@***.***
PP:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927

**Comment by Y-PLONI** [comment]
מהיכן ניסית להוריד?

**Comment by Goodman3177** [comment]
מזה Sent from Mail for Windows From: Y-PLONISent: Thursday, December 5, 2024 11:32 PMTo: Sivan22/otzariaCc: Goodman3177; AuthorSubject: Re: [Sivan22/otzaria] i tried download and it says "can not download needs authorization" (Issue #363) מהיכן ניסית להוריד?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Y-PLONI** [comment]
לא הבנתי את התגובה שלך.
את אוצריא מורידים מכאן:
https://github.com/Sivan22/otzaria/releases/download/0.2.3/otzaria-0.2.3-windows.exe

**Comment by Goodman3177** [comment]
תודה הורדתי עכשיו איך פותחים ומתקינים אוצריה? Sent from Mail for Windows From: Y-PLONISent: Friday, December 6, 2024 1:25 AMTo: Sivan22/otzariaCc: Goodman3177; AuthorSubject: Re: [Sivan22/otzaria] i tried download and it says "can not download needs authorization" (Issue #363) לא הבנתי את התגובה שלך.את אוצריא מורידים מכאן:https://github.com/Sivan22/otzaria/releases/download/0.2.3/otzaria-0.2.3-windows.exe—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Bshlomecha** [comment]
המערכת שלך שולחת את כל המעטפת של ההגדרות ובתוכה נעלם המשפט הפשוט שרצית לומר:
> -->תודה הורדתי עכשיו איך פותחים ומתקינים אוצריה?

תנסה לסדר את זה.
אם הורדת קובץ הפעלה [exe] ואתה פותח אותו - הוא אמור לעשות את כל העבודה.

**Comment by Goodman3177** [comment]
שבוע טוב
לא עשה את העבודה!
Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602  S. Magnolia  St. Denver CO
80224
Zelle: ***@***.***
PP:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927

**Comment by YOSEFTT** [comment]
אם תרצה שליטה מרחוק, אוכל לעזור לך בל"נ

‫בתאריך שבת, 7 בדצמ׳ 2024 ב-18:21 מאת ‪Goodman3177‬‏ <‪
***@***.***‬‏>:‬

> שבוע טוב
> לא עשה את העבודה!
> Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602 S. Magnolia St. Denver CO
> 80224
> Zelle: ***@***.***
> PP:
>
> https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
> IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927
>

**Comment by Y-PLONI** [comment]
@Goodman3177 
בשביל שמישהו יוכל לעזור לך, תצטרך להסביר מה זה "לא עשה את העבודה".

**Comment by Goodman3177** [comment]
הורדתי התוכנה למחשב .
אבל לא נתקן לבד.
Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602  S. Magnolia  St. Denver CO
80224
Zelle: ***@***.***
PP:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927

**Comment by Y-PLONI** [comment]
אני מבקש שתסביר, אין לי כח לשאול אותך שוב ושוב.
הורדת את התוכנה, לחצת פעמיים על קובץ ההתקנה, ומה קרה? כלום?

**Comment by Goodman3177** [comment]
לחצתי פעמים על קובץ ההתקנה הקובץ נפתח לקובץ קריא באנגלית אבל האוצריה לא נתקנתתודה Sent from Mail for Windows From: Y-PLONISent: Saturday, December 7, 2024 8:24 PMTo: Sivan22/otzariaCc: Goodman3177; MentionSubject: Re: [Sivan22/otzaria] i tried download and it says "can not download needs authorization" (Issue #363) אני מבקש שתסביר, אין לי כח לשאול אותך שוב ושוב.הורדת את התוכנה, לחצת פעמיים על קובץ ההתקנה, ומה קרה? כלום?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Y-PLONI** [comment]
אני לא מבין אותך.
אני יכול רק להציע שליטה מרחוק.

**Comment by Goodman3177** [comment]
תודה
נשלח מייל מחר אחה"צ
לקבוע מתי טוב לכם.
Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602  S. Magnolia  St. Denver CO
80224
Zelle: ***@***.***
PP:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927

**Comment by Y-PLONI** [comment]
מחר יהיה מאוחר, כדאי כעת [אח"כ בע"ה אתנתק מהרשת עד ליל שישי, בל"נ]

**Comment by Goodman3177** [comment]
הבנתי כבודו פנוי עכשיו
Cong. Sfat Temmim| c.o. Rabbi AD Karno| 602  S. Magnolia  St. Denver CO
80224
Zelle: ***@***.***
PP:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GRLBYV6D4KMJN&source=url
IL:https://www.matara.pro/nedarimplus/online/?mosad=7006927

**Comment by Y-PLONI** [comment]
כן. תן מזהה אנידסק

**Comment by Y-PLONI** [comment]
@Goodman3177 
???

**Comment by Goodman3177** [comment]
שלום ושבוע טוב.
אני הורדתי תוכנת אוצריא במחשב אחד ומאוד נהנה ממנו הוא ממש מצוין


ניסיתי במחשב שני הוא מוריד אבל לא נפתח להתקין.
יש אולי עצה או פתרון?
תודה רבה

**Comment by Danthig** [comment]
תגדיר מה בדיוק קורה?

אם המחשב השני הוא ישן בעל 32 סיביות, אז אוצריא לא תעבוד בו.

‫בתאריך שבת, 27 בדצמ׳ 2025 ב-20:10 מאת ‪Goodman3177‬‏ <‪
***@***.***‬‏>:‬

**Comment by Goodman3177** [comment]
תודה אני יבדוק ויחזור
