### ISSUE TITLE
הוספת ספרים למאגר

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#37]
אם אתה מעונין שנשווה את המאגר של 'אוצריא' עם 'תורת אמת' ו'דיקטה', ונבדוק איזה ספרים קיימים בהם שאין ב'אוצריא'? נשמח מאוד כולנו לעשות את זה.

כמו"כ, האם אתה מעוניין שלמי שיש קבצי טקסט של ספרים ללא זכויות יוצרים, או עם זכויות אבל באישור בעלי הזכויות, שיעביר לך?
א"כ כדאי שתפרסם ב'מתמחים', הרבה ישמחו לשתף איתך פעולה בנושא.
כמובן שצריך להגדיר איזה ספרים אתה מעוניין שיכנסו [מחברים מדורנו, מחקר, וכו'].

אני מכיר טוב מישהו שהו"ל ספר של אחד מהראשונים, ואני יכול לשכנע אותו להעביר את הטקסט למאגר. כמובן שככל שהמאגר של התוכנה יהי' יותר גדול, זה ותר ישכנע אנשים להעביר ספרים למאגר.

אולי כאן אפשר למצוא הרבה ספרים נוספים,
https://torah-munachat.netlify.app/

**Comment by Y-PLONI** [comment]
@Sivan22 ???

**Comment by Sivan22** [comment]
אשמח לרשימה של ספרים מ"תורת אמת".
 מדיקטה בינתיים קשה לי להמיר, זה הרבה עבודה ידנית. (מי שרוצה להשתמש בקידודון של @pcinfogmach לתורת אמת, ולהמיר ספרים של דיקטה לתורת אמת, אחר כך יהיה קל יותר להמיר לאוצריא.)
למעשה כל ספר שיגיע בפורמט נוח להוספה אפשר להוסיפו, אבל לעתים נדרשת עבודה להתאים, אז ספרי יסוד קודמים.

**Comment by yoseftct** [comment]
בשביל זה נצטרך רשימה מסודרת בקובץ אקסל שיהי' קל לבדוק.

**Comment by zevisvei** [comment]
[BooksConfig.txt](https://github.com/Sivan22/otzaria/files/14906305/BooksConfig.txt)
[BooksList.txt](https://github.com/Sivan22/otzaria/files/14906306/BooksList.txt)
[Config.txt](https://github.com/Sivan22/otzaria/files/14906307/Config.txt)
מתיקיית ההתקנה של תורת אמת

אולי ל @pcinfogmach יש רשימה יותר מסודרת

**Comment by Y-PLONI** [comment]
העבודה על תורת אמת החלה:
https://github.com/Sivan22/otzaria/issues/62
העבודה על דיקטה החלה:
https://mitmachim.top/post/774464

**Comment by Y-PLONI** [comment]
מקור: https://mitmachim.top/post/775746
הוספת: http://books.613m.org/1
מקור: https://mitmachim.top/post/775997
הוספת: https://mobile.tora.ws/
ממויין כאן: https://mitmachim.top/post/712925 יש הלאה שם.

**Comment by Danthig** [comment]
לגבי אוצר הספרים היהודי, https://github.com/Sivan22/otzaria/issues/62#issuecomment-2050428259 עד כמה שידוע לי הספרים שם אינם ברשיון חופשי לשימוש מסחרי, אבל יכול להיות שהם יסכימו כמו שהם הסכימו לתוכנת סטנדר ז"ל.
זה האימייל ליצירת קשר WikiJewishBooks@Gmail.com.

**Comment by Bshlomecha** [comment]
עוד ראיתי להציע [אם כי מסתבר שחשבו על זה מעצמם, אבל לא ראיתי שהזכירו זאת]
לקחת גם מאוצר הספרים היהודי השיתופי - https://wiki.jewishbooks.org.il/mediawiki/wiki/%D7%90%D7%95%D7%A6%D7%A8:%D7%A1%D7%A4%D7%A8%D7%99%D7%9D_%D7%A7%D7%99%D7%99%D7%9E%D7%99%D7%9D
ולכאו' גם מארון הספרים היהודי שב'ויקטיקסט' -https://he.wikisource.org/wiki/%D7%95%D7%99%D7%A7%D7%99%D7%98%D7%A7%D7%A1%D7%98:%D7%90%D7%A8%D7%95%D7%9F_%D7%94%D7%A1%D7%A4%D7%A8%D7%99%D7%9D_%D7%94%D7%99%D7%94%D7%95%D7%93%D7%99
איני בקיא בתנאים ובהגבלות המשפטיות וכו'. אבל לכאורה יש שם הרבה טוב, בן מצד התוכן והן מצד הצורה.
הנני מצרף דוגמא לאיכות העימוד והקישורים:

[מקרא.pdf](https://github.com/Sivan22/otzaria/files/14950794/default.pdf)

פרטים נוספים: https://he.wikisource.org/wiki/%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9:Dovi/%D7%9E%D7%A7%D7%A8%D7%90_%D7%A2%D7%9C_%D7%A4%D7%99_%D7%94%D7%9E%D7%A1%D7%95%D7%A8%D7%94#%D7%A8%D7%90%D7%A9
