### ISSUE TITLE
הכללת מאגרים נוספים שקיימים אצל המשתמש

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#371]
בקשה מחוץ לקופסה [כמשמעו...]

האם ישנה אפשרות - למי שיש ברשותו תוכנה חוקית ומאושרת - [כגון התקליטור התורני **DBS** וכיו"ב]
ליצור חיבור ו**לכלול את תוכן המאגרים הללו בתוכנה הנפלאה של אוצריא** ?

החלום הכללי הוא שיהיה אפשר לעשות חיפוש אחד בכל המאגרים התורניים גם יחד
[כן, כולל בר־אילן ואוצר החכמה...], ולקבל רשימה מסודרת עם קישור לתוכנה המתאימה..
אבל בינתיים - האם הבקשה שלי היא מעבר לאופק?

**Comment by Y-PLONI** [comment]
יש פה 2 בקשות שונות:
1. שיראו באוצריא את תוכן המאגרים: לא אפשרי, הם קידדו את זה בצורה שאיש לא יוכל להעתיק...
2. 2. חיפוש במאגרים הנ"ל: יתכן, אולי ואולי, שניתן לפתוח את אוצה"ח עם פקודת חיפוש. לא יותר, וגם זה נראה חסר טעם.

**Comment by Bshlomecha** [comment]
אם כדבריך - שזה יועיל רק לפתוח את אוצה"ח - זה אכן חסר טעם לחלוטין.
מה שעלה בדעתי רק אם ואולי אפשר לגשת לאינדקס של המאגרים ההם, אבל אני מבין
מדבריך שזה בלתי אפשרי.

‫בתאריך יום א׳, 8 בדצמ׳ 2024 ב-18:07 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬
