### ISSUE TITLE
קישורים בין טקסט לבין ספר המקור

### ISSUE THREAD

**Issue by yosef123660** [Sivan22/otzaria#377]
כיצד יוצרים קישורים בין טקסט של פירוש לבין ספר המקור?

**Comment by Y-PLONI** [comment]
לפי הבלוקים.
לא נראה לי שאפשר לעשות ידנית יותר מאחד-שתיים.
אבל אם יש לך בוורד, @Sivan22 כתב תוכנה שעושה את זה אוטומטית.

**Comment by yosef123660** [comment]
thank you, can tou post the exact link?

**Comment by Y-PLONI** [comment]
https://drive.google.com/drive/folders/1Sqj3sCyYJnVB60KAZxgmDNO7x52qoVm6
תוכנת "וורד לאוצריא"
