### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by zmanjnr** [Sivan22/otzaria#378]
can you update newest release for macos too? thanks

**Comment by Sivan22** [comment]
try downoading from here: https://github.com/Sivan22/otzaria/actions/runs/12242095855/artifacts/2295626921

**Comment by zmanjnr** [comment]
> try downoading from here: https://github.com/Sivan22/otzaria/actions/runs/12242095855/artifacts/2295626921

hi just saw this, but link is down? thanks

**Comment by zmanjnr** [comment]
0.2.3 Auto Sync
doesnt have macOS there by assets thanks

**Comment by Sivan22** [comment]
Just added.

**Comment by zmanjnr** [comment]
thanks, got it, however i cant open it after i download it - the otzaria screen is black on the update, any idea? thanks

**Comment by Sivan22** [comment]
Try to uninstall the old version, and make sure the settings file is
deleted. (Search for bookmarks.isar and delete all files in the directory)

בתאריך יום ד׳, 15 בינו׳ 2025, 04:27, מאת zmanjnr ***@***.***
