### ISSUE TITLE
פתיחת שתי ספרים במקביל

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#38]
אני חושב שיהי' תועלת אם יהי' אפשרות לפתוח שתי ספרים במקביל [לאורך או לרוחב], כמו שיש בתורת אמת. [הם קוראים לזה בתוכנה שלהם - שתי דפדפנים].

אמנם גם כרגע אפשר לעשות את זה ע"י פתיחת התוכנה בשתי חלונות שונים, אבל ההבדל רב, כמובן.

**Comment by yisrael-rosen** [comment]
@yoseftct 
איך זה אמור לעבוד בפועל? אפשרות לאיחוד כרטיסיות?

**Comment by yoseftct** [comment]
לא הבנתי השאלה, אבל אם אתה רוצה לראות תמונה מ'תורת אמת', 
הנה:
![צילום מסך 2024-04-08 002532](https://github.com/Sivan22/otzaria/assets/115775588/44aa5717-f02c-43d6-8a69-743e3381dada)

**Comment by yisrael-rosen** [comment]
לא מכיר תורת אמת.
הבנתי איך אמור להראות מסך מפוצל
אני רוצה שתתאר בפועל איך פותחים 2 כרטיסיות
אם פתחתי גמ' ברכות דף ג: ואני עכשיו רוצה לראות במקביל שו"ע יו"ד סעיף א'
מה השלבים הנדרשים מהמשתמש לעשות כדי להגיע למצב הזה?

**Comment by Danthig** [comment]
> לא מכיר תורת אמת. הבנתי איך צריך להראות מסך מפוצל אני רוצה שתתאר בפועל איך פותחים 2 כרטיסיות אם פתחתי גמ' ברכות ג: ואני עכשיו רוצה לראות את הדף שו"ע יו"ד סעיף א' מה השתלמות מהמשתמש לעשות כדי להגיע למצב הזה?

צריך שהפוקוס יהיה על החלונית הרצויה, ובבחירת ספר, הוא נפתח בחלונית הזו. ניתן לפתוח מספר ספרים (שנפתחים בתוכנה כטאבים), בכל חלונית בנפרד. 
![image](https://github.com/Sivan22/otzaria/assets/161762042/cf36d9ee-5a1c-4acb-99f3-026792eb1f93)
אגב, השינוי של זה הוא על ידי לחיצה במסך הבית (למעלה בצד שמאל) כמו שהצעתי [כאן](https://github.com/Sivan22/otzaria/issues/51#issue-2231119115).

**Comment by yisrael-rosen** [comment]
משהו כזה?
(הדוגמה עם PDF כי בספר רגיל זה קורס ולא יודע איפה לשים את הפוקוס)
![image](https://github.com/Sivan22/otzaria/assets/57872424/79d2b07c-0725-4e0a-a868-b794d71b4b95)
![image](https://github.com/Sivan22/otzaria/assets/57872424/c8284c5a-a8e0-46aa-a98b-0c676f973ea7)

**Comment by Danthig** [comment]
כן!
יישר כוחך!!!

**Comment by yisrael-rosen** [comment]
נראה שיקח זמן לפתח את זה בצורה יציבה
צריך לקחת בחשבון את כל ההשלכות מפיצול כזה
אבל נראה לי שכדאי להכניס את זה לרשימה לפיתוח
@Sivan22 מה דעתך בעניין?

**Comment by yoseftct** [comment]
לא ממש הבנתי מה התקשית כאן, האם רצית לדעת איך בדיוק 'תורת אמת' עשו את זה, אני לא מבים בתכנות. ואם רצית לדעת איך זה נראה, דהיינו בממשק משתמש, אז כבר הראתי לך צילו"מ.
בכל אופן מה שדאנציג העלה זה רק 2 טאבים. אני מדבר על 2 חלונות ממש.

אני מעלה כאן הסרטת מסך שעשיתי. תראה ותבין.
[הקלטת תורת אמת.zip](https://github.com/Sivan22/otzaria/files/14915855/default.zip)

**Comment by yisrael-rosen** [comment]
> לא ממש הבנתי מה התקשית כאן, האם רצית לדעת איך בדיוק 'תורת אמת' עשו את זה, אני לא מבים בתכנות. ואם רצית לדעת איך זה נראה, דהיינו בממשק משתמש, אז כבר הראתי לך צילו"מ. בכל אופן מה שדאנציג העלה זה רק 2 טאבים. אני מדבר על 2 חלונות ממש.
> 
> אני מעלה כאן הסרטת מסך שעשיתי. תראה ותבין. [הקלטת תורת אמת.zip](https://github.com/Sivan22/otzaria/files/14915855/default.zip)

רציתי שיסבירו ברחל בתך הקטנה מה רוצים שיהיה
כמו שמסבירים להודי שהרגע נחת כאן ומעולם לא ראה צורת ספר.
ובמילים בהסרטה רואים שאפשר ליצור 2 סביבות עבודה ו**לגרור** טאבים מסביבה לסביבה 
והסביבות עבודה יכולים להיות במאונך או במאוזן
קשה להבין את כל זה מהתיאור הראשוני
> אני חושב שיהי' תועלת אם יהי' אפשרות לפתוח שתי ספרים במקביל [לאורך או לרוחב], כמו שיש בתורת אמת. [הם קוראים לזה בתוכנה שלהם - שתי דפדפנים].

**Comment by YOSEFTT** [comment]
אני לא יודע אם זה ממש אותו פיתוח או משהו חדש, תודיע לי אם לדעתך צריך לפתוח ע"ז נושא חדש.

רציתי להציע [בלי קשר ישיר לנקודה הקודמת] שיהי' אפשר להזיז סימניות ימינה ושמאלה, כמו שרואים בהסרטה בתוכנת תורת אמת.
[זה מאוד שימושי לי. וזכור לי שמישהו כבר הציע את זה במתמחים טופ].

**Comment by yisrael-rosen** [comment]
> אני לא יודע אם זה ממש אותו פיתוח או משהו חדש, תודיע לי אם לדעתך צריך לפתוח ע"ז נושא חדש.
> 
> רציתי להציע [בלי קשר ישיר לנקודה הקודמת] שיהי' אפשר להזיז סימניות ימינה ושמאלה, כמו שרואים בהסרטה בתוכנת תורת אמת. [זה מאוד שימושי לי. וזכור לי שמישהו כבר הציע את זה במתמחים טופ].

זה פיתוח נפרד 
ואמור להיות יותר פשוט לביצוע

**Comment by Y-PLONI** [comment]
הנושא נידון בגיליון נפרד, @yisrael-rosen @YOSEFTT 
https://github.com/Sivan22/otzaria/issues/61
