### ISSUE TITLE
הערות שלי על הסוגיא

### ISSUE THREAD

**Issue by ZXCVBNM607** [Sivan22/otzaria#380]
אם אפשר להוסיף שכל אחד יוכל להוסיף הערות על הסוגיה וישמר לו בתוכנה זה עוזר שאם יש הערה קטנה ויש מקום לכתוב בתוכנה יכתבו ואם לא פשוט ילך לאיבוד.

**Comment by David-1684** [comment]
> אם אפשר להוסיף שכל אחד יוכל להוסיף הערות על הסוגיה וישמר לו בתוכנה זה עוזר שאם יש הערה קטנה ויש מקום לכתוב בתוכנה יכתבו ואם לא פשוט ילך לאיבוד.

כבר ביקשו כאן #374

**Comment by ZXCVBNM607** [comment]
סליחה שפתחתי משהו חדש במקום


‫בתאריך יום ד׳, 11 בדצמ׳ 2024 ב-9:52 מאת ‪David-1684‬‏ <‪
***@***.***‬‏>:‬
