### ISSUE TITLE
חידושי רמב"ן - שיבוש מילים

### ISSUE THREAD

**Issue by saryag** [Sivan22/otzaria#382]
## Describe the bug | תיאור הבאג
מילים משובשות 
מצורף צילום מסך עם הדגשת חלק מהמילים המשובשות
![image](https://github.com/user-attachments/assets/b3e43049-840c-48bd-af07-8a8bd5cc9729)

### Steps to reproduce | צעדים לשחזור
לדוגמא להיכנס לחידושי רמב"ן בבא בתרא דף ל"ב

### Environment | סביבה 
windows 
 - version | גרסת התוכנה: 
alpha-0.2.3

**Comment by Refael11** [comment]
זה קשור בעיקרון לספריא, כדאי לנסות לפנות אליהם ואז זה יתעדכן אוטומטית באוצריא

**Comment by Y-PLONI** [comment]
אין לנו הרבה מה לעשות. אנו יכולים לתקן, אבל אז נצטרך ליצור רשימה של מה שתיקנו ולא לעדכן את זה מספריא, בקיצור - בלבולי שכל...
