### ISSUE TITLE
Can not open otsaria the exe. account is rejected by microsoft as not reliable

### ISSUE THREAD

**Issue by Halichos** [Sivan22/otzaria#394]

**Comment by Y-PLONI** [comment]
לחץ על "מידע נוסף", ואז על הפעל

**Comment by Halichos** [comment]
Does not work this is what it says
לא עובד זה מה שכתוב
This app package’s publisher certificate could not be verified. Contact
your system administrator or the app developer to obtain a new app package
with verified certificates. The root certificate and all immediate
certificates of the signature in the app package must be verified
(0x800B010A)

**Comment by YOSEFTT** [comment]
רוצה  עזרה ע"י שליטה מרחוק?
א"כ תכתוב כאן או שתשלח לי למייל ***@***.*** את פרטי האנידסק שלך

‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-19:23 מאת ‪Halichos‬‏ <‪
***@***.***‬‏>:‬

> Does not work this is what it says
> לא עובד זה מה שכתוב
> This app package’s publisher certificate could not be verified. Contact
> your system administrator or the app developer to obtain a new app package
> with verified certificates. The root certificate and all immediate
> certificates of the signature in the app package must be verified
> (0x800B010A)
>

**Comment by David-1684** [comment]
ככל הנראה וינדוס נמצא ב Safe Mode. תעביר אותו למצב רגיל, וזה יסתדר.

**Comment by Y-PLONI** [comment]
העניין פשוט: הורדת רק את התוכנה [כ25 מגה], ולא את הקובץ המלא.
בהתקנת הקובץ המלא מותקן גם אישור, המאפשר את התקנת התוכנה. הורדת התוכנה לבדה מיועדת רק למי שכבר התקין את התוכנה המלאה עם אחת, ומעוניין לקבל עדכון תוכנה.
מקווה שהסברתי ברור...
