### ISSUE TITLE
באג בגרסה החדשה

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#4]
יש באג בגירסה החדשה - בחיפוש - הוא לא מציג את רשימת הספרים לחיפוש - מצורף תמונה.
עדיין אי אפשר לדפדף ברשימת הספרים עם החיצים- רק בטקסט עצמו של הספרים אפשר להשתמש בחיצים
תודה רבה
image.png

**Comment by Danthig** [comment]
זה לא באג, צריך להכניס בהגדרות את הנתיב של התיקייה אוצריא:
![image](https://github.com/Sivan22/otzaria/assets/161762042/6e496304-4758-452c-ab29-497475919877)

**Comment by AshiVered** [comment]
למה זה ככה?
אין אופציה שהתוכנה בעצמה תזהה את הנתיב? כלומר תתחיל לבדוק את הנתיב מאיפה שהexe עצמו נמצא?

**Comment by Sivan22** [comment]
זה קשור לתמיכה באנדרואיד, אבל יתוקן בלי נדר בגירסאות הבאות.

**Comment by AshiVered** [comment]
מחכים לגרסת האנדרואיד :) ישר כוח!

**Comment by Sivan22** [comment]
תוקן בגרסה 0.1.1
