### ISSUE TITLE
הצעת ייעול: הדפסה

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#41]
הצעת ייעול נוספת:
1. הוספת אפשרות להדפסה מתוך התוכנה עצמה
2. כשלוחצים על הלחצן איתור ספר זה לא מתחיל לחפש עד שמסמנים עם העכבר בשורת החיפוש.
3. נראה לי שעדיף שברירת המחדל שפותחים ספר תהיה שחלונית הניווט והחיפוש יפתחו באופן אוטומטי.
4. תודה רבה

_Originally posted by @cc054848484 in https://github.com/Sivan22/otzaria/issues/3#issuecomment-1968806611_

**Comment by Sivan22** [comment]
printing functionlaty added. (DEV version 0.1.7+7 and above)

**Comment by cc054848484** [comment]
איך מורידים את הגירסה הזו  version 0.1.7+7 and above

‫בתאריך יום א׳, 2 ביוני 2024 ב-8:55 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/issues/131
