### ISSUE TITLE
סדר התיקיות

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#42]
סדר התיקיות כרגע במסך הראשי הוא לפי א-ב, וזה גורם כמובן לסדר לא הגיוני, כאשר 'בית שני' ו'ברוכים הבאים' בהתחלה, ו'תנך' ו'תלמוד' בסוף. 
אגב, צריך למצוא פתרון שיופיעו קודם התיקיות ואח"כ קובץ פרטי כמו 'ברוכים הבאים'.
יש לסדר בסדר הגיוני, או לפחות לקבוע להםפ סדר ע"י הוספת מספור א־תנ''ך, ב־משנה, ג־תלמוד, וכך הלאה
וכך גם בתיקיות הפנימיות: למשל ב'הלכה' - טור שו"ע אחרונים כו' וכיו"ב.

**Comment by Y-PLONI** [comment]
הוזכר כאן:
https://github.com/Sivan22/otzaria/issues/46

**Comment by Bshlomecha** [comment]
א. תודה. נכון. ובאמת צ"ע א"כ לפי מה זה נסדר?

ב. עצה טובה [דרך אגב] לעשות ראשי תיבות בשמות המפרשים או הספרים - למרות שאי
אפשר לכלול בשם קובץ או תיקיה את התו גרשיים " מכל מקום אפשר לכתוב שני גרשים
בזה אחר זה וזה נראה [במחשב עכ"פ] כמעט אותו דבר : '' .

‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-10:12 מאת ‪yoseftct‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
אתה צודק, הנידון שם שונה, אך קרוב.
נראה לי שהיה עוד מישהו שביקש, לא מצאתי ברפרוף מהיר.

**Comment by Sivan22** [comment]
התיקיות מסודרות לפי א-ב לעת עתה. בתכנית לסדר אותם לפי רשימה ערוכה מראש שקיימת במאגר של ספריא. 
בחיפוש ספר התוצאות ממוינות לפי הקירבה לטקסט החיפוש (מרחק לוינשטיין).

**Comment by Bshlomecha** [comment]
*תודה*. כוונתי היתה שראוי לסדרם גם מבחינת הנגישות הפרקטית, אבל בעיקר מפני
הכבוד הראוי..

[אגב אעיז לשאול, לבני תורה רבים צורם ההקשר המפורש ל'ספריא', ומובן..
האם אכן אנו מחוייבים להזכירם בצורה כל כך מכובדת, מצד הזכויות, או משום
רצוננו שישתפו עמנו פעולה?]

‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-15:48 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
ישנם ספרי קודש רבים מאוד מתחילת הדפוס ועד לפני כמאה שנה, שהודפסו בדפוסים נוצריים עם מוטיבים נוצריים במיוחד, ואף על פי כן התקבלו בציבור החרדים לדבר ה' בצמאון. 
לדעתי עיקר הבעיה בספריא זה הספרים באנגלית, שכספריה כללית לכל ספרי היהדות הם הכניסו אותם, משום שהם 'ליברלים' ה"י. אך באופן כללי רוב הספרים הם קודש, ומה שוועדת הרבנים של הסינונים למיניהם החליטו לחסום, ובצדק, זה לא משום שאסור לקרוא בספרי המינים, אלא משום קושי בסינון (להבנתי), ולכן אין שום סיבה לשייך זאת למקום שממנו אתה יונק... (מכיר את הדיונים בפורום נטפרי, ואין צורך להפנות אותי לשם).
בברכת התורה

**Comment by Bshlomecha** [comment]
תודה.
אך *גילוי נאות *כי לא באתי מהדיון בנטפרי ואיני יונק משם. [אולי בשלב מסויים
שלחתי להם כמה נותנים שאספתי, אינני זוכר]
בניתי את התייחסותי על סמך מעקב ארוך על האתר שלהם ועל היוזמים והמפעילים, על
האג'נדות שלהם ועל מה שבחרו לכלול בו.
יתכן שאני טועה [זה קורה לא פעם...], ובמדה מסויימת יש דברים שאני אפילו מקוה
שאני טועה בהם [כי אין לי חלילה שום ענין לפסול מאחינו בני ישראל, וודאי שלא
מפעלים שיש בהם תועלת לקודש],
בכל מקרה ודאי הדברים מורכבים ואינם שחור לבן.
על כן - לא אמרתי שיש לכתוב מודעה המוקיעה אותם [כגון - אע"פ שלקחנו משם דעו
לכם וכו'], אלא רק לשמור על דיסטנס מאוק שאינו מדגיש את המקור משם.

אבל כאמור זו הגישה האישית שלי, איני אומר קבלו דעתי, בטח שאינני מתיימר להיות
מאן דאמר כלפיכם, שהשקעתם ובניתם מה שחיכינו וציפינו לו זמן רב.
רק אמרתי להשמיע דעתי כי בד"כ יש ברכה לשמוע דברי אחרים ולראות הדברים מזוויות
נוספות.

*בכל אופן תודה וברכה, חפץ ה' בידכם יצליח להגדיל תורה ולהאדירה. *


‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-22:37 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
https://github.com/Sivan22/otzaria/issues/54#issue-2232058583

‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-23:34 מאת ‪Bshlomecha‬‏ <‪
***@***.***‬‏>:‬

**Comment by YOSEFTT** [comment]
בקשר לצילו"מ של חיפוש ספר, שהעליתי למעלה מחיפוש של ספר הרש"ש.
בדקתי שוב, ולאחר מחשבה, ראיתי שהוא מסדר דבר ראשון לפי כמות אותיות. זאת אומרת, קודם 2 אותיות [דהיינו נדה, שבת] ואח"כ 3 וכו' [אחרי המילים 'רשש על'].
אבל בתוך אותו מספר אותיות, לא הבנתי כלל מה הסדר שלו.
וזה לא קשור לסדר הספרים שפתחתי לאחרונה כלל. או שפתוח כרגע.

אני מציע לשנות את זה, שכשאין נ"מ ללווינשטיין הזה [אני יודע מה זה, א"צ להסביר לי], התצוגה תהי' לפחות לפי א-ב. [עד שזה יסתדר לפי חשיבות ונושא, בגריסא 2.

**Comment by Danthig** [comment]
> מתיימר להיות מאן דאמר כלפיכם, שהשקעתם ובניתם מה שחיכינו וציפינו לו זמן רב. 
לייתר דיוק, אני לא בונה, ואפילו לא עוזר לבנות את התוכנה הנפלאה והמיוחדת "אוצריא", @Sivan22 הוא זה שבנה ובונה כותב ועורך ועושה הכל יחד עם @yisrael-rosen שלהם מגיע התודה הענקית שאינה מגלמת את גודל הזכות שיש להם בהנגשת דברי התורה לציבור היראים שספריא חסומה להם. 
ועל כך מגיעה להם הערכה והוקרה, ולא להתחיל לבקש דברים שאינם לפי רוחך.
כך היא דעתי, ולכן כתבתי לך זאת...
בברכת התורה

**Comment by Y-PLONI** [comment]
נסכם את הדיון הזה:
א. סדר הספרים: יסודר בגרסה 0.2, אין עניין להשקיע מאמצים וטיםול בבעיה שהולכת להסתדר [מיועד ל @YOSEFTT ]
ב. קרדיט: מי שמחליט זה @Sivan22 אנחנו סתם מתקשקשים...
ג. עניין לווינשטין לא יכול לקבל יחס לפני שנראה מה סיון מתכנן בגרסה הנ"ל, כך שניתן לסגור את הנושא.

**Comment by Sivan22** [comment]
סדר הספרים מתוכנן לגירסה 0.1.7. ראו כאן: https://github.com/Sivan22/otzaria/issues/75
