### ISSUE TITLE
באג: לא נפתח חלון איתור ספר

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#44]
מצו"ב הקלטת מסך

https://github.com/Sivan22/otzaria/assets/165617135/55acdef2-9e0f-407f-a055-01b66be74dd6

**Comment by Refael11** [comment]
כך גם בחלון 'דפדוף'

**Comment by Danthig** [comment]
בהגדרות התוכנה במיקום הספריה תכתוב נקודה .:
![image](https://github.com/Sivan22/otzaria/assets/161762042/cc34889a-d7c4-4500-ad43-e99abc203175)
תסגור ותפעיל את התוכנה.
