### ISSUE TITLE
איטיות בגירסא 0.1.6

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#45]
עושה רושם שמאז הגירסא החדשה התוכנה הפכה להיות איטית יותר, ומהרגע שאתה לוחץ על ספר מסוים עד שהוא נפתח לוקח זמן, זה בולט יותר בהצגת פרשנים

**Comment by Sivan22** [comment]
לאחר בדיקה, הבאג קיים רק באיתור ספר ולא בדפדוף, ורק אם יש טקסט בשורת החיפוש. אעדכן בהמשך אם יתוקן הבאג.

**Comment by Sivan22** [comment]
בגרסה הבאה 0.1.7 זה לא יהיה רלוונטי.
