### ISSUE TITLE
באג בשדרוג

### ISSUE THREAD

**Issue by sbhtk1989** [Sivan22/otzaria#46]
1. לא מוצג מפרשים 
ניסיתי ספר שופטים וכל המפרשים כאילו מנסים להיטען אך ללא הצלחה
2. אחרי כמה שימושים מסך אפור בתוכנה:
![צילום מסך 2024-04-08 080924](https://github.com/Sivan22/otzaria/assets/166361435/1eabee89-9347-47e1-9b89-cdee7e3f356c)
3. מסך לבן במסך הפתיחה כמו שמישהו אחר כבר ציין
4. בתצוגה 2 עמודים לא ניתן להעתיק טקסט

עדכון!!
אחרי התקנת התוסף ועדכון מקור הקבצים התקלות 1+2 הסתדרו

**Comment by yabig1456** [comment]
לאחר נסיונות רבים, התברר לי שכל עוד שקיים במחשב גירסה ישנה יותר, הוא לא מצליח לבחור את התקיה הנכונה, ומכאן הבעיה הנזכרת! אצלי זה עזר שמחקתי את גירסה 15 לגמרי, ואז התחילו להיטען הספרים... 
נסו זאת...
(ניסיתי בגירסה 16 מלאה)

**Comment by Y-PLONI** [comment]
תואם למסקנה בגיליון זה:
https://github.com/Sivan22/otzaria/issues/39

**Comment by Y-PLONI** [comment]
ראו כאן:
https://github.com/Sivan22/otzaria/issues/53
