### ISSUE TITLE
באגים בחיפושים

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#47]
נפתח בנטפרי.
בהתחלה הי' סגור עקב תוכן אסור רח"ל שנכתב כאן [לפי הבוט...]

כבר נכתב כאן: https://mitmachim.top/post/770708 במס' 1 על באגים בחיפוש בתנ"ך. 
אני מעתיק משם - אין אפשרות בתנ"ך לחפש מילים בסוף פסוק ביחד עם המילים שאחריהם בפסוק הבא. כגון 'מרחפת על פני המים ויאמר', אין שום תוצאות.
אח"כ ראיתי שגם בגמ' זה ככה, אם עושים חיפוש בסוף קטע ותחילת הקטע שאחריו. 
מצורף תמונה. 
שים לב, שבעמוד הפתוח כתוב פעמיים בסוף שתי הקטעים את המילים 'לא איקרי', אבל הוא לא מוצא אפי' אחד מהם! וזה בגלל שכתבתי רווח אחרי המילה 'איקרי', ומבחינתו אחרי שנגמר הקטע אין לא רווח ולא נקודה ולא פסיק ולא כלום.

אתמול שמתי לב לשתי דברים נוספים:
א. שגם בגמ' יש את הבעי' הזאת שכשיש נקודות ופסיקים וסימני שאלה ותשובה וכדו', הוא לא ימצא בחיפוש אם לא יכתבו בחיפוש את הסימנים הנ"ל בדיוק כמו שהם כתובים בתוכנה.

ב. דבר נוסף, כשחפשתי את המילה 'אלמנה' בגמ' בקידושין, הוא מצא לי 33 תוצאות, [וכשיש רווח אחרי המילה 27 תוצאות]. 
אבל משום מה, ממש אין לי שום הסבר וקצה חוט, את המילה אלמנה שבדף לד ע"ב הוא לא מצא [כך כתוב בגמ' - אַלְמָנָה מַאי אִיכָּא לְמֵימַר? בִּשְׁרוּיָה אֶצְלוֹ.] וצ"ע רב. 
אחרי זה ראיתי שכשעשיתי חיפוש בגוף הספר בלשונית הנפתחת של ניווט חיפוש פרשנות קישורים, שם הוא כן מצאאת זה. 
ויותר מזה, שם הוא מוצא 36 תוצאות [כשמחפשים את המילה אלמנה בלי רווח אחרי המילה], וזה אומר שהוא מוצא עוד 3 תוצאות. וצ"ע בכ"ז.

אח"כ עברתי אחד אחד לבדוק מה הם עוד 2 התוצאות המוצגות רק בחיפוש שבגוף הספר, וגיליתי שהם:
אחד בדף עז ע"א, אַלְמָנָה וּגְרוּשָׁה וַחֲלָלָה זוֹנָה, בִּזְמַן שֶׁהֵם כַּסֵּדֶר – חַיָּיב עַל כׇּל אַחַת וְאַחַת. זִינְּתָה וְנִתְחַלְּלָה וְנִתְגָּרְשָׁה וְנִתְאַרְמְלָה – אֵינוֹ חַיָּיב אֶלָּא אַחַת.
ועוד אחד כנ"ל שם ע"ב, אַלְמָנָה אֲסוּרָה לְכֹהֵן גָּדוֹל וְשַׁרְיָא לְכֹהֵן הֶדְיוֹט. הָוְיָא לַהּ גְּרוּשָׁה, מִיגּוֹ דְּאִיתּוֹסַף לַהּ אִיסּוּרָא לְגַבֵּי כֹּהֵן הֶדְיוֹט – אִיתּוֹסַף לַהּ אִיסּוּרָא לְגַבֵּי כֹּהֵן גָּדוֹל, וַעֲדַיִין שַׁרְיָא לְמֵיכַל בִּתְרוּמָה. הָוְיָא לַהּ חֲלָלָה, מִיגּוֹ דְּאִיתּוֹסַף אִיסּוּרָא לְמֵיכַל בִּתְרוּמָה – אִיתּוֹסַף אִיסּוּרָא לְגַבֵּי כֹּהֵן גָּדוֹל.

והמשותף לכולם שהמילה אלמנה היא בתחילת קטע [לפי חלוקת הקטעים של התוכנה]. ולמרות שבחיפוש לא כתבתי שום תו לםני האות א של המילה אלמנה!

**Comment by Y-PLONI** [comment]
הערות נכונות, אבל אם כמו שאני מבין - שכשיהיה חיפוש הוא יהיה חיפוש חכם, אין לזה משמעות.
ראה באבני הדרך.
