### ISSUE TITLE
חיפוש נוסף באותו חלון

### ISSUE THREAD

**Issue by yoseftct** [Sivan22/otzaria#48]
הועתק מכאן: https://mitmachim.top/post/770708 מס' 3
במסך חיפוש לאחר שעושים חיפוש אחד, ורוצים לעשות חיפוש נוסף, אין אפשרות לשנות את רשימת הספרים לחיפוש, ורק אפשר לפתוח חיפוש חדש. אני לא אומר שזה בוודאי לא טוב, רק שתשים לב לכך אם באמת אתה רוצה שזה יישאר כך.

**Comment by Danthig** [comment]
@Sivan22 האם יש דרך למחוק נושא כפול? 
וכיצד?
