### ISSUE TITLE
חיפוש חוזר בספרים שונים

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#49]
הועתק מכאן: https://mitmachim.top/post/770708 מס' 3
במסך חיפוש לאחר שעושים חיפוש אחד, ורוצים לעשות חיפוש נוסף, אין אפשרות לשנות את רשימת הספרים לחיפוש, ורק אפשר לפתוח חיפוש חדש. 
אני לא אומר שזה בוודאי לא טוב, רק שתשים לב לכך אם באמת אתה רוצה שזה יישאר כך.

**Comment by Sivan22** [comment]
אפשר אם מוחקים את שורת החיפוש ומאשרים.
