### ISSUE TITLE
רצועה אדומה מופיעה מסך

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#5]
בגרסא החדשה, כשלוחצים על "דפדוף" או "איתור ספר".
ישר כוח ותודה רבה!

https://github.com/Sivan22/otzaria/assets/76535872/8f210ae3-3eec-4c68-8a27-590bead1d36f

**Comment by Y-PLONI** [comment]
לא מצליח לראות את הווידאו.
תוכל להעלות צילו"מ?

**Comment by AshiVered** [comment]
הובא גם כאן
https://github.com/Sivan22/otzaria/issues/8
