### ISSUE TITLE
עיצוב עץ הספרים במסך חיפוש

### ISSUE THREAD

**Issue by ghost** [Sivan22/otzaria#50]
הועתק מכאן:https://mitmachim.top/post/770708 מס' 2
בבחירת ספרים לחיפוש בתוך תיקיות, כשיש בתוך התיקיי' גם קבצים וגם תיקיות, אז הקבצים יוצאים קצת הצידה לצד ימין, לטעמי זה מבלבל.
יותר נח כמו במסך דפדוף בספרים, או שהכל מיושר ומתחיל באותו קו, או בצורה של עץ ספרים, שכל תיקייה נכנסת קצת שמאלה, אבל שלא יהיה הבדל בין ספרים בודדים לתיקיות בתוך תיקיית האב שלהם.
מצו"ב צילו"מ מתיקיית 'קבלה'.
![image](https://github.com/Sivan22/otzaria/assets/115775588/0a33104d-1cc7-4f99-8239-f2677475ba21)

**Comment by yisrael-rosen** [comment]
> מצו"ב צילו"מ מתיקיית 'קבלה'.

תודה על הדוגמה
עזר להבין על מה מדובר
הצעתי תיקון שיראה ככה
![image](https://github.com/Sivan22/otzaria/assets/57872424/40f62b30-6aea-4eb1-ac12-5964e1b5a9bf)

**Comment by YOSEFTT** [comment]
מצוין!
בהתחלה חשבתי שעדיף שהריבוע שאותו מסמנים יהי' מתחת לסמל התיקי' שמעליו, דהיינו שהריבוע של וזאת ליהודה יהי' ממש מתחת הסמל קבלה כמו זה:
![321285892-40f62b30-6aea-4eb1-ac12-5964e1b5a9bf](https://github.com/Sivan22/otzaria/assets/166497965/47c7dbc7-31a7-4c5d-a731-37c0908a28dc)
אבל אח"כ חשבתי שאולי באמת יותר טוב כמו התמונה שאתה העלית, כי אם יש הרבה תתי תיקיות אז כל העץ זז מידי הרבה שמאלה, ואז זה לוקח הרבה מקום במסך.
למעשה עשה כחוכמתך!

**Comment by yisrael-rosen** [comment]
לא מצאתי תיקיה יותר עמוקה מ6
במחשב זה נראה בסדר
אבל צריך לבדוק במובייל
![image](https://github.com/Sivan22/otzaria/assets/57872424/c14ff14b-b3c0-4e25-86dd-8e41b2625fe5)

**Comment by YOSEFTT** [comment]
צודק, אבל אם אנו רוצים שיוכלו לראות ברקע את הספר שפתוח עכשיו תוך כדי איתור הספר הבא [יכול להיות לכך כמה סיבות], אז צריך שישאר גם רווח לזה.
וחוץ מזה, אתה מדבר כרגע, אבל בתוך זמן קצר התוכנה אמורה לכלול עשרות אלפי ספרים בעז"ה, וצריך לחשוב גם על העתיד.

**Comment by Y-PLONI** [comment]
גם אז לא אמור להיות יותר מ6. אמור להיות יותר בכל אחד.
אגב, כשהתוכנה תהיה עשרות אלפי ספרים, לא ישתמשו בזה ללא חיפוש פנימי [כלומר: לא יפתחו את העץ, אלא פשוט יאתרו את הספר]

**Comment by YOSEFTT** [comment]
@Y-PLONI  אז בעצם אתה אומר שכן עדיף כמו הצורה שאני הצעתי?
