### ISSUE TITLE
נוחות גישה להגדרות ממשק

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#51]
יהיה תועלתי אם אפשרויות 'הגדרות ממשק' יהיו מתוך המסך הראשי של התוכנה:
א' שסגירת תפריט הצד בעת גלילה יהיה עם נעץ בתפריט גלילה עצמו.
ב' שהצגת מפרשים במפוצל יהיה בכפתור ליד הסימניות 
![image](https://github.com/Sivan22/otzaria/assets/161762042/40877102-93da-4244-8f3c-1131b44c64dc)
.

**Comment by Sivan22** [comment]
a.
![image](https://github.com/Sivan22/otzaria/assets/89018301/15a713f5-084d-4d1d-8904-3388e32c0551)

**Comment by Sivan22** [comment]
b. 
![image](https://github.com/Sivan22/otzaria/assets/89018301/8c0d6b5b-7226-493b-ab0a-822008745fdd)
![image](https://github.com/Sivan22/otzaria/assets/89018301/835ff2b3-324e-4535-a87d-87f1f4b74896)

**Comment by YOSEFTT** [comment]
@Sivan22  עדיין זה לא סותר לכך שיהי' כפתור זה גם בהגדרות, כי יש את ההגדרה ברירת מחדל שאת זה מגדירים בהגדרות, ויש את מה שהמשתמש רוצה לשנות בספר הספציפי הנוכחי שלזה יש את הכפתור שעל המסך.
בדיוק כמו כפתור גודל הגופן, שקיים גם בהגדרות, וגם על המסך בפתיחת ספר.
