### ISSUE TITLE
שדרגתם לגרסה 0.1.6? שימו לב:

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#53]
כנסו להגדרות, ובמיקום הספריה הקלידו נקודה אחת. ככה:
![image](https://github.com/Sivan22/otzaria/assets/116633732/04f9f974-0320-4f92-b785-d1a462a1b2ed)

**Comment by Y-PLONI** [comment]
מומלץ גם להכנס ב"דפדוף" ל"ברוכים הבאים", משום מה זה לא נפתח אוטומטית כבעבר.

**Comment by Danthig** [comment]
> כנסו להגדרות, ובמיקום הספריה הקלידו נקודה אחת. ככה:
כבר היה לעולמים...
https://github.com/Sivan22/otzaria/issues/44#issuecomment-2041614981
