### ISSUE TITLE
השמטת קרדיט

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#54]
כדי שלא לפגוע ברגשותיהם של ציבור יראי ה', האם אפשר למזער את הקרדיט לספריא?
https://github.com/Sivan22/otzaria/issues/42#issuecomment-2043474885
https://github.com/Sivan22/otzaria/issues/42#issuecomment-2043596154

**Comment by Sivan22** [comment]
חוץ מהכרת הטוב שלימדה תורה אפילו למצרים, חשוב לי להדגיש שהטקסטים באו ממקור
אחר ואני רק מנגיש את הממשק. ולכן הרמיזה.

בתאריך יום ב׳, 8 באפר׳ 2024, 23:51, מאת Danthig ***@***.***>:

**Comment by Y-PLONI** [comment]
איזה רגשות???
אתה רוצה למחוק את הסמל של בר אילן מהמחשב שלך, כי זה אוניברסיטה ש"כל באיה לא ישובון"???
אתה לא מזמין אינסטלטור עם אייפון?
אתה לא הראשון שכותב זאת, ולכן אני כותב בכזו חריפות.
יש ארגון שעשה משהו. זה שלו. הוא נתן לך להשתמש - תגיד תודה. בא נגיד שהוא עשה חלוקה לפסח, בסדר?

**Comment by YOSEFTT** [comment]
מה לא מובן, 
בקשר לסמל של בר אילן, תשאל את כל החברים שלך, ואת אבא שלך, בוודאי שהם ירצו למחוק את הסמל. כן!
להגיד תודה, זה דבר נכון, אבל הנושא הוא רק למזער את גודל התמונה. 
מה העסק הגדול שאתה יוצא נגד זה????
[בלי קשר שלטעמי הגודל לא פרופורציונאלי, גם אם זה הי' סמל קדוש של ישיבת פוניבז' לדוגמא].

אולי נשאל הפוך, לא נראה לך שזה ממש חוסר הכרת הטוב כזה סמל קטן?
צריך להגדיל אותו הרבה יותר!!!.........!!!!!!!

**Comment by Danthig** [comment]
> מה לא מובן, בקשר לסמל של בר אילן, תשאל את כל החברים שלך, ואת אבא שלך, בוודאי שהם ירצו למחוק את הסמל. כן! להגיד תודה, זה דבר נכון, אבל הנושא הוא רק למזער את גודל התמונה. מה העסק הגדול שאתה יוצא נגד זה???? [בלי קשר שלטעמי הגודל לא פרופורציונאלי, גם אם זה הי' סמל קדוש של ישיבת פוניבז' לדוגמא].
> 
> אולי נשאל הפוך, לא נראה לך שזה ממש חוסר הכרת הטוב כזה סמל קטן? צריך להגדיל אותו הרבה יותר!!!........!!!!!!!

אני חושב שהוסבר כאן טוב את הסיבה, אין שום סיבה להמשיך את הדיון, אם זה מפריע לך אתה לא חייב להשתמש לא באוצריא, ולא בספריא!!!
וגם לשיטתך עדיף שידעו מהיכן הטקסטים כדי שידעו לקחת את הדברים בערבון מוגבל.
נא לא להמשיך את הדיון בענין זה. 
בברכה

**Comment by YOSEFTT** [comment]
@Danthig אני לא מבין מה ההבדל בין מה שאני טענתי כאן, למה שאתה בעצמך כתבת בתחילת הפוסט.
@Bshlomecha ראה כאן, ותרווה המון נחת. https://mitmachim.top/post/774433

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/issues/42
עריכה: אני רואה שציינת כבר [את הגיליון ההוא].
