### ISSUE TITLE
פתיחת החלון בכרטיסיה שנצפתה לאחרונה

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#55]
כיום אם יש כמה כרטיסיות פתוחות, אחרי סגירת החלון ופתיחתו מחדש החלון יפתח בכרטיסיה שהיא האחרונה ברשימה ולא בכרטיסיה שנקראה אחרונה.
כדאי שהחלון יפתח בכרטיסיה שנקראה אחרונה.
מקווה שאני מספיק מובן

**Comment by Sivan22** [comment]
ייושם בגרסה הבאה 0.1.7.
