### ISSUE TITLE
אפשרות לטורים ועימוד מינימלי אוטומטי לספרי הטקסט

### ISSUE THREAD

**Issue by abaye123** [Sivan22/otzaria#56]
כדאי להוסיף אפשרות להגדרה של תצוגת הטקסט בטורים, 

ואולי גם מספר כללי עימוד מוגדרים נוספים, כמו חלון וכו' שמקובלים בעימוד של ספרי קודש.

**Comment by Danthig** [comment]
???
זה לא תוכנת עימוד, מה הכוונה / התועלת בכך.

**Comment by abaye123** [comment]
כוונתי שהתוכנה תציג את הטקסטים באופן אוטומטי בצורה נוחה יותר, ובסגנון המקובל לספרי קודש,

ולא שיהיה אפשר לעמד את הטקסט..

**Comment by Sivan22** [comment]
לא בתכנון כרגע. (כמובן שניתן להשתמש בקובץ pdf שכולל עימוד מובנה.)

בתאריך יום ג׳, 9 באפר׳ 2024, 16:45, מאת abaye ***@***.***>:

**Comment by Bshlomecha** [comment]
כמדומה שב'ספריא' ישנו עימוד מאיר עיניים [זכור לי מהתקופה שהי' פתוח ולפני שהתחדשה לי הסתייגות ממנו. איני יודע איך זה מעוצב היום].

**Comment by Y-PLONI** [comment]
לסגור, @Sivan22 ?
