### ISSUE TITLE
 נתיב ספריה ברירת מחדל

### ISSUE THREAD

**Issue by rabanan** [Sivan22/otzaria#58]
תודה רבה!
**כדאי שהתוכנה תזהה מאיזה נתיב היא הופעלה כברירת מחדל וזה יחסוך הרבה שאלות ומסכים ריקים למשתמשים מתחילים (כמוני🤔)**

**Comment by Danthig** [comment]
@Sivan22 כדאי להוסיף בהסבר ליד ההורדה, מה לכתוב בהגדרות - מיקום התוכנה, ישנם הרבה שמסתבכים עם זה.

**Comment by Y-PLONI** [comment]
ערכתי את ההודעה הראשונה.
למעשה התוכנה בהחלט מזהה את נתיב ההפעלה, את מכניסים נקודה אחת (.) לא ברור למה זה לא נמצא כברירת מחדל.

**Comment by Sivan22** [comment]
מהגרסה הבאה 0.1.7 יצטרכו להגדיר בפתיחה הראשונה את מיקום הספרייה. כמו שקיים היום באנדרואיד.

**Comment by Y-PLONI** [comment]
למה שלא יישאר כמו עכשיו, שנקודה מסדרת את המיקום אוטומטית?

**Comment by Danthig** [comment]
> למה שלא יישאר כמו עכשיו?

כי הרבה אנשים הסתבכו עם זה!

**Comment by Y-PLONI** [comment]
אז שתהיה נקודה כברירת מחדל!
