### ISSUE TITLE
קישור ביאור הריטב"א להגדה

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#59]
מצו"ב הקלטת מסך
[הקלטה 2024-04-09 093102.zip](https://github.com/Sivan22/otzaria/files/14914210/2024-04-09.093102.zip)

**Comment by Refael11** [comment]
@Danthig למיטב הבנתי הבעיה אינה ספציפית לריטב"א על הגדש"פ

**Comment by Danthig** [comment]
באופן כללי הקישורים עובדים אינם מושלמים. 
תסמן את כל הפרשנים, ותראה שהרבה מהם עובדים, ורק ביאור הריטב"א אינו מופיע כלל, לדעתי בגלל שאין אותו על כל ההגדה הוא מקוטלג באופן קצת שונה (עם פרקים באמצע), ולכן הקישורים אינם תואמים. 
בעיה זו קיימת בעוד פרשנים ולא רק על ההגדה.

**Comment by Sivan22** [comment]
גם בספריא הוא לא מקושר.

בתאריך יום ג׳, 9 באפר׳ 2024, 16:21, מאת Danthig ***@***.***>:

**Comment by Sivan22** [comment]
באופן כללי, קשה לטפל בקישורים ולשנות אותם. אפשר לפנות לספריא בכל מה שנוגע לטעויות במאגר, והם אולי  יתקנו זאת בעתיד.
