### ISSUE TITLE
הזזת טאבים של ספרים ימינה ושמאלה

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#61]
רציתי להציע, שיהי' אפשר טאבים ימינה ושמאלה, כמו שקיים בתוכנת תורת אמת.
[זה מאוד שימושי לי. וזכור לי שמישהו כבר הציע את זה במתמחים טופ].

**Comment by Sivan22** [comment]
בוצע בסייעתא דשמיא.

**Comment by Refael11** [comment]
אפשר להזיז רק שמאלה ולא ימינה, מצו"ב תיעוד מגירסה 0.1.7+6


‫בתאריך יום ד׳, 29 במאי 2024 ב-7:02 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
לא ניתן לשלוח תיעוד דרך מייל @Refael11

**Comment by Y-PLONI** [comment]
שיניתי לבאג, כי התכונה קיימת - ובעייתית

**Comment by Sivan22** [comment]
צריך לשחרר את הכרטיסיה *על גבי* כרטיסיה אחרת ממש (ניתן לראות שהיא מודגשת), ולא באויר.

**Comment by Y-PLONI** [comment]
יש לכתוב זאת בהדרכה לתוכנה, מישהו זוכר איפה זה ומי כתב?
