### ISSUE TITLE
קישורי 'פרשנות'

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#63]
[דברים ששמתי לב אליהם תוך כדי עבודתי על השוואת אוצריא לתורת אמת].

ילקוט שמעוני וכן מדרש רבה, אינם נמצאים בקטגוריה פרשנות של התורה, למרות שהם קיימים בתוכנה.

בפרשנות של גמ' ברכות, קיים תוס' על פסחים, צ"ע למה. ובאמת גגם כשמסמנים אותו לא ראיתי שנפתח משהו.

בפרשנות על ספר יצירה להוסיף גם את פרי יצחק ופירוש הגרא ונוסח הגרא, קיימים כבר במאגר, אך לא מובאים ב'פרשנות' של ספר יצירה.

**Comment by YOSEFTT** [comment]
כמוכן, בפרשנות על מסכת בבא בתרא ושבועות [ואולי עוד מסכתות] חוץ מהרי"ף על המסכת, קיים גם על עוד הרבה מסכתות. מצו"ב צילו"מ.
![image](https://github.com/Sivan22/otzaria/assets/166497965/f13e8f0f-d4c9-4188-a982-2011481b9dc2)

**Comment by Sivan22** [comment]
במאגר ספריא זה מוגדר פרשנות מצטטת, וההבדל בין פרשנות על הדף הוא בשדה אחר
שמגדיר איזה ספר מפרש ספר אחר. בינתיים לא מימשתי את זה בתוכנה.

בתאריך יום ד׳, 10 באפר׳ 2024, 18:41, מאת יוסף ***@***.***>:
