### ISSUE TITLE
מסך פרשנות כשאין פרשנים כלל

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#64]
גם כשאין בכלל פרשנים הוא נותן לבחור 'כל הפרשנים', לטעמי זה באג שלא אמור להיות.
מצורף צילו"מ.
![image](https://github.com/Sivan22/otzaria/assets/166497965/42e4cc42-6ee5-45d1-baf7-04471e61d773)

**Comment by Y-PLONI** [comment]
כלומר: כדאי שתהיה הודעה: אין פרשנים.
[אולי זה לא באג אלא הצעה לשיפור? מי יודע?

**Comment by YOSEFTT** [comment]
או שלא יהי' כלום, אבל לא נראה לי שאמור להיות כתוב - 'כל הפרשנים'.

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/463f64a5-978f-442c-9e17-ae8a2713b96e)

**Comment by Y-PLONI** [comment]
במחשבה שנייה, עדיין כדאי להעיף את זה לגמרי.
לפתוח, @Sivan22 ?
