### ISSUE TITLE
באג בקידוד כותרת רמה 3

### ISSUE THREAD

**Issue by ToratEmetInWord** [Sivan22/otzaria#65]
בספר דרך המלך הקידוד בכל בכותרות רמה שלוש אינו סגור נכון כלומר:

`<h3>הקדמה<h3>`
במקום

`<h3>הקדמה<\h3>`

צריך לבדוק האם זה נכון לגבי עוד ספרים והאם הבאג בקידודון תורת את או במקום אחר

**Comment by Y-PLONI** [comment]
כרגע אין קשר לתורת אמת.
איך ניתן לבדוק לגבי שאר הספרים?
יותר מכך: מה ראית בספר הנ"ל? לא הצלחתי להבין. נראה בסדר, לא?
![image](https://github.com/Sivan22/otzaria/assets/116633732/3c074a65-c20a-40b4-bed6-723544dc1140)

**Comment by pcinfogmach** [comment]
הממ מעניין אתה צודק האמת היא שלא עלית על הבאג דרך אוצריא אלא דרך תורת אמת בוורד
תפתח את הקובץ הנ"ל על ידי עורך טקסטים ותראה

**Comment by Y-PLONI** [comment]
לא הבנתי. יש בעיה או אין? יש בעיה שרואים אותה רק בקורא טקסטים, אבל בתוכנה זה עובד מצויין?

**Comment by pcinfogmach** [comment]
כן - לא מבין איך אז אולי זה לא בעיה!?!?!?

**Comment by NHLOCAL** [comment]
This is definitely a bug. Even if for some reason it doesn't cause a problem with the display.

**Comment by Y-PLONI** [comment]
מה המשמעות של באג שלא רואים?
"בתורת"? אני מעוניין ב"בפועל", לא ב"בכוח"...

‫בתאריך יום ו׳, 26 באפר׳ 2024 ב-15:50 מאת ‪NHLOCAL‬‏ <‪
***@***.***‬‏>:‬

**Comment by NHLOCAL** [comment]
לטווח הארוך יתכן שזה יגרום לבעיות, גם אם ברגע זה אין השפעה לכאורה

**Comment by Sivan22** [comment]
סוף סוף מצאתי את הבאג, וסידרתי אותו.
