### ISSUE TITLE
הוספת "בעל השמועה" למאגר

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#66]
אברך שאני מכיר הכין את הקובץ המצורף (כמובן, אני מעלה אותו לכאן בברכתו ואישורו)
רשימה של כל האמוראים (יתכנו כמובן פספוסים) שמופיעים בש"ס, כולל מראי מקומות ופרטים על האמורא.
לדוגמא
![image](https://github.com/Sivan22/otzaria/assets/76535872/47ffbab7-ee69-40dc-b45e-da533e938840)
[בעל השמועה.pdf](https://github.com/Sivan22/otzaria/files/14930035/default.pdf)

**Comment by Y-PLONI** [comment]
באיזה תת תיקיה אתה רוצה להכניס? נא לפרט.
כמו"כ כדאי להוריד את סימן המים, לא כ"כ מוצלח ככה. נכון?

**Comment by Y-PLONI** [comment]
מחוסר תיוג מתאים, הגדרתי זאת כ"ייעול" עם "מאגר".

**Comment by AshiVered** [comment]
אצלי הוספתי לתיקיית תלמוד
![image](https://github.com/Sivan22/otzaria/assets/76535872/980cef16-9366-49c7-a27e-489bca8a0e0b)
את סימן המים הוספתי לבקשתו.

**Comment by Y-PLONI** [comment]
למה הוא ביקש זאת? מה העניין בזה?

‫בתאריך יום ה׳, 11 באפר׳ 2024 ב-11:25 מאת ‪Ashi Vered‬‏ <‪
***@***.***‬‏>:‬
