### ISSUE TITLE
גופנים

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#69]
כדאי שתהיה אפשרות להכניס גופנים נוספים [וכן אפשר שתוסיפו אתם].
כשניסיתי להכניס לתיקיה של הפונטים - לא זיהה אותם.
[לעצמי - התחכמתי וקראתי לפונטים החדשים בשמות אשר קראתם את הפונטים הישני, וכך הם נכנסו....]

**Comment by Y-PLONI** [comment]
נראה לי יותר פשוט לפיתוח, שהתוכנה תסתמך על גופני המחשב, לא @Sivan22 ?
