### ISSUE TITLE
למה התוכנה רוצה גישה למיקום?

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#7]
מה הקשר בין ספרים למיקום?
![image](https://github.com/Sivan22/otzaria/assets/116633732/56dc8504-ca04-42d5-ada9-71be7e6c04e5)

**Comment by Y-PLONI** [comment]
והערות נוספות:
[הערות לאוצרייא.docx](https://github.com/Sivan22/otzaria/files/14500613/default.docx)

**Comment by Y-PLONI** [comment]
עוד לא הבנתי: למה התוכנה צריכה גישה למיקום?

‫בתאריך יום ו׳, 3 במאי 2024 ב-1:30 מאת ‪Sivan22‬‏ ***@***.***
‬‏>:‬

**Comment by Sivan22** [comment]
גם אני לא יודע, אצלי היא לא דורשת גישה למיקום. [image: image.png]

‫בתאריך יום ו׳, 3 במאי 2024 ב-13:48 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by YOSEFTT** [comment]
גם אצלי היא משתמשת במיקום.
דרך אגב, @Sivan22 התוכנה אצלך 'מותקנת'? [ועוד בשם עברי 'אוצריא'?], אצל כולנו היא ניידת, משהו מאוד מוזר כאן!

**Comment by Danthig** [comment]
אצלי גם לא מבקשת להגיע למיקום, בכל מקרה אצלי המיקום כבוי:
![image](https://github.com/Sivan22/otzaria/assets/161762042/f022e42b-9af6-4b11-b1b2-87d613097157)

**Comment by Sivan22** [comment]
יש התקנה (קובץ בסיומת msix) אבל צריך להתקין קודם תעודת אבטחה (קובץ בסיומת
crt) ויש אנשים שניסו ולא הצליחו. אשמח לעוד בודקים לקובץ ההתקנה.

בתאריך יום א׳, 5 במאי 2024, 4:33, מאת Danthig ***@***.***>:

**Comment by Y-PLONI** [comment]
> אצלי גם לא מבקשת להגיע למיקום,

חושבני שלא שייך לבקש גישה כשהוא כבוי.


> אשמח לעוד בודקים לקובץ ההתקנה

מה יש לעשות?

**Comment by Danthig** [comment]
> מה יש לעשות?

צריך להוסיף את [הקובץ הזה](https://github.com/Sivan22/otzaria/releases/download/v0.1.6-beta/sivan22.crt) למקורות מהימנים, לא זוכר בדיוק את ההגדרה, ואחר כך [להתקין את זה](https://github.com/Sivan22/otzaria/releases/download/v0.1.6-beta/otzaria.appinstaller) כך כתב לי פעם @Sivan22 אולי תמצא את זה איפשהו. 
אבל כאן הוא כתב שצריך [להתקין את זה](https://github.com/Sivan22/otzaria/releases/download/v0.1.6-beta/otzaria_0.0.1.6.msix) אצלי שניהם לא עובדים.

**Comment by Y-PLONI** [comment]
דווקא הלך לי מאוד בקלות...
כבר אכתוב הדרכה

**Comment by Y-PLONI** [comment]
לא ברור לי היכן הדאטה אמור להיות. @Sivan22 ?

**Comment by Sivan22** [comment]
הספריה יכולה להיות בכל מקום, רק צריך להגדיר את מיקום הספריה.

‫בתאריך יום א׳, 5 במאי 2024 ב-22:17 מאת ‪Y-PLONI‬‏ <‪
***@***.***‬‏>:‬

**Comment by Y-PLONI** [comment]
יש לחפש ב"התחל": **אישורי**, זו התוצאה הנדרשת:
![image](https://github.com/Sivan22/otzaria/assets/116633732/6bb19cb3-b020-4666-b889-8a5b1fb75142)
הכנס, בתפריט הלחצן הימני על **רשויות אישורים עליונות מהימנות**, תחת **כל המשימות**, בחר ב-**import**, כך:
![image](https://github.com/Sivan22/otzaria/assets/116633732/e1a6c1ba-724b-4640-a7cf-5907dab1765a)
לחץ על הבא, נווט אל הקובץ, לחץ על **הבא**, שוב **הבא** ולבסוף **סיום**, וההתקנה בוצעה.
כעת הורד את קובץ ה-msix, והתקן אותו להנאתך, את הספרייה מקם היכן שתרצה, רק זכור להגדיר זאת באוצריא, בהגדרות.
קובץ ה-otzaria.appinstaller הוא סה"כ קובץ התקנה מקוונת, או עדכון.

כתבתי כ"כ מפורט ועם צילומי מסך לא בשבילך, @Danthig [וגם לא בשבילך, @Sivan22 ...] אלא בשביל שיהיה קל לכם להעתיק זאת למי שצריך...

**Comment by Y-PLONI** [comment]
אגב...
![image](https://github.com/Sivan22/otzaria/assets/116633732/2e3d5ec5-0f16-4f9f-8757-a0603e00008c)

**Comment by Danthig** [comment]
הנה הפוסט (היה מתחת לאף)...
https://github.com/Sivan22/otzaria/issues/72
