### ISSUE TITLE
שדות אפורים

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#70]
בגירסא 0.15 התכנה פעלה מעולה.
גירסא 0.16 עושה שדות אפורים כפי שניתן להתרשם בגיפ המצורף
![אנימציה](https://github.com/Sivan22/otzaria/assets/85172877/7caea3ca-4984-490a-b969-c42357b3fbf6)

גם לא עזר להוריד מחדש גירסא 0.16 מלאה ולהתקין.

**Comment by Danthig** [comment]
https://github.com/Sivan22/otzaria/issues/53#issue-2231893685
כנס להגדרות ובמיקום ספריה כתוב . (נקודה), ואשר, סגור ותפעיל מחדש את התוכנה.

**Comment by Danthig** [comment]
https://github.com/Sivan22/otzaria/issues/53#issue-2231893685
כנס להגדרות ובמיקום ספריה כתוב . (נקודה), ואשר, סגור ותפעיל מחדש את התוכנה.

**Comment by chezfo** [comment]
תודה!

אכן הבעיה נפתרה!
