### ISSUE TITLE
באג כשהתוכנה על חצי מסך

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#71]
כשהתוכנה על חצי מסך, והתפריט נמצא במאוזן למטה,
אז כשלוחצים על 'איתור ספר', הסמן לא נמצא על שורת החיפוש באופן אוטומטי, 
[ורק כשהתוכנה על מסך שלם, והתפריט בצד ימין, אז זה מסודר כבר].

**Comment by Y-PLONI** [comment]
יש לציין שבחיפוש הסמן נמצא, ההבאג קיים רק באיתור.

**Comment by Sivan22** [comment]
זה לא יהיה רלוונטי בגרסה הבאה. 0.1.7 עם מסך ספרייה ואיתור ספר חדש.
