### ISSUE TITLE
a new library browsing experience

### ISSUE THREAD

**Issue by Sivan22** [Sivan22/otzaria#75]
working for the next version on a new UX for books browsing (inspired by sefaria's app):

![image](https://github.com/Sivan22/otzaria/assets/89018301/809283cd-fa57-4785-afc0-f34a0d490259)
![image](https://github.com/Sivan22/otzaria/assets/89018301/04951132-abfd-4fbb-a349-4c91d8e98e25)

**Comment by Bshlomecha** [comment]
אכן ייעול חשוב. תודה רבה.
והנני מציע לנסח מחדש את ההגדרות והכותרות למאגרים בהתאם לרוח בית המדרש..
וכמו"כ את התאריכים לתרגם לתאריכים עבריים כמובן.

**Comment by Sivan22** [comment]
רעיון טוב. לגבי החלק השני אני יכול לכתוב סקריפט שיעשה את זה, אבל החלק הראשון הוא עבודה ידנית, אז העליתי קובץ משותף וכל מי שרוצה יכול לערוך אותו. הנה הקישור: https://docs.google.com/spreadsheets/d/1SblOGE8eTUbB6j2D-fjaaaW54IuoTI_rAx8eYKtrygQ/edit?usp=sharing

**Comment by Danthig** [comment]
> רעיון טוב. לגבי החלק השני אני יכול לכתוב סקריפט שיעשה את זה, אבל החלק הראשון הוא עבודה ידנית, אז העליתי קובץ משותף וכל מי שרוצה יכול לערוך אותו. הנה הקישור: https://docs.google.com/spreadsheets/d/1SblOGE8eTUbB6j2D-fjaaaW54IuoTI_rAx8eYKtrygQ/edit?usp=sharing

לגבי החלק השני (עבודת היד), חייב להיות מוסכמות איך וכיצד לערוך, מכיון שאחרת יהיה לאותה מילה כמה תרגומים.

**Comment by Bshlomecha** [comment]
האם תוכל לערוך רשימה מסודרת של הדברים הראויים לדיון [למשל רשימת מושגים הצריכים תרגום או הגדרות הצריכות עדכון לשפת בית המדרש]?

**Comment by Bshlomecha** [comment]
העפתי מבט ואתה צודק, בתרתי: שהיא עבודה גדולה, וקדושה.

אתחיל בל"נ קמעא קמעא, בתקוה שבמקביל לעבודת לומדים נוספים.

למשל: ספרי המקרא ודאי אינם צריכים בכלל הגדרות ותיאורי תוכן .....

‫בתאריך יום ב׳, 6 במאי 2024 ב-16:34 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
> אתחיל בל"נ קמעא קמעא, בתקוה שבמקביל לעבודת לומדים נוספים.

יישר כוחך!!!
אם לא ייכתבו הוראות ברורות, לדעתי לא כדאי שיהיה יותר מעובד אחד, משום שאני לא מאמין ששני אנשים יתנבאו בסגנון אחד לחלופה של למשל 'תאולוגיה'...

שאגב, ברגע שאתה מוצא חלופה נכונה, תוכל להחליף את הכל על ידי חפש החלף, למען לא תצטרך לעבוד בעבודת נמלים על כל פעם ופעם שמוזכר.

לענין ספרי המקרא, אולי אפשר לכתוב את התיאור החז"לי כגון לויקרא 'תורת כהנים' - עניני הקרבנות. וכדומה.

**Comment by Danthig** [comment]
> אתחיל בל"נ קמעא קמעא

סיון כתב שיותר טוב שיכתבו את תיאורים החדשים בנפרד, זאת אומרת לא למחוק את הישנים, אלא לכתוב בעמודה אחרת, אם ראית עמודת G עכשיו בשם 'תיאור חדש'. 
אם אתה הורדת את החוברת ועובד איתה על אקסל, צריך לחשוב כיצד לעשות את זה, אבל לא לדרוס את החומר הקיים!!! 
(נראה לי בשביל העתיד כאשר ספריא יעדכנו את הספרים, והוא ישאב גם את התיאורים, שלא יצטרכו למחוק מחדש, אלא זה יהיה במקביל).

הספק, סיון רוצה עד סוף בין הזמנים לסיים עם הגרסה 0.17, כך שצריך להזדרז, אולי תכתוב לי מה וכיצד כדי שנוכל להתקדם עם זה.

**Comment by Danthig** [comment]
> העפתי מבט ואתה צודק, בתרתי: שהיא עבודה גדולה, וקדושה. אתחיל בל"נ קמעא קמעא, בתקוה שבמקביל לעבודת לומדים נוספים. למשל: ספרי המקרא ודאי צריכים בכלל הגדרות ותיאורי תוכן ..... בתאריך יום ב', 6 במאי 2024 ב-16:34 מאת Danthig‏ < ***@***.***‏>:

אני עברתי על הכל, (בסתמא התפספס לי משהו), וכתבתי רק את הדברים החשובים ביותר, היכן שצריך למחוק סימנתי ---, ובשאר לא העתקתי לG ולא שיניתי.

**Comment by Bshlomecha** [comment]
טעות סופר שלי. התכוונתי שספרי המקרא *אינם *צריכים הגדרה. נראה לי שאפילו אין
צריך להסביר.

בכל אופן לא נראה לי שאהיה פנוי לעבוד בקצב כזה של להשלים המלאכה היום [מחר
אנחנו מתחילים את הזמן בעה"י, אחה"צ יש יום עיון אצל הרב אפרתי...]
אני שמח ומודה שקריינתא דאיגרתא כוותך להוי פרוונקא מעליא, לתקוני מילתא
ליקרא דאורייתא דאיהי יקרא דמלכא.

*ומתוך רוממות חג חרותנו וספירת העומר בהכנה למתן תורה ונהיגת כבוד זה בזה *[וגם
מתוך אוירת השחרור של בין הזמנים...]* אני מרשה לעצמי להעלות מחשבה קצת מרחיקת
לכת:*

הנה ר' סיון שליט"א עשה עבודה נפלאה ועקף [מימין ?] כמה שניסו לעלות על
שלחן מלכים ולקדם את הענין, מאז שהתכנות הישנות נתקעו רחוק מאחור [תורת אמת,
אורייתא, עם כל חביבותן ותועלתן].
כמובן שאין טעם להתחרות עם בר אילן שיש להם מימון המונים... [ואני נהנה להשתמש
בתוכנה שלהם],
אבל הלוואי אם היה אפשר לאחד כחות וכשרונות ויכולות, של כל העוסקים במלאכת
הקודש, ולקחת מכל אחד הטוב והמעולה שבו
- ביניהם *תא שמע* [שיש לו ממשק מפותח אבל כמות הספרים דלה (בחינמית)], *רבותינו
*[שעשה רושם הכי מקצועי אבל אינני יודע היכן הדברים אוחזים], *DBS *[שיש להם
כמות אדירה של חומר אבל ממשק גרוע ומיושן], *סטנדר *[שהיה לו רעיון אדיר של
הגהה ציבורית, אבל נתקע באמצע הדרך, וכנראה בגלל שאי אפשר לתפוס החבל משני
קצותיו, המוניות ודייקנות, במיוחד שמנסים לתפוס שני קצוות רחוקים, כי התוכנה
מיועדת למי שאין לו חיבור זמין לרשת תדיר, ומאידך אינה פונה למי שאין לו
שייכות לרשת כלל...].
ואולי אפילו *מרכבה *[אלא שמשום מה הם עושים עלי רושם חשוד, לא פחות
מספרייא...].
ועל כולם *שיתופתא*, שהרעיון של הערות אישיות מצא חן בעיני, וגם צורת הדף
האינטראקיטיבית, אבל זה נתקע ג"כ בשלב יחסית מוקדם.... והם במוצהר עובדים על
מנת להגדיל תורה, ומערכת שלהם הכי קרובה לממשק של ספריא, כך שיש על מה לבנות.

האם זה חזון אחרית הימים ? האם לא הגיע הזמן שיבינו כולם שאין שוק מספיק גדול
בשביל להתחלק בו, ומאידך חבל על כל שבכל חיפוש צריך לעבור ארבעה וחמשה כלים
שונים, כל אחד ומעלותיו, במקום לקבץ הטוב מכולם אל מקום אחד ?

אני לא תמים. אבל אולי אם תהיה מוצבת מטרה עליונה כזו - יש מקום לקוות שיותר
ויותר יצטרפו אליה, ובסופו של דבר אולי גם ירויחו, כמו הרבה מערכות ציבוריות
שבסופו של דבר משתלמות לכולם, ומזה ומזה תסתיים שמעתא ויתקלס עילאה.

‫בתאריך יום ב׳, 6 במאי 2024 ב-21:55 מאת ‪Danthig‬‏ <‪
***@***.***‬‏>:‬

**Comment by Sivan22** [comment]
דעתי הקלושה בעניין: מדובר על טכנולוגיות מאד שונות ולכן קשה לחשוב על לאחד
הכל ביחד. ואם הכוונה ליצור גוף אחד שיתכלל הכל, אז מדובר על עלות אסטרונומית.
בדרך כלל זה מפתח בודד בהתנדבות (תורת אמת, אוצריא) או יזם שרוצה להרוויח (תא
שמע, רבותינו) או להועיל לכלל (סטנדר), ולא גוף משמעותי מספיק.

בכל אופן רציתי לומר שהפרוייקט שלי לא היה מתאפשר ללא המאגר שספריא מיינו
וקטלגו וקישרו, (אין ספק שזהו הקושי וגם העלות הגדולים ביותר). ואת הספרים הם
לקחו ממאגרים קודמים פתוחים כולל תורת אמת. אז יש בהחלט תועלת בכל פרויקט והם
מועילים גם אחד לשני.

בתאריך יום ג׳, 7 במאי 2024, 11:27, מאת Bshlomecha ***@***.***

**Comment by Y-PLONI** [comment]
אם סיון יסכים לפתח עריכה [או יצליח להכניס את הקוד של סטנדר איכשהו], אז כבר הכללת את סטנדר. תורת אמת מוכללת מינה ובה [יש 42 ספרים פלוס מינוס שמחכים לסקריפטים של סיון], וכולי.
כלומר - במסגרת היכולות שלנו - או יותר נכון של סיון, זה הרבה מאוד. המון.
אבל הדבר היחיד שיכול להועיל באמת, זה לגייס איזה מפתח לעניין. אני חושד שהמפתח של תוכנת "וייב" [VIBE] הוא חרדי, אבל אין לי מושג מיהו באמת, ואם הוא יודע להתעסק בספרייה של סיון [למה לקחת ספרייה כזו נדירה?]

**Comment by Bshlomecha** [comment]
אודה ולא אבוש כי כשעברתם לדבר בענייני תכנות - אין לי בזה קצה של הבנה והשגה.
אשריכם שאתם מנצלים את כישוריכם וכשרונותיכם בענין הקדוש הזה, כי 'מה תקוַת
הנברא אם לא ישים עמל נפשו בעניינים אשר נברא בעבורם', וזכות הרבים תלויה בכם.
יישר כח לכל היוזמים והפועלים והעוזרים והמסייעים.
ותודה על שהעמדתם אותי על האמת, כי אכן גם בלא לשתף את המערכות יחד - באמת
יכולים כולם להיות שותפים במגמה הגדולה, ולכולם חלק בהתפתחות התהליך.

אגב, מן הסתם אתם יודעים גם המפתח של הפלטפורמה הבסיסית של 'סטנדר' הוא כנראה
חרדי [מחו"ל?], ר' יהודה נויפלד. יהודה נויפלד - קהילת DEV
<https://dev.to/yiddishekop> https://yiddishe-kop.com/

‫בתאריך יום ג׳, 7 במאי 2024 ב-21:46 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬
