### ISSUE TITLE
מחוות החלקה ימינה ושמאלה בקבצי PDF לא עובדת

### ISSUE THREAD

**Issue by NHLOCAL** [Sivan22/otzaria#77]
בתוכנה ישנה אפשרות להחליק עם העכבר לימין ושמאל כדי לעבור בין הכרטיסיות.
משום מה בקבצי PDF התכונה לא עובדת

**Comment by Sivan22** [comment]
בדקתי את זה ודוקא כן עבד לי. אולי רק כשהדף מוגדל זה לא עובד כדי לגלול את הדף.

**Comment by NHLOCAL** [comment]
בדקתי כעת שוב - בחלק מהמקרים זה עובד ובחלק לא.
יתכן שזה קשור לגודל
