### ISSUE TITLE
לא מוצא את הפונקציה של הצגת חלון הפרשנים במפוצל לרוחב

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#78]
בעמוד releases רשום שהתכונה הזו נוספה בגירסת 0.1.6+ התקנתי, ואני לא מוצא את הפונקציה הזו, אולי זה באג?

**Comment by Danthig** [comment]
זה נמצא בהגדרות:
![image](https://github.com/Sivan22/otzaria/assets/161762042/94770ef0-d8fc-417c-a445-0c0735566cdd)

**Comment by Refael11** [comment]
אה.. תמחק את כל הISSUE
