### ISSUE TITLE
גלילת פרשנים במאונך

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#79]
כאשר מגיעים לסוף הספר ובחרו פרשנים, עמוד הפרשנים נגלל בהתאמה למקור כאשר הוא מגיע לקצה העליון של התוכנה, אך כאשר ישנם במקור פסקאות קצרות כמו פסוקים או משניות, הפרשנים על הפסקאות האחרונות שאינם יכולים להגלל ללמעלה, אינם מופיעים בלחיצה על טקטס המקור, אלא צריך לגלול את הפרשנים בנפרד:
![image](https://github.com/Sivan22/otzaria/assets/161762042/baca4d53-2eb2-414b-9eb8-b509cc9b31a3)

![image](https://github.com/Sivan22/otzaria/assets/161762042/6a7b2221-a381-424e-b447-6f3721512051)

אני חושב שיהיה תועלת גדולה אם הפרשנים יגללו בהתאמה ללחיצה על המקור כמו בתצוגה מאונכת. 
יישר כח!!!

**Comment by Sivan22** [comment]
הפרשנים הם על כל הטקסט שבצד ימין.

**Comment by Sivan22** [comment]
לאור בקשות נוספות של משתמשים, האפשרות נוספה (בגרסאות החל מ 0.1.7+2). תוך כדי הגלילה מוצגים הפרשנים על כל הקטעים הגלויים, ובלחיצה על קטע מסויים מוצגים הפרשנים רק על אותו קטע.
