### ISSUE TITLE
התוכנה לא מוצאת ספרים בגרסא החדשה

### ISSUE THREAD

**Issue by AshiVered** [Sivan22/otzaria#8]
גרסא 0.1.2
![image](https://github.com/Sivan22/otzaria/assets/76535872/97b68d8c-59dc-42ef-9ebf-eebb58b2ecd1)

**Comment by Sivan22** [comment]
יש להגדיר את מיקום הספריה מעל תיקיית אוצריא, בתיקייה בה נמצאים התיקייה "אוצריא" וכן "links". (בשונה מהגרסאות הקודמות)

**Comment by AshiVered** [comment]
תודה.
ומה זה המלבן האדום בפינה השמאלית למטה?

**Comment by Sivan22** [comment]
פס גלילה. שיניתי עכשיו את העיצוב:
![image](https://github.com/Sivan22/otzaria/assets/89018301/839f8bac-b8b0-4456-90e6-6dc65818357b)
