### ISSUE TITLE
הוספת מספר תוצאות ב'איתור ספר'.

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#81]
### Motivation
אולי יש כאלו שלא יבינו מה הענין, אבל אני חושב שזה מאוד שימושי ומועיל.

**Comment by Y-PLONI** [comment]
לא הבנתי את כוונתך.
![image](https://github.com/Sivan22/otzaria/assets/116633732/ed8dc913-e9c4-4977-a9a4-4e91a11a89d3)

**Comment by YOSEFTT** [comment]
מה לא מובן???
אני רוצה שיראה ככה:
![צילום מסך 2024-05-04 214510](https://github.com/Sivan22/otzaria/assets/166497965/62e94b70-5465-40aa-a90b-a56db35d72b5)
את ה - 9 אני הוספתי כמובן, לצורך הדגמה, הוא עדיין לא נמצא בתוכנה, ואת זה אני רוצה שהוא יוסיף.

**Comment by Sivan22** [comment]
לא בתכנון כרגע

**Comment by Y-PLONI** [comment]
למה?
