### ISSUE TITLE
רבנו חננאל לא מופיע ב'פרשנות' של חלק ממסכתות הש"ס [למרות שהוא נמצא בתוכנה על אותם מסכתות. יש מסכתות שהוא כן נמצא ב'פרשנות'].

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/otzaria#82]

**Comment by YOSEFTT** [comment]
כנ"ל 'פסקי הרא"ש' לא מופיע בתור פרשן על מסכתות קטנות, למרות שהוא מופיע בתוכנה עליהם [בתוך פסקי הרא"ש למסכת מנחות].

**Comment by Y-PLONI** [comment]
https://github.com/Sivan22/otzaria/issues/59#issuecomment-2091848640
