### ISSUE TITLE
מקש החלפת טקסט לPDF.

### ISSUE THREAD

**Issue by Y-PLONI** [Sivan22/otzaria#83]
מציע להוסיף כפתור, שבלחיצה עליו התוכנה תחליף את תצוגת הספר מפורמ טטקסט ל- PDF ולהיפך.
הרעיון שאני מציע, שכשהתוכנה תראה 2 קבצים עם אותו השם, עם 2 סיומות [לענייננו: אחד עם סיומת PDF ואחד ללא סיומת], כפתור האיתור [או העיון, כלומר: כפתור פתיחת הספר] יציג 2 אפשרויות, פתיחת PDF ופתיחת טקסט*. גם בתוך הספר עצמו יתווסף כפתור כזה, להחלפה מהירה בין טקסט לPDF.
קבצי הPDF יוכלו להיות בתוך מסד הנתונים, או בנפרד, כי התוכנה תזהה אותם לבדה.
ישנו קושי מסויים ברעיון, במקרה שהמשתמש נמצא במיקום מסויים בספר, **ובספר לא יהיו סימניות,** כך שלא יהיו דפים מקבילים, ובלחיצה על הכפתור המשתמש יוחזר לתחילת הספר. אם בספר יהיו סימניות, ניתן להגדיר שאם שמות הסימניות שווים המשתמש יועבר למיקום הנכון.
בתוכנה החינמית [וקוד פתוח] SumatraPDF יש תכונה שזוכרת את המיקום האחרון בקבצי PDF.
אשמח להתייחסותך, @Sivan22 , כי לייצר קבצים עם סימניות זו עבודה די רצינית, ואני רוצה לנצל את הימים שנותרו לביה"ז.

*חשבתי על כיוון, שהכפתור יהיה מחולק ל2, ימין ושמאל

**Comment by Sivan22** [comment]
זה אפשרי, רק שאני לא יודע כמה זה שימושי לעבור מתצוגה לתצוגה, אולי רק בש"ס זה נחמד, אבל לדעתי רוב הספרים אם יש אותם בטקסט אין צורך בצילום הדף. PDF זה בעיקר בשביל ספרים שאין להם טקסט (בהיברובוקס יש יותר מ50000 ספרים, באוצריא יש פחות מ 6000) 
בכל אופן סימניות לקבצי PDF זה כן שימושי מאד, כבר עכשיו, כך אפשר לנווט בספר בקלות. אבל זה ממש עבודת נמלים. (לש"ס אפשר ליצור סקריפט אבל ספרים אחרים צריך לעבור על הספר כולו ולמצוא את ראשי הפרקים)

**Comment by Danthig** [comment]
> זה אפשרי, רק שאני לא יודע כמה זה שימושי מתצוגה לתצוגה, אולי רק בש"ס זה נחמד, אבל לדעתי רוב הספרים אם יש אותם בטקסט אין צורך בצילום הדף. PDF זה בעיקר בשביל ספרים שאין להם טקסט (בהיברובוקס יש יותר מ500000 ספרים, באוצריא יש פחות מ 6000) בכל אופן סימניות לקבצי )

לכאורה צורת הדף חשוב מאוד בש"ס ומשנה ברורה, ורצוי גם בשו"ע, ויהיה נחמד גם למקראות גדולות, אבל כל שאר הספרים לדעתי אינם צריכים צורת הדף. 
אמנם בספר עם הערות על הערות על הערות, כמו למשל טעמי המנהגים ומקורי הדינים קובץ PDF יכול לעזור בתצוגה.

**Comment by YOSEFTT** [comment]
גם בסידור מועיל מאוד צורת הדף

**Comment by Y-PLONI** [comment]
אני דווקא חושב שזה שימושי. לא סתם אוצה"ח נשארים בPDF, לא בגלל יכולות, אלא בגלל שהרבה מאוד אנשים רוצים דווקא PDF. אני אישית אשמח שיהיו שניהם.
בכל מקרה, אפילו לדעת @Danthig כדאי ביותר מהש"ס, וזה רלוונטי.
אני מסכים אתך, @Sivan22 שזו עבודת נמלים, אני מתכנן לעשות אותה באופן שיתופי [במתמחים, יהיה מי שיעשה], אבל אני צריך את ההוראות שלך: איך תרצה לתכנן את הסימניות, כך שהתוכנה תזהה אותן?

**Comment by Danthig** [comment]
> גם בסידור מועיל מאוד צורת הדף

אתה יכול גם כעת להוסיף איזה סידור שאתה רוצה כPDF, למה סתם להכביד על התוכנה? כבר כעת היא מציגה PDF בצורה יפה ביותר!
מה ההגיון ליצור קישוריות בין הPDF לטקסט, זה כמעט לא שימושי בסידור.

**Comment by YOSEFTT** [comment]
@Danthig  אתה צודק, התכוונתי לומר שבסידור מאוד חשוב צורת הדף, ולכן כדאי שיהי' בתוכנה סידור עם צורת הדף, אבל באמת זה לא קשור לנושא הזה כלל.

**Comment by YOSEFTT** [comment]
>אני דווקא חושב שזה שימושי. לא סתם אוצה"ח נשארים בPDF, לא בגלל יכולות, אלא בגלל שהרבה מאוד אנשים רוצים דווקא PDF. אני אישית אשמח שיהיו שניהם.
לפי דעתך, למה באוצר החכמה אין גם טקסט כמו שאתה מציע שיהי' כאן?

**Comment by Sivan22** [comment]
הסימניות הן סטנדרטיות בPDF אפשר להוסיף אותן בכל תוכנת עריכה של PDF.

בתאריך שבת, 4 במאי 2024, 22:57, מאת Danthig ***@***.***>:

**Comment by Y-PLONI** [comment]
> לפי דעתך, למה באוצר החכמה אין גם טקסט

כי זה הקו שלהם. זה דיון פילוסופי מעניין, אך לא קשור לכאן. המציאות היא שתוכנות הספרים הגדולות אינן טקסט אלא PDF.

> הסימניות הן סטנדרטיות בPDF אפשר להוסיף אותן בכל תוכנת עריכה של PDF.

ואז? כלומר, מה זה עונה? לא הבנתיך!

**Comment by YOSEFTT** [comment]
דברתי עם @Y-PLONI, והוא מתכוין לשאול, האם בשביל שהתוכנה תזהה את הסימניות של השס שבתוכנה ושל השס שבפי די אף כסימניות מקבילות, צריך שיהי' לשתיהם את אותו שם של סימני', או איזשהו מזהה אחר. או שלא משנה מה שם הסימני', ואוצריא כבר תדע להתמודד עם זה.

**Comment by Sivan22** [comment]
צריך שיהיה אותו שמות ומבנה היררכי של סימניות בדיוק, ואז איכשהו אפשר לקשר
ביניהם.

בתאריך יום א׳, 5 במאי 2024, 16:00, מאת יוסף ***@***.***>:

**Comment by Y-PLONI** [comment]
כלומר: אתה רוצה שיהיה כתוב בסימניה: קידושין דף מ עמוד ב
ככה?

**Comment by adyady148** [comment]
לע"ד, י**שנה חשיבות לתת אפשרות של הקבלת צורת הדף לקבצי הטקסט** בכל ספר שהדבר מתאפשר, ומכמה טעמים:

א. מועיל לזכרון חזותי [למי שזו הגירסא של המעבד שניתן לו במוחו...]
ב. נותן אפשרות להגהה ותיקון, ואם תהיה אפשרות עריכה - [בבקורת של מפעילי התוכנה, כמובן] - גם לערוך כותרות וכד'.
ג. מועיל לעריכת דפי מקורות וכדומה.
 [ואולי עוד טעמים].
כמובן שהדבר תלוי בשיקול דעתכם אם להשקיע בזה ע"ח הסמן של הכנסת ספרים נוספים חדשים וכיו"ב...

ושוב ושוב ייש"כ.

**Comment by Y-PLONI** [comment]
לסגור, או כיון שזה עדיין לא רשמי, לא?

**Comment by Sivan22** [comment]
יתווסף בעזרת ה' בגרסה הבאה.
