### ISSUE TITLE
חזון איש אמונה ובטחון - ניקוד מוטעה

### ISSUE THREAD

**Issue by Bshlomecha** [Sivan22/otzaria#86]
ספר חזון איש אמונה ובטחון הוא ספר יסוד נכבד, וטוב שהוסיפוהו למאגר. 
אבל ראוי להגיה היטב הניקוד [בכל ספר, וכל שכן בלשון מסובכת ובלי שגרתית כמו לשונו של החזו"א].

דוגמא לדבר - פרק א' אות ג' :
'וּמַנְעִימוֹת הַחֲכָמָה לַחְזוֹת בְּקֶשֶׁר שֶׁל הַחַיִים עִם אֲוִיר הָעוֹלָם, הָאָצוּר בַּחִמְצֵי וּפֶחָמִי...'
כמובן צ"ל '**ומִנעִימוֹת** **החָכְמָה'** או '**ומִנעימוּת** החכמה'
וכן 'בְּחִמְצִי וּפֶחָמִי' - כלומר בחומר החמצן וחומר הפחמן...

ושם אות ד': 'עוֹד יִגְדַּל מַחֲזֵה הַפְּלָאוֹת הִתְהַפְּכוּת הַשְׂכֵּל'' צ"ל '**הַשֶׂכֶל'**.

ובאות ה':  וְלָתֵת לוֹ תְּהִלָּה וּשְׁבָח צ"ל '**וְשֶׁבַח'**.

ובאות ז': רַב הַהֶרְגֵּל מַכְהֶה אֶת רֶגֶשׁ הִתְפַּעֲלוּת הַנֶפֶשׁ צ"ל רוֹב ההרגל ?

ושם: ובר"ש שָּׁם חַיָהּ שֶׁשְּׁמָהּ יַדּוּעַ כו' לכאורה צ"ל 'יִדוֹעַ' [עשה"כ אוב וידעוני]
 -
באות יא [ולבטל הניקוד בכותרת]: יֵשׁ אִישׁ מִתְאַוָּה לְהָשִׁיב לְזוּלָתוֹ, הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא, לוֹ לְחֶדְוַת לֵב, 
צ"ל **להֵטיב** לְזוּלָתוֹ, הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא, לוֹ לְחֶדְוַת לֵב
 ..- ...
ובאות טו: וּבְהַכָּרַת בּוֹרְאוֹ יִתְבָּרַךְ יִמָּצֵא פִתְרוֹן הַחִידָה שֶׁל הָעוֹלָם כּוּלוֹ אֲשֶׁר הִדְרִיכָהּ מְנוּחָתוֹ לְלֹא הֲפוּגוֹת. צ"ל 'יִמְצָא'.

[מסתמא יש עוד הרבה, כתבתי מה שעלה נגד עיני עתה].

באות יא [ולבטל הניקוד בכותרת]: יֵשׁ אִישׁ מִתְאַוָּה לְהָשִׁיב לְזוּלָתוֹ, הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא, לוֹ לְחֶדְוַת לֵב, 
צ"ל **להֵטיב** לְזוּלָתוֹ, הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא, לוֹ לְחֶדְוַת לֵב
 ..- ...
 -

**Comment by Bshlomecha** [comment]
טעות נפלה גם בהערתי:
הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא, לוֹ לְחֶדְוַת לֵב
צ"ל הִפַּגְּשׁוֹ עִם רֵעֵהוּ הוּא לוֹ לְחֶדְוַת לֵב

**Comment by Sivan22** [comment]
מי ששלח לי את זה כתב שהוא באמצע להגיה את הניקוד...

**Comment by Bshlomecha** [comment]
ייש"כ. אולי כדאי להעיר על זה בתחילת הספר בינתיים, לבלי להשכין באהלנו עוולה.

‫בתאריך יום א׳, 5 במאי 2024 ב-21:12 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
תוכל להגיה את זה ולשלוח, כך תהיה ממזכי הרבים. 
יכול להיות שעדיף שיהיה בתוכנה בלי ניקוד כלל, מאשר עם ניקוד חלקי שכזה...

**Comment by Refael11** [comment]
שימו לב גם לניקוד שהשתרבב בטעות לכותרות הניווט

![image](https://github.com/Sivan22/otzaria/assets/165617135/03891159-0f0c-4a2f-a281-9a6c68b3cdc2)
