### ISSUE TITLE
אפשרות הסתרת ניקוד

### ISSUE THREAD

**Issue by Refael11** [Sivan22/otzaria#87]
אפרופו הISSUE הקודם, כדאי להוסיף כפתור שדרכו אפשר יהיה להסתיר את הניקוד,
יש הרבה שהניקוד מפריע להם במיוחד בתלמוד בבלי, ומאידך יש הרבה שזה יכול להועיל להם מאוד
האופציה של להסתיר ניקוד מאפשרת לשניהם להפיק תועלת מרבית מהתוכנה

**Comment by Danthig** [comment]
@Sivan22 [לעיונך](https://tchumim.com/topic/15886/js-%D7%9C%D7%9B%D7%91%D7%95%D7%AA-%D7%95%D7%9C%D7%94%D7%A4%D7%A2%D7%99%D7%9C-%D7%A0%D7%99%D7%A7%D7%95%D7%93-%D7%95%D7%98%D7%A2%D7%9E%D7%99%D7%9D) אולי יעזור.

**Comment by Y-PLONI** [comment]
צריך לתת הגדרה שהתוכנה תתעלם מתווי יוניקוד מרמה X ומעלה, לא?
כך אמר לי בשעתו האדם החושב.

**Comment by Sivan22** [comment]
יש לי כבר את הקוד להעלמת ניקוד, החיפוש בטקסט מנוקד הוא ללא ניקוד, רק צריך
להוסיף כפתור וכמובן את הקוד מאחורה לנהל את זה.

בתאריך יום ב׳, 6 במאי 2024, 20:23, מאת Y-PLONI ***@***.***>:

**Comment by Sivan22** [comment]
נוסף בגרסה 0.1.7
