### ISSUE TITLE
RAM גבוה בתוכנה המותקנת

### ISSUE THREAD

**Issue by Danthig** [Sivan22/otzaria#89]
אותו שימוש באוצריא הנייד השתמש בכ500 MB, ואילו בתוכנה המותקנת אותו שימוש בדיוק גבה כ1,800 MB RAM!!!

**Comment by Sivan22** [comment]
יש בעיות מסויימות של דליפת זכרון, מקווה שבעתיד הם יטופלו. כרגע לא מומלץ לסגור ספר PDF תוך כדי הטעינה, משום שהזכרון לא ישתחרר, צריך לחכות שהוא ייטען במלואו ואז ניתן לסגור את הכרטיסייה והזכרון ישתחרר.

**Comment by natireed** [comment]
אני חושב שמדובר בבעיה של ממש שמתילב שהדבר מאט מאד את קצב העבודה ולאחר שמחקתי את התוכנה והתקנתי מחדש חזר לתפקד במהירות אולי אפשר לציין פתרון זמני לניקוי הזכרון בלי כל הפורצדורה של מחיקת הכל והתקנה מלאה.

**Comment by YOSEFTT** [comment]
הפתרון כשהתוכנה נתקעת, זה למחוק את תיקיית otzaria שבתוך תיקיית com.example שבתוך תיקיית Roaming שבתוך תיקיית AppData שבשם המשתמש שלך.
[גם זה כבר כתוב במדריך של [@דאנציג](https://mitmachim.top/uid/4785) ].

**Comment by Danthig** [comment]
אולי מן הראוי לפתוח לפתוח אישוי עם[ המדריך שכתבתי במתמחים](https://mitmachim.top/post/798584) @YOSEFTT מה אתה אומר על כך?
האמת היא שזה קשור יותר ל @Sivan22 ...

**Comment by YOSEFTT** [comment]
לא הבנתי כוונתך @Danthig
