### ISSUE TITLE
במצב כהה, הטקסט אינו מוצג כראוי בביצוע חיפוש

### ISSUE THREAD

**Issue by HeroldGr** [Sivan22/otzaria#9]
<img width="960" alt="image" src="https://github.com/Sivan22/otzaria/assets/103885041/e3aea60d-20f0-4520-afde-f7b66e34177b">

תודה על התוכנה!

**Comment by Sivan22** [comment]
תודה על הדיווח, הבאג תוקן עבור הגירסאות הבאות.
![image](https://github.com/Sivan22/otzaria/assets/89018301/03465427-b15a-42eb-a8e1-cc128e51f3b8)
