### ISSUE TITLE
יש ליישר למרכז את טקסט התיאור "איתור ספר" בסרגל הצד

### ISSUE THREAD

**Issue by NHLOCAL** [Sivan22/otzaria#90]
- טקסט התיאור של הכפתור "איתור ספר" מיושר לצד שמאל במקום להיות מיושר למרכז
זהו שיפור קטן אבל חשוב

**Comment by Danthig** [comment]
מה הכוונה מיושר לשמאל? אצלי הוא מוצג כך:
![image](https://github.com/Sivan22/otzaria/assets/161762042/51324540-074d-43b7-aedf-b802ee745680)

**Comment by Sivan22** [comment]
לא רלוונטי לגרסה 0.1.7
