### ISSUE TITLE
הוספת תצוגה מתאימה לחיפוש במקרה שלא נמצאו תוצאות

### ISSUE THREAD

**Issue by NHLOCAL** [Sivan22/otzaria#91]
- לא קיימת תצוגה תואמת לתפריט החיפוש במקרה שלא נמצאו תוצאות
מומלץ להוסיף זאת - שיפור קטן אבל חשוב לממשק

**Comment by YOSEFTT** [comment]
כבר כתבתי פעם אישיו כאן ע"ז.
