### ISSUE TITLE
דף הורדה מהיברובוקס, דרך התוכנה

### ISSUE THREAD

**Issue by chezfo** [Sivan22/otzaria#92]
## Summary
פאנל הורדה וחיפוש בהיברו בוקס.

### Basic example
הרעיון הוא כזה.
יהיה לחצן "חפש ספר ב היברו בוקס"
ואז יזינו את שם הספר או שם המחבר
ואז ייפתח הדפדפן של היברו בוקס לפי החיפוש, עם דף ההורדה.
ואז הורד את הספר
מכאן ואילך אני לא ממש יודע איך להמשיך, כי צריך שהספר יהיה בתוך התוכנה, ויכנס לאינדקס.
אבל הכיוון ברור.

### Motivation
זה חשוב מאוד, שמי שצריך ספר יוכל להוריד אותו בקלות ובנוחות.

#### EXTRA
התוכנה תשמור log של הספרים שהורדו מהיברו בוקס
וכך המפתחים ידעו אלו ספרים כדאי להוסיף לbasic של התוכנה.

**Comment by Danthig** [comment]
https://github.com/Sivan22/otzaria/issues/34

**Comment by chezfo** [comment]
תודה.
יש כאן כמה תוספות, לפני שמאחדים את הבעיות

1. שמירת לוג של הבקשות
2. אופן אחר של חיפוש בלי קובץ אקסל. יעזור בשביל ספרים חדשים.

**Comment by Danthig** [comment]
> אופן אחר של חיפוש בלי קובץ אקסל. יעזור בשביל ספרים חדשים.

אם כבר מדברים על חיפוש דרך האתר, יש את [היברובוקס בטא](https://beta.hebrewbooks.org/home#gsc.tab=0), שהוא הרבה יותר נוח, והרבה יותר מהיר!!!

**Comment by Sivan22** [comment]
זה בתכנון. בודק אפשרות של מסד נתונים מקומי או רק בצורה מקוונת דרך API כמו
שעשו hebrewbooksbot.

בתאריך יום ד׳, 8 במאי 2024, 12:20, מאת Danthig ***@***.***>:

**Comment by chezfo** [comment]
> כמו שעשו hebrewbooksbot.

אני לא מכיר.
תוכל לרשום קישור?

**Comment by chezfo** [comment]
אתה מתכוון לזה
https://github.com/david-lev/hebrewbooksbot

למה לא לשלב את הפרוייקט עצמו?

**Comment by Sivan22** [comment]
זה לא אותה שפה.

בתאריך יום ד׳, 8 במאי 2024, 20:18, מאת noty ***@***.***>:

**Comment by YOSEFTT** [comment]
בקשר למה שכתב @Sivan22 
>בודק אפשרות של מסד נתונים מקומי או רק בצורה מקוונת דרך API כמו
שעשו hebrewbooksbot.

לכאו' עדיף גם וגם, ונפק"מ למי שלא מחובר כרגע [או תמיד] לרשת.
[כמו רוב משתמשי התוכנה, כך מסתבר].

**Comment by zevisvei** [comment]
לגבי אוצר החכמה:
לכאו' צריך לחלק את זה ל2 חלקים, א': פתיחת התוכנה (למי שיש), ב' - פתיחה באתר
לגבי פתיחה בתוכנה בצורה שמוסברת [כאן](https://mitmachim.top/topic/62764/%D7%A9%D7%99%D7%AA%D7%95%D7%A3-%D7%A7%D7%99%D7%A6%D7%95%D7%A8-%D7%93%D7%A8%D7%9A-%D7%91%D7%A9%D7%95%D7%9C%D7%97%D7%9F-%D7%A2%D7%91%D7%95%D7%93%D7%94-%D7%9C%D7%A1%D7%A4%D7%A8-%D7%95%D7%A2%D7%9E%D7%95%D7%93-%D7%9E%D7%A1%D7%95%D7%99%D7%99%D7%9E%D7%99%D7%9D-%D7%91%D7%90%D7%95%D7%A6%D7%A8-%D7%94%D7%97%D7%9B%D7%9E%D7%94) זה משתנה מאדם לאדם, איזו גיר' וחבילות יש לו, לכן לכאו' צריך יהיה לתת למשתמש להכניס את רשימת הספרים שלו (ניתן לייצוא מהתוכנה בדרך הבאה:
![סופי](https://github.com/Sivan22/otzaria/assets/101482799/e5e10649-f943-4515-8f6f-389119120f40))
לגבי פתיחה באתר זה מבוסס על אותו עיקרון, רק מה שצריך יהיה להשיג זה את רשימת כל הספרים כולל הid שלהם,משום מה באתר רשימת הספרים לא כוללת id,אבל ניתן יהיה להשיג רשימה מאחד שיש לו את הגיר' האחרונה כולל כל החבילות שייצא את הרשימה בדרך הנ"ל

**Comment by mendelg** [comment]
It's possible, and I'd like to contribute, @Sivan22 

The question is regarding copyright.

I've found that you can use the following endpoint to search for a book:
```
https://beta.hebrewbooks.org/generic.aspx?search=true&title=%D7%A9%D7%9C%D7%95%D7%9D%20%D7%95%D7%91%D7%A8%D7%9B%D7%94&auth=&ocr=
```

The request parameters are:
```json
{
  "search": true,
  "title": "שלום וברכה",
  "auth": "",
  "ocr": ""
}
```

You can then download it through:
```
https://download.hebrewbooks.org/downloadhandler.ashx?req=41657
```

### Regarding Copyright:

How do we deal with API access/copyright for Hebrewbooks?

**Comment by Sivan22** [comment]
I got this email from hebrewbooks:

We noticed that you are planning to provide functionality to access

our site and download PDFs automatically. Please be advised that this

is something that will put the availability and security of our site

and other users at risk, and is against our terms of use. We

Are requesting you stop plans for this functionality immediately.

[End of email.]

So using the API is prohibited.

בתאריך יום א׳, 7 ביולי 2024, 18:26, מאת mendelg ***@***.***>:

**Comment by Y-PLONI** [comment]
זו טעות. הם לא הבינו אותך.
אין שום מניעה!

**Comment by mendelg** [comment]
@Sivan22   I agree with @Y-PLONI 

maybe they didn't understand, your email?
what was the email wording like?

Unless that's just a way of saying 'no'

**Comment by Sivan22** [comment]
We probably could still search localy on the device (using a catalogue) and link to the do download page, to open it in the browser, not using the API at all.

**Comment by Y-PLONI** [comment]
נכון! מצויין!

**Comment by mendelg** [comment]
Interesting.
I tried to search for a catalog, but couldn't find one.

So, how would we go about getting all the data?
scraping it?

**Comment by Sivan22** [comment]
@mendelg send me please an email to my personal address, i would like to cooperate with you!

**Comment by mendelg** [comment]
@Sivan22 Sure, I just don't know your personal email address. I couldn't find it..

**Comment by YOSEFTT** [comment]
מופיע כאן בקובץ README בסוף
https://github.com/Sivan22/otzaria
