### ISSUE TITLE
בירור על גרסה חדשה, הוספת ספרים, וגרסה למק.

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#93]
מתי יוצא גירסה חדשה וספרים נוספים? והאם יש אפשרות שיצא גירסה גם למק כי ראיתי שיש משיהו במתמחים שכתב שהוא מוכן לקחת את זה על עצמו

**Comment by Sivan22** [comment]
הגרסה הבאה היא בשלבי בדיקה אחרונים. ככל הנראה תהיה אפשרות להורדה בנפרד של
מאגר הספרים של דיקטה (כ580 ספרים). כרגע עדיין לא הסתדרתי עם בנייה למק.

‫בתאריך יום ה׳, 9 במאי 2024 ב-18:54 מאת ‪cc054848484‬‏ <‪
***@***.***‬‏>:‬

**Comment by Danthig** [comment]
> מתי יוצא גירסה חדשה וספרים נוספים? והאם יש אפשרות שיצא גירסה גם למק כי ראיתי שיש משיהו במתמחים שכתב שהוא מוכן לקחת את זה על עצמו

אם אתה רוצה לדעת האם יש התקדמות בגירסה למק, כדאי לך לפתוח נושא חדש במתמחים טופ, [בקטגוריה המתאימה](https://mitmachim.top/category/298/%D7%A2%D7%96%D7%A8%D7%94-%D7%94%D7%93%D7%93%D7%99%D7%AA-macos).

**Comment by YOSEFTT** [comment]
בקשר לספרים נוספים, 
אולי אתה בעצמך, תנסה לחשוב רגע, אולי אתה מכיר איזה מאגר ספרים חופשיים שיש בו ספרים שלא נמצאים בתוכנה?
או אולי אתר מסוים שאפשר למצוא בו את הנ"ל?
האם אתה מכיר מישהו שהוציא לאור איזה ספר של אחד הראשונים או האחרונים, ומוכן לתת אותו למאגר?
אולי תנסה לשכנע אותו?
תחשוב רגע, איזה זיכוי הרבים אדיר זה!! 
כמה אנשים ילמדו בזכותו בספר זה, מהיום ועד..... [עד שיצא תוכנה חדשה, אם בכלל, יקח המון שנים, ממתי שיצא תורת אמת עד עכשיו זה לפחות 25 שנים אם לא הרבה יותר].
ולא רק @cc054848484 , 

גם אתה, 
כן אתה שקורא כרגע הודעה זו, תחשוב, רגע אחד!
וודאי תמצא משהו,
וכל המזכה את הרבים, בלימוד התורה הקדושה אין גבול למתן שכרו!!!!!!!!!!

**Comment by cc054848484** [comment]
ילקוט יוסף עין יצחק שות הראשון לציון.rar
<https://drive.google.com/file/d/1oxdJgE3IsgE4yGPXNN4msWnxYFpS3-FM/view?usp=drive_web>
הקבצים הנ"ל חדשים יותר ממה שיש בהברו בוקס
הקבצים הנל עם אפשריות חיפוש

**Comment by Sivan22** [comment]
הגירסה החדשה כוללת גם תוכנה עבור מק.
