### ISSUE TITLE
  תכונות הדפסה, תכונות עדכון אוטמטי בפתיחת התוכנה ,ספרי החזו"א

### ISSUE THREAD

**Issue by cc054848484** [Sivan22/otzaria#94]
האם בגירסה החדשה יתווסף גם ספרי החזו"א בטקסט? [יש את הטקסט בויקיטקסט.]
האם תהיה אפשרות הדפסה מהתוכנה?
האם אפשר לעשות שיוריד עדכון אוטמטי לתוכנה כשאר זמין?
האם יהיה אפשר באיתור ספר לכתוב דף או סימן בטוש"ע בשו"ת וכו' - שיפתח ישר במקום [כמו שעשה ידידינו בתוסף לתורת אמת לוורד בגירסה החדשה על ידי פסיקים וכדו' שזה מעלה עצומה?
האם החיפוש יהיה יותר מהיר?

תודה רבה ויישר כח עצום! כל הכולל שלנו נהנה מהתוכנה

**Comment by Danthig** [comment]
> האם בגירסה החדשה יתווסף גם ספרי החזו"א בטקסט? [יש את הטקסט בויקיטקסט.] 

לכאורה כן.

>האם תהיה אפשרות הדפסה מהתוכנה? 
לכאורה עדיין לא.
>האם אפשר לעשות שיוריד עדכון אוטמטי לתוכנה כשאר זמין? 
קיים גם עכשיו [עיין כאן](https://github.com/Sivan22/otzaria/issues/7#issuecomment-2094937647).

>האם יהיה אפשר באיתור ספר לכתוב דף או סימן בטוש"ע בשו"ת וכו' - שיפתח ישר במקום [כמו שעשה ידידינו בתוסף לתורת אמת לוורד בגירסה החדשה על ידי פסיקים וכדו' שזה מעלה עצומה? האם החיפוש יהיה יותר מהיר?

[עדיין לא מתוכנן לגרסה 0.2](https://github.com/Sivan22/otzaria/milestone/1).

**Comment by YOSEFTT** [comment]
מהירות החיפוש אמורה להשתפר דרמטית בגירסא 2.0
ע"י אינדקס.
וכן מגוון שיפורים נוספים בחיפוש בגירסא הנ"ל.
