### ISSUE TITLE
 לא רואה מפרשים גירסא 0.1.6

### ISSUE THREAD

**Issue by israelsky** [Sivan22/otzaria#99]
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
<img width="650" alt="מפרשים אוצריא" src="https://github.com/Sivan22/otzaria/assets/167645759/8a12dda0-f50f-48b7-9b46-ebede5344fa9">
<img width="650" alt="מפרשים אוצריא" src="https://github.com/Sivan22/otzaria/assets/167645759/70ae0bd0-b297-4062-96b4-db572b2f72df">

 - Other details that you think may affect.

### Additional context
![image](https://github.com/Sivan22/otzaria/assets/167645759/cab741cf-a552-45e8-ab19-17dd20edd524)

**Comment by Sivan22** [comment]
1. האם שידרגתם מגירסה קודמת?
2. מה מוגדר בהגדרות-> מיקום הספרייה?
3. האם קיימת באותו מיקום תיקייה בשם links?

בתאריך יום ג׳, 14 במאי 2024, 16:11, מאת israelsky ***@***.***

**Comment by Sivan22** [comment]
ראה כאן בעיה דומה: https://github.com/Sivan22/otzaria/issues/39

**Comment by israelsky** [comment]
תודה. אכן הבעיה היתה בנקודה במיקום הספריה

‫בתאריך יום ג׳, 14 במאי 2024 ב-17:20 מאת ‪Sivan22‬‏ <‪
***@***.***‬‏>:‬
